{{- $management := .Values.config.server.management | default dict }}
{{- if and .Values.managementService.enabled (get $management "port") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gestaltd.fullname" . }}-management
  labels:
    {{- include "gestaltd.labels" . | nindent 4 }}
  {{- with .Values.managementService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.managementService.type }}
  ports:
    - port: {{ .Values.managementService.port }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "gestaltd.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
