export default {
  index: "Overview",
  install: "Install",
  "getting-started": "Getting Started",
  "-- server": { type: "separator", title: "Server" },
  configuration: "Configuration",
  plugins: "Plugins",
  security: "Security",
  observability: "Observability",
  "audit-logging": "Audit Logging",
  deploy: "Deploy",
  "-- clients": { type: "separator", title: "Clients" },
  client: {
    display: "children",
  },
  "-- reference": { type: "separator", title: "Reference" },
  reference: "Reference",
  "-- help": { type: "separator", title: "Help" },
  troubleshooting: "Troubleshooting",
};
