export default {
  index: "Overview",
  install: "Install",
  "getting-started": "Getting Started",
  "-- server": { type: "separator", title: "Server" },
  configuration: "Configuration",
  providers: "Providers",
  security: "Security",
  observability: "Observability",
  "audit-logging": "Audit Logging",
  deploy: "Deploy",
  "-- clients": { type: "separator", title: "Clients" },
  client: {
    display: "children",
  },
  "-- advanced": { type: "separator", title: "Advanced" },
  architecture: "Architecture",
  reference: "Reference",
  troubleshooting: "Troubleshooting",
};
