version: 2
updates:
  - package-ecosystem: docker
    directory: /server
    schedule:
      interval: weekly
    commit-message:
      prefix: build

  - package-ecosystem: docker
    directory: /client
    schedule:
      interval: weekly
    commit-message:
      prefix: build

  - package-ecosystem: docker
    directory: /docs
    schedule:
      interval: weekly
    commit-message:
      prefix: build
