version: 2
updates:
  - package-ecosystem: docker
    directory: /gestaltd
    schedule:
      interval: daily
    commit-message:
      prefix: build

  - package-ecosystem: docker
    directory: /gestalt
    schedule:
      interval: daily
    commit-message:
      prefix: build

  - package-ecosystem: docker
    directory: /docs
    schedule:
      interval: daily
    commit-message:
      prefix: build

  - package-ecosystem: cargo
    directory: /gestalt
    schedule:
      interval: daily
    commit-message:
      prefix: build

  - package-ecosystem: cargo
    directory: /sdk/rust
    schedule:
      interval: daily
    commit-message:
      prefix: build

  - package-ecosystem: gomod
    directory: /gestaltd
    schedule:
      interval: daily
    commit-message:
      prefix: build

  - package-ecosystem: gomod
    directory: /sdk/go
    schedule:
      interval: daily
    commit-message:
      prefix: build

  - package-ecosystem: npm
    directory: /gestaltd/ui
    schedule:
      interval: daily
    commit-message:
      prefix: build

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: daily
    commit-message:
      prefix: build

  - package-ecosystem: pip
    directory: /sdk/python
    schedule:
      interval: daily
    commit-message:
      prefix: build
