# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import runtime_provider_pb2 as v1_dot_runtime__provider__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in v1/runtime_provider_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RuntimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSupport = channel.unary_unary(
                '/gestalt.provider.v1.Runtime/GetSupport',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_runtime__provider__pb2.RuntimeSupport.FromString,
                _registered_method=True)
        self.StartSession = channel.unary_unary(
                '/gestalt.provider.v1.Runtime/StartSession',
                request_serializer=v1_dot_runtime__provider__pb2.StartRuntimeSessionRequest.SerializeToString,
                response_deserializer=v1_dot_runtime__provider__pb2.RuntimeSession.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/gestalt.provider.v1.Runtime/GetSession',
                request_serializer=v1_dot_runtime__provider__pb2.GetRuntimeSessionRequest.SerializeToString,
                response_deserializer=v1_dot_runtime__provider__pb2.RuntimeSession.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/gestalt.provider.v1.Runtime/ListSessions',
                request_serializer=v1_dot_runtime__provider__pb2.ListRuntimeSessionsRequest.SerializeToString,
                response_deserializer=v1_dot_runtime__provider__pb2.ListRuntimeSessionsResponse.FromString,
                _registered_method=True)
        self.StopSession = channel.unary_unary(
                '/gestalt.provider.v1.Runtime/StopSession',
                request_serializer=v1_dot_runtime__provider__pb2.StopRuntimeSessionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.PrepareWorkspace = channel.unary_unary(
                '/gestalt.provider.v1.Runtime/PrepareWorkspace',
                request_serializer=v1_dot_runtime__provider__pb2.PrepareRuntimeWorkspaceRequest.SerializeToString,
                response_deserializer=v1_dot_runtime__provider__pb2.PrepareRuntimeWorkspaceResponse.FromString,
                _registered_method=True)
        self.RemoveWorkspace = channel.unary_unary(
                '/gestalt.provider.v1.Runtime/RemoveWorkspace',
                request_serializer=v1_dot_runtime__provider__pb2.RemoveRuntimeWorkspaceRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.StartApp = channel.unary_unary(
                '/gestalt.provider.v1.Runtime/StartApp',
                request_serializer=v1_dot_runtime__provider__pb2.StartHostedAppRequest.SerializeToString,
                response_deserializer=v1_dot_runtime__provider__pb2.HostedApp.FromString,
                _registered_method=True)


class RuntimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSupport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSupport': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupport,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_runtime__provider__pb2.RuntimeSupport.SerializeToString,
            ),
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=v1_dot_runtime__provider__pb2.StartRuntimeSessionRequest.FromString,
                    response_serializer=v1_dot_runtime__provider__pb2.RuntimeSession.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=v1_dot_runtime__provider__pb2.GetRuntimeSessionRequest.FromString,
                    response_serializer=v1_dot_runtime__provider__pb2.RuntimeSession.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=v1_dot_runtime__provider__pb2.ListRuntimeSessionsRequest.FromString,
                    response_serializer=v1_dot_runtime__provider__pb2.ListRuntimeSessionsResponse.SerializeToString,
            ),
            'StopSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSession,
                    request_deserializer=v1_dot_runtime__provider__pb2.StopRuntimeSessionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'PrepareWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareWorkspace,
                    request_deserializer=v1_dot_runtime__provider__pb2.PrepareRuntimeWorkspaceRequest.FromString,
                    response_serializer=v1_dot_runtime__provider__pb2.PrepareRuntimeWorkspaceResponse.SerializeToString,
            ),
            'RemoveWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveWorkspace,
                    request_deserializer=v1_dot_runtime__provider__pb2.RemoveRuntimeWorkspaceRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'StartApp': grpc.unary_unary_rpc_method_handler(
                    servicer.StartApp,
                    request_deserializer=v1_dot_runtime__provider__pb2.StartHostedAppRequest.FromString,
                    response_serializer=v1_dot_runtime__provider__pb2.HostedApp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gestalt.provider.v1.Runtime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gestalt.provider.v1.Runtime', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Runtime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSupport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gestalt.provider.v1.Runtime/GetSupport',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_runtime__provider__pb2.RuntimeSupport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gestalt.provider.v1.Runtime/StartSession',
            v1_dot_runtime__provider__pb2.StartRuntimeSessionRequest.SerializeToString,
            v1_dot_runtime__provider__pb2.RuntimeSession.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gestalt.provider.v1.Runtime/GetSession',
            v1_dot_runtime__provider__pb2.GetRuntimeSessionRequest.SerializeToString,
            v1_dot_runtime__provider__pb2.RuntimeSession.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gestalt.provider.v1.Runtime/ListSessions',
            v1_dot_runtime__provider__pb2.ListRuntimeSessionsRequest.SerializeToString,
            v1_dot_runtime__provider__pb2.ListRuntimeSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gestalt.provider.v1.Runtime/StopSession',
            v1_dot_runtime__provider__pb2.StopRuntimeSessionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gestalt.provider.v1.Runtime/PrepareWorkspace',
            v1_dot_runtime__provider__pb2.PrepareRuntimeWorkspaceRequest.SerializeToString,
            v1_dot_runtime__provider__pb2.PrepareRuntimeWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gestalt.provider.v1.Runtime/RemoveWorkspace',
            v1_dot_runtime__provider__pb2.RemoveRuntimeWorkspaceRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gestalt.provider.v1.Runtime/StartApp',
            v1_dot_runtime__provider__pb2.StartHostedAppRequest.SerializeToString,
            v1_dot_runtime__provider__pb2.HostedApp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
