// Code generated by sdkgen. DO NOT EDIT.

import { create } from "@bufbuild/protobuf";

import * as wire from "../gen/v1/workflow_pb.ts";
import type {
  ApplyWorkflowProviderDefinitionRequest,
  BoundWorkflowTarget,
  CancelWorkflowProviderRunRequest,
  DeleteWorkflowProviderDefinitionRequest,
  DeliverWorkflowProviderEventRequest,
  GetWorkflowProviderDefinitionRequest,
  GetWorkflowProviderRunEventsRequest,
  GetWorkflowProviderRunEventsResponse,
  GetWorkflowProviderRunOutputRequest,
  GetWorkflowProviderRunOutputResponse,
  GetWorkflowProviderRunRequest,
  ListWorkflowProviderDefinitionsRequest,
  ListWorkflowProviderDefinitionsResponse,
  ListWorkflowProviderRunsRequest,
  ListWorkflowProviderRunsResponse,
  SetWorkflowProviderActivationPausedRequest,
  SetWorkflowProviderDefinitionPausedRequest,
  SignalOrStartWorkflowProviderRunRequest,
  SignalWorkflowProviderRunRequest,
  SignalWorkflowRunResponse,
  StartWorkflowProviderRunRequest,
  WorkflowActivation,
  WorkflowActivationTrigger,
  WorkflowAgentMessage,
  WorkflowArray,
  WorkflowDefinition,
  WorkflowDefinitionSpec,
  WorkflowEvent,
  WorkflowEventActivation,
  WorkflowEventMatch,
  WorkflowEventTriggerInvocation,
  WorkflowManualTrigger,
  WorkflowObject,
  WorkflowPathSource,
  WorkflowRun,
  WorkflowRunEvent,
  WorkflowRunTrigger,
  WorkflowRunTriggerKind,
  WorkflowScheduleActivation,
  WorkflowScheduleTrigger,
  WorkflowSignal,
  WorkflowStep,
  WorkflowStepAction,
  WorkflowStepAgentTurn,
  WorkflowStepAppCall,
  WorkflowStepAttempt,
  WorkflowStepExecution,
  WorkflowStepInputSource,
  WorkflowStepOutputSource,
  WorkflowStepWhen,
  WorkflowText,
  WorkflowValue,
  WorkflowValueKind,
} from "../../native-types.ts";
import { fromWireAgentOutput, toWireAgentOutput } from "./agent.ts";
import {
  fromWireAgentToolRef,
  fromWireRequestContext,
  toWireAgentToolRef,
  toWireRequestContext,
} from "./app.ts";
import {
  fromWireTimestamp,
  fromWireValue,
  sanitizeJsonObject,
  toWireTimestamp,
  toWireValue,
} from "./support.ts";
import type { Init } from "../../rpc_support.ts";

export function toWireApplyWorkflowProviderDefinitionRequest(
  value: Init<ApplyWorkflowProviderDefinitionRequest>,
): wire.ApplyWorkflowProviderDefinitionRequest {
  return create(wire.ApplyWorkflowProviderDefinitionRequestSchema, {
    provider: value.provider ?? "",
    ...(value.spec !== undefined
      ? { spec: toWireWorkflowDefinitionSpec(value.spec) }
      : {}),
    idempotencyKey: value.idempotencyKey ?? "",
    ...(value.context !== undefined
      ? { context: toWireRequestContext(value.context) }
      : {}),
  });
}

export function fromWireApplyWorkflowProviderDefinitionRequest(
  value: wire.ApplyWorkflowProviderDefinitionRequest,
): ApplyWorkflowProviderDefinitionRequest {
  return {
    provider: value.provider,
    ...(value.spec !== undefined
      ? { spec: fromWireWorkflowDefinitionSpec(value.spec) }
      : {}),
    idempotencyKey: value.idempotencyKey,
    ...(value.context !== undefined
      ? { context: fromWireRequestContext(value.context) }
      : {}),
  };
}

export function toWireBoundWorkflowTarget(
  value: Init<BoundWorkflowTarget>,
): wire.BoundWorkflowTarget {
  return create(wire.BoundWorkflowTargetSchema, {
    steps: (value.steps ?? []).map(toWireWorkflowStep),
  });
}

export function fromWireBoundWorkflowTarget(
  value: wire.BoundWorkflowTarget,
): BoundWorkflowTarget {
  return {
    steps: value.steps.map(fromWireWorkflowStep),
  };
}

export function toWireCancelWorkflowProviderRunRequest(
  value: Init<CancelWorkflowProviderRunRequest>,
): wire.CancelWorkflowProviderRunRequest {
  return create(wire.CancelWorkflowProviderRunRequestSchema, {
    runId: value.runId ?? "",
    reason: value.reason ?? "",
    ...(value.context !== undefined
      ? { context: toWireRequestContext(value.context) }
      : {}),
    provider: value.provider ?? "",
  });
}

export function fromWireCancelWorkflowProviderRunRequest(
  value: wire.CancelWorkflowProviderRunRequest,
): CancelWorkflowProviderRunRequest {
  return {
    runId: value.runId,
    reason: value.reason,
    ...(value.context !== undefined
      ? { context: fromWireRequestContext(value.context) }
      : {}),
    provider: value.provider,
  };
}

export function toWireDeleteWorkflowProviderDefinitionRequest(
  value: Init<DeleteWorkflowProviderDefinitionRequest>,
): wire.DeleteWorkflowProviderDefinitionRequest {
  return create(wire.DeleteWorkflowProviderDefinitionRequestSchema, {
    definitionId: value.definitionId ?? "",
    ...(value.context !== undefined
      ? { context: toWireRequestContext(value.context) }
      : {}),
    provider: value.provider ?? "",
  });
}

export function fromWireDeleteWorkflowProviderDefinitionRequest(
  value: wire.DeleteWorkflowProviderDefinitionRequest,
): DeleteWorkflowProviderDefinitionRequest {
  return {
    definitionId: value.definitionId,
    ...(value.context !== undefined
      ? { context: fromWireRequestContext(value.context) }
      : {}),
    provider: value.provider,
  };
}

export function toWireDeliverWorkflowProviderEventRequest(
  value: Init<DeliverWorkflowProviderEventRequest>,
): wire.DeliverWorkflowProviderEventRequest {
  return create(wire.DeliverWorkflowProviderEventRequestSchema, {
    provider: value.provider ?? "",
    ...(value.event !== undefined
      ? { event: toWireWorkflowEvent(value.event) }
      : {}),
    ...(value.context !== undefined
      ? { context: toWireRequestContext(value.context) }
      : {}),
  });
}

export function fromWireDeliverWorkflowProviderEventRequest(
  value: wire.DeliverWorkflowProviderEventRequest,
): DeliverWorkflowProviderEventRequest {
  return {
    provider: value.provider,
    ...(value.event !== undefined
      ? { event: fromWireWorkflowEvent(value.event) }
      : {}),
    ...(value.context !== undefined
      ? { context: fromWireRequestContext(value.context) }
      : {}),
  };
}

export function toWireGetWorkflowProviderDefinitionRequest(
  value: Init<GetWorkflowProviderDefinitionRequest>,
): wire.GetWorkflowProviderDefinitionRequest {
  return create(wire.GetWorkflowProviderDefinitionRequestSchema, {
    definitionId: value.definitionId ?? "",
    ...(value.context !== undefined
      ? { context: toWireRequestContext(value.context) }
      : {}),
    provider: value.provider ?? "",
  });
}

export function fromWireGetWorkflowProviderDefinitionRequest(
  value: wire.GetWorkflowProviderDefinitionRequest,
): GetWorkflowProviderDefinitionRequest {
  return {
    definitionId: value.definitionId,
    ...(value.context !== undefined
      ? { context: fromWireRequestContext(value.context) }
      : {}),
    provider: value.provider,
  };
}

export function toWireGetWorkflowProviderRunEventsRequest(
  value: Init<GetWorkflowProviderRunEventsRequest>,
): wire.GetWorkflowProviderRunEventsRequest {
  return create(wire.GetWorkflowProviderRunEventsRequestSchema, {
    runId: value.runId ?? "",
    ...(value.context !== undefined
      ? { context: toWireRequestContext(value.context) }
      : {}),
    provider: value.provider ?? "",
  });
}

export function fromWireGetWorkflowProviderRunEventsRequest(
  value: wire.GetWorkflowProviderRunEventsRequest,
): GetWorkflowProviderRunEventsRequest {
  return {
    runId: value.runId,
    ...(value.context !== undefined
      ? { context: fromWireRequestContext(value.context) }
      : {}),
    provider: value.provider,
  };
}

export function toWireGetWorkflowProviderRunEventsResponse(
  value: Init<GetWorkflowProviderRunEventsResponse>,
): wire.GetWorkflowProviderRunEventsResponse {
  return create(wire.GetWorkflowProviderRunEventsResponseSchema, {
    events: (value.events ?? []).map(toWireWorkflowRunEvent),
  });
}

export function fromWireGetWorkflowProviderRunEventsResponse(
  value: wire.GetWorkflowProviderRunEventsResponse,
): GetWorkflowProviderRunEventsResponse {
  return {
    events: value.events.map(fromWireWorkflowRunEvent),
  };
}

export function toWireGetWorkflowProviderRunOutputRequest(
  value: Init<GetWorkflowProviderRunOutputRequest>,
): wire.GetWorkflowProviderRunOutputRequest {
  return create(wire.GetWorkflowProviderRunOutputRequestSchema, {
    runId: value.runId ?? "",
    ...(value.context !== undefined
      ? { context: toWireRequestContext(value.context) }
      : {}),
    provider: value.provider ?? "",
  });
}

export function fromWireGetWorkflowProviderRunOutputRequest(
  value: wire.GetWorkflowProviderRunOutputRequest,
): GetWorkflowProviderRunOutputRequest {
  return {
    runId: value.runId,
    ...(value.context !== undefined
      ? { context: fromWireRequestContext(value.context) }
      : {}),
    provider: value.provider,
  };
}

export function toWireGetWorkflowProviderRunOutputResponse(
  value: Init<GetWorkflowProviderRunOutputResponse>,
): wire.GetWorkflowProviderRunOutputResponse {
  return create(wire.GetWorkflowProviderRunOutputResponseSchema, {
    ...(value.output !== undefined
      ? { output: toWireValue(value.output) }
      : {}),
  });
}

export function fromWireGetWorkflowProviderRunOutputResponse(
  value: wire.GetWorkflowProviderRunOutputResponse,
): GetWorkflowProviderRunOutputResponse {
  return {
    ...(value.output !== undefined
      ? { output: fromWireValue(value.output) }
      : {}),
  };
}

export function toWireGetWorkflowProviderRunRequest(
  value: Init<GetWorkflowProviderRunRequest>,
): wire.GetWorkflowProviderRunRequest {
  return create(wire.GetWorkflowProviderRunRequestSchema, {
    runId: value.runId ?? "",
    ...(value.context !== undefined
      ? { context: toWireRequestContext(value.context) }
      : {}),
    provider: value.provider ?? "",
  });
}

export function fromWireGetWorkflowProviderRunRequest(
  value: wire.GetWorkflowProviderRunRequest,
): GetWorkflowProviderRunRequest {
  return {
    runId: value.runId,
    ...(value.context !== undefined
      ? { context: fromWireRequestContext(value.context) }
      : {}),
    provider: value.provider,
  };
}

export function toWireListWorkflowProviderDefinitionsRequest(
  value: Init<ListWorkflowProviderDefinitionsRequest>,
): wire.ListWorkflowProviderDefinitionsRequest {
  return create(wire.ListWorkflowProviderDefinitionsRequestSchema, {
    ...(value.context !== undefined
      ? { context: toWireRequestContext(value.context) }
      : {}),
    provider: value.provider ?? "",
  });
}

export function fromWireListWorkflowProviderDefinitionsRequest(
  value: wire.ListWorkflowProviderDefinitionsRequest,
): ListWorkflowProviderDefinitionsRequest {
  return {
    ...(value.context !== undefined
      ? { context: fromWireRequestContext(value.context) }
      : {}),
    provider: value.provider,
  };
}

export function toWireListWorkflowProviderDefinitionsResponse(
  value: Init<ListWorkflowProviderDefinitionsResponse>,
): wire.ListWorkflowProviderDefinitionsResponse {
  return create(wire.ListWorkflowProviderDefinitionsResponseSchema, {
    definitions: (value.definitions ?? []).map(toWireWorkflowDefinition),
  });
}

export function fromWireListWorkflowProviderDefinitionsResponse(
  value: wire.ListWorkflowProviderDefinitionsResponse,
): ListWorkflowProviderDefinitionsResponse {
  return {
    definitions: value.definitions.map(fromWireWorkflowDefinition),
  };
}

export function toWireListWorkflowProviderRunsRequest(
  value: Init<ListWorkflowProviderRunsRequest>,
): wire.ListWorkflowProviderRunsRequest {
  return create(wire.ListWorkflowProviderRunsRequestSchema, {
    pageSize: value.pageSize ?? 0,
    pageToken: value.pageToken ?? "",
    status: (value.status ?? 0) as wire.WorkflowRunStatus,
    targetApp: value.targetApp ?? "",
    ...(value.context !== undefined
      ? { context: toWireRequestContext(value.context) }
      : {}),
    provider: value.provider ?? "",
  });
}

export function fromWireListWorkflowProviderRunsRequest(
  value: wire.ListWorkflowProviderRunsRequest,
): ListWorkflowProviderRunsRequest {
  return {
    pageSize: value.pageSize,
    pageToken: value.pageToken,
    status: value.status,
    targetApp: value.targetApp,
    ...(value.context !== undefined
      ? { context: fromWireRequestContext(value.context) }
      : {}),
    provider: value.provider,
  };
}

export function toWireListWorkflowProviderRunsResponse(
  value: Init<ListWorkflowProviderRunsResponse>,
): wire.ListWorkflowProviderRunsResponse {
  return create(wire.ListWorkflowProviderRunsResponseSchema, {
    runs: (value.runs ?? []).map(toWireWorkflowRun),
    nextPageToken: value.nextPageToken ?? "",
  });
}

export function fromWireListWorkflowProviderRunsResponse(
  value: wire.ListWorkflowProviderRunsResponse,
): ListWorkflowProviderRunsResponse {
  return {
    runs: value.runs.map(fromWireWorkflowRun),
    nextPageToken: value.nextPageToken,
  };
}

export function toWireSetWorkflowProviderActivationPausedRequest(
  value: Init<SetWorkflowProviderActivationPausedRequest>,
): wire.SetWorkflowProviderActivationPausedRequest {
  return create(wire.SetWorkflowProviderActivationPausedRequestSchema, {
    definitionId: value.definitionId ?? "",
    activationId: value.activationId ?? "",
    paused: value.paused ?? false,
    ...(value.context !== undefined
      ? { context: toWireRequestContext(value.context) }
      : {}),
    provider: value.provider ?? "",
  });
}

export function fromWireSetWorkflowProviderActivationPausedRequest(
  value: wire.SetWorkflowProviderActivationPausedRequest,
): SetWorkflowProviderActivationPausedRequest {
  return {
    definitionId: value.definitionId,
    activationId: value.activationId,
    paused: value.paused,
    ...(value.context !== undefined
      ? { context: fromWireRequestContext(value.context) }
      : {}),
    provider: value.provider,
  };
}

export function toWireSetWorkflowProviderDefinitionPausedRequest(
  value: Init<SetWorkflowProviderDefinitionPausedRequest>,
): wire.SetWorkflowProviderDefinitionPausedRequest {
  return create(wire.SetWorkflowProviderDefinitionPausedRequestSchema, {
    definitionId: value.definitionId ?? "",
    paused: value.paused ?? false,
    ...(value.context !== undefined
      ? { context: toWireRequestContext(value.context) }
      : {}),
    provider: value.provider ?? "",
  });
}

export function fromWireSetWorkflowProviderDefinitionPausedRequest(
  value: wire.SetWorkflowProviderDefinitionPausedRequest,
): SetWorkflowProviderDefinitionPausedRequest {
  return {
    definitionId: value.definitionId,
    paused: value.paused,
    ...(value.context !== undefined
      ? { context: fromWireRequestContext(value.context) }
      : {}),
    provider: value.provider,
  };
}

export function toWireSignalOrStartWorkflowProviderRunRequest(
  value: Init<SignalOrStartWorkflowProviderRunRequest>,
): wire.SignalOrStartWorkflowProviderRunRequest {
  return create(wire.SignalOrStartWorkflowProviderRunRequestSchema, {
    workflowKey: value.workflowKey ?? "",
    idempotencyKey: value.idempotencyKey ?? "",
    ...(value.signal !== undefined
      ? { signal: toWireWorkflowSignal(value.signal) }
      : {}),
    provider: value.provider ?? "",
    definitionId: value.definitionId ?? "",
    ...(value.input !== undefined
      ? { input: sanitizeJsonObject(value.input) }
      : {}),
    expectedDefinitionGeneration: value.expectedDefinitionGeneration ?? 0n,
    ...(value.context !== undefined
      ? { context: toWireRequestContext(value.context) }
      : {}),
  });
}

export function fromWireSignalOrStartWorkflowProviderRunRequest(
  value: wire.SignalOrStartWorkflowProviderRunRequest,
): SignalOrStartWorkflowProviderRunRequest {
  return {
    workflowKey: value.workflowKey,
    idempotencyKey: value.idempotencyKey,
    ...(value.signal !== undefined
      ? { signal: fromWireWorkflowSignal(value.signal) }
      : {}),
    provider: value.provider,
    definitionId: value.definitionId,
    ...(value.input !== undefined ? { input: value.input } : {}),
    expectedDefinitionGeneration: value.expectedDefinitionGeneration,
    ...(value.context !== undefined
      ? { context: fromWireRequestContext(value.context) }
      : {}),
  };
}

export function toWireSignalWorkflowProviderRunRequest(
  value: Init<SignalWorkflowProviderRunRequest>,
): wire.SignalWorkflowProviderRunRequest {
  return create(wire.SignalWorkflowProviderRunRequestSchema, {
    runId: value.runId ?? "",
    ...(value.signal !== undefined
      ? { signal: toWireWorkflowSignal(value.signal) }
      : {}),
    ...(value.context !== undefined
      ? { context: toWireRequestContext(value.context) }
      : {}),
    provider: value.provider ?? "",
  });
}

export function fromWireSignalWorkflowProviderRunRequest(
  value: wire.SignalWorkflowProviderRunRequest,
): SignalWorkflowProviderRunRequest {
  return {
    runId: value.runId,
    ...(value.signal !== undefined
      ? { signal: fromWireWorkflowSignal(value.signal) }
      : {}),
    ...(value.context !== undefined
      ? { context: fromWireRequestContext(value.context) }
      : {}),
    provider: value.provider,
  };
}

export function toWireSignalWorkflowRunResponse(
  value: Init<SignalWorkflowRunResponse>,
): wire.SignalWorkflowRunResponse {
  return create(wire.SignalWorkflowRunResponseSchema, {
    ...(value.run !== undefined ? { run: toWireWorkflowRun(value.run) } : {}),
    ...(value.signal !== undefined
      ? { signal: toWireWorkflowSignal(value.signal) }
      : {}),
    startedRun: value.startedRun ?? false,
    workflowKey: value.workflowKey ?? "",
  });
}

export function fromWireSignalWorkflowRunResponse(
  value: wire.SignalWorkflowRunResponse,
): SignalWorkflowRunResponse {
  return {
    ...(value.run !== undefined ? { run: fromWireWorkflowRun(value.run) } : {}),
    ...(value.signal !== undefined
      ? { signal: fromWireWorkflowSignal(value.signal) }
      : {}),
    startedRun: value.startedRun,
    workflowKey: value.workflowKey,
  };
}

export function toWireStartWorkflowProviderRunRequest(
  value: Init<StartWorkflowProviderRunRequest>,
): wire.StartWorkflowProviderRunRequest {
  return create(wire.StartWorkflowProviderRunRequestSchema, {
    idempotencyKey: value.idempotencyKey ?? "",
    workflowKey: value.workflowKey ?? "",
    provider: value.provider ?? "",
    definitionId: value.definitionId ?? "",
    ...(value.input !== undefined
      ? { input: sanitizeJsonObject(value.input) }
      : {}),
    expectedDefinitionGeneration: value.expectedDefinitionGeneration ?? 0n,
    ...(value.context !== undefined
      ? { context: toWireRequestContext(value.context) }
      : {}),
  });
}

export function fromWireStartWorkflowProviderRunRequest(
  value: wire.StartWorkflowProviderRunRequest,
): StartWorkflowProviderRunRequest {
  return {
    idempotencyKey: value.idempotencyKey,
    workflowKey: value.workflowKey,
    provider: value.provider,
    definitionId: value.definitionId,
    ...(value.input !== undefined ? { input: value.input } : {}),
    expectedDefinitionGeneration: value.expectedDefinitionGeneration,
    ...(value.context !== undefined
      ? { context: fromWireRequestContext(value.context) }
      : {}),
  };
}

export function toWireWorkflowActivation(
  value: Init<WorkflowActivation>,
): wire.WorkflowActivation {
  return create(wire.WorkflowActivationSchema, {
    id: value.id ?? "",
    ...(value.input !== undefined
      ? { input: toWireWorkflowValue(value.input) }
      : {}),
    paused: value.paused ?? false,
    trigger: toWireWorkflowActivationTrigger(
      value.trigger ?? { case: undefined },
    ),
  });
}

export function fromWireWorkflowActivation(
  value: wire.WorkflowActivation,
): WorkflowActivation {
  return {
    id: value.id,
    ...(value.input !== undefined
      ? { input: fromWireWorkflowValue(value.input) }
      : {}),
    paused: value.paused,
    trigger: fromWireWorkflowActivationTrigger(value.trigger),
  };
}

export function toWireWorkflowActivationTrigger(
  value: Init<WorkflowActivationTrigger>,
): wire.WorkflowActivation["trigger"] {
  switch (value.case) {
    case "schedule":
      return {
        case: "schedule",
        value: toWireWorkflowScheduleActivation(value.value),
      };
    case "event":
      return {
        case: "event",
        value: toWireWorkflowEventActivation(value.value),
      };
    default:
      return { case: undefined };
  }
}

export function fromWireWorkflowActivationTrigger(
  value: wire.WorkflowActivation["trigger"],
): WorkflowActivationTrigger {
  switch (value.case) {
    case "schedule":
      return {
        case: "schedule",
        value: fromWireWorkflowScheduleActivation(value.value),
      };
    case "event":
      return {
        case: "event",
        value: fromWireWorkflowEventActivation(value.value),
      };
    default:
      return { case: undefined };
  }
}

export function toWireWorkflowAgentMessage(
  value: Init<WorkflowAgentMessage>,
): wire.WorkflowAgentMessage {
  return create(wire.WorkflowAgentMessageSchema, {
    role: value.role ?? "",
    ...(value.text !== undefined
      ? { text: toWireWorkflowText(value.text) }
      : {}),
    ...(value.metadata !== undefined
      ? { metadata: sanitizeJsonObject(value.metadata) }
      : {}),
  });
}

export function fromWireWorkflowAgentMessage(
  value: wire.WorkflowAgentMessage,
): WorkflowAgentMessage {
  return {
    role: value.role,
    ...(value.text !== undefined
      ? { text: fromWireWorkflowText(value.text) }
      : {}),
    ...(value.metadata !== undefined ? { metadata: value.metadata } : {}),
  };
}

export function toWireWorkflowArray(
  value: Init<WorkflowArray>,
): wire.WorkflowArray {
  return create(wire.WorkflowArraySchema, {
    values: (value.values ?? []).map(toWireWorkflowValue),
  });
}

export function fromWireWorkflowArray(
  value: wire.WorkflowArray,
): WorkflowArray {
  return {
    values: value.values.map(fromWireWorkflowValue),
  };
}

export function toWireWorkflowDefinition(
  value: Init<WorkflowDefinition>,
): wire.WorkflowDefinition {
  return create(wire.WorkflowDefinitionSchema, {
    id: value.id ?? "",
    generation: value.generation ?? 0n,
    ...(value.target !== undefined
      ? { target: toWireBoundWorkflowTarget(value.target) }
      : {}),
    activations: (value.activations ?? []).map(toWireWorkflowActivation),
    paused: value.paused ?? false,
    ...(value.createdAt !== undefined
      ? { createdAt: toWireTimestamp(value.createdAt) }
      : {}),
    ...(value.updatedAt !== undefined
      ? { updatedAt: toWireTimestamp(value.updatedAt) }
      : {}),
    provider: value.provider ?? "",
    runAs: value.runAs ?? "",
  });
}

export function fromWireWorkflowDefinition(
  value: wire.WorkflowDefinition,
): WorkflowDefinition {
  return {
    id: value.id,
    generation: value.generation,
    ...(value.target !== undefined
      ? { target: fromWireBoundWorkflowTarget(value.target) }
      : {}),
    activations: value.activations.map(fromWireWorkflowActivation),
    paused: value.paused,
    ...(value.createdAt !== undefined
      ? { createdAt: fromWireTimestamp(value.createdAt) }
      : {}),
    ...(value.updatedAt !== undefined
      ? { updatedAt: fromWireTimestamp(value.updatedAt) }
      : {}),
    provider: value.provider,
    runAs: value.runAs,
  };
}

export function toWireWorkflowDefinitionSpec(
  value: Init<WorkflowDefinitionSpec>,
): wire.WorkflowDefinitionSpec {
  return create(wire.WorkflowDefinitionSpecSchema, {
    id: value.id ?? "",
    ...(value.target !== undefined
      ? { target: toWireBoundWorkflowTarget(value.target) }
      : {}),
    activations: (value.activations ?? []).map(toWireWorkflowActivation),
    paused: value.paused ?? false,
    runAs: value.runAs ?? "",
  });
}

export function fromWireWorkflowDefinitionSpec(
  value: wire.WorkflowDefinitionSpec,
): WorkflowDefinitionSpec {
  return {
    id: value.id,
    ...(value.target !== undefined
      ? { target: fromWireBoundWorkflowTarget(value.target) }
      : {}),
    activations: value.activations.map(fromWireWorkflowActivation),
    paused: value.paused,
    runAs: value.runAs,
  };
}

export function toWireWorkflowEvent(
  value: Init<WorkflowEvent>,
): wire.WorkflowEvent {
  return create(wire.WorkflowEventSchema, {
    id: value.id ?? "",
    source: value.source ?? "",
    specVersion: value.specVersion ?? "",
    type: value.type ?? "",
    subject: value.subject ?? "",
    ...(value.time !== undefined ? { time: toWireTimestamp(value.time) } : {}),
    datacontenttype: value.datacontenttype ?? "",
    ...(value.data !== undefined
      ? { data: sanitizeJsonObject(value.data) }
      : {}),
    extensions: Object.fromEntries(
      Object.entries(value.extensions ?? {}).map(([key, item]) => [
        key,
        toWireValue(item),
      ]),
    ),
  });
}

export function fromWireWorkflowEvent(
  value: wire.WorkflowEvent,
): WorkflowEvent {
  return {
    id: value.id,
    source: value.source,
    specVersion: value.specVersion,
    type: value.type,
    subject: value.subject,
    ...(value.time !== undefined
      ? { time: fromWireTimestamp(value.time) }
      : {}),
    datacontenttype: value.datacontenttype,
    ...(value.data !== undefined ? { data: value.data } : {}),
    extensions: Object.fromEntries(
      Object.entries(value.extensions).map(([key, item]) => [
        key,
        fromWireValue(item),
      ]),
    ),
  };
}

export function toWireWorkflowEventActivation(
  value: Init<WorkflowEventActivation>,
): wire.WorkflowEventActivation {
  return create(wire.WorkflowEventActivationSchema, {
    ...(value.match !== undefined
      ? { match: toWireWorkflowEventMatch(value.match) }
      : {}),
  });
}

export function fromWireWorkflowEventActivation(
  value: wire.WorkflowEventActivation,
): WorkflowEventActivation {
  return {
    ...(value.match !== undefined
      ? { match: fromWireWorkflowEventMatch(value.match) }
      : {}),
  };
}

export function toWireWorkflowEventMatch(
  value: Init<WorkflowEventMatch>,
): wire.WorkflowEventMatch {
  return create(wire.WorkflowEventMatchSchema, {
    type: value.type ?? "",
    source: value.source ?? "",
    subject: value.subject ?? "",
  });
}

export function fromWireWorkflowEventMatch(
  value: wire.WorkflowEventMatch,
): WorkflowEventMatch {
  return {
    type: value.type,
    source: value.source,
    subject: value.subject,
  };
}

export function toWireWorkflowEventTriggerInvocation(
  value: Init<WorkflowEventTriggerInvocation>,
): wire.WorkflowEventTriggerInvocation {
  return create(wire.WorkflowEventTriggerInvocationSchema, {
    activationId: value.activationId ?? "",
    ...(value.event !== undefined
      ? { event: toWireWorkflowEvent(value.event) }
      : {}),
  });
}

export function fromWireWorkflowEventTriggerInvocation(
  value: wire.WorkflowEventTriggerInvocation,
): WorkflowEventTriggerInvocation {
  return {
    activationId: value.activationId,
    ...(value.event !== undefined
      ? { event: fromWireWorkflowEvent(value.event) }
      : {}),
  };
}

export function toWireWorkflowManualTrigger(
  value: Init<WorkflowManualTrigger>,
): wire.WorkflowManualTrigger {
  return create(wire.WorkflowManualTriggerSchema, {});
}

export function fromWireWorkflowManualTrigger(
  value: wire.WorkflowManualTrigger,
): WorkflowManualTrigger {
  return {};
}

export function toWireWorkflowObject(
  value: Init<WorkflowObject>,
): wire.WorkflowObject {
  return create(wire.WorkflowObjectSchema, {
    fields: Object.fromEntries(
      Object.entries(value.fields ?? {}).map(([key, item]) => [
        key,
        toWireWorkflowValue(item),
      ]),
    ),
  });
}

export function fromWireWorkflowObject(
  value: wire.WorkflowObject,
): WorkflowObject {
  return {
    fields: Object.fromEntries(
      Object.entries(value.fields).map(([key, item]) => [
        key,
        fromWireWorkflowValue(item),
      ]),
    ),
  };
}

export function toWireWorkflowPathSource(
  value: Init<WorkflowPathSource>,
): wire.WorkflowPathSource {
  return create(wire.WorkflowPathSourceSchema, {
    path: value.path ?? "",
  });
}

export function fromWireWorkflowPathSource(
  value: wire.WorkflowPathSource,
): WorkflowPathSource {
  return {
    path: value.path,
  };
}

export function toWireWorkflowRun(value: Init<WorkflowRun>): wire.WorkflowRun {
  return create(wire.WorkflowRunSchema, {
    id: value.id ?? "",
    status: (value.status ?? 0) as wire.WorkflowRunStatus,
    ...(value.target !== undefined
      ? { target: toWireBoundWorkflowTarget(value.target) }
      : {}),
    ...(value.trigger !== undefined
      ? { trigger: toWireWorkflowRunTrigger(value.trigger) }
      : {}),
    ...(value.createdAt !== undefined
      ? { createdAt: toWireTimestamp(value.createdAt) }
      : {}),
    ...(value.startedAt !== undefined
      ? { startedAt: toWireTimestamp(value.startedAt) }
      : {}),
    ...(value.completedAt !== undefined
      ? { completedAt: toWireTimestamp(value.completedAt) }
      : {}),
    statusMessage: value.statusMessage ?? "",
    ...(value.output !== undefined
      ? { output: toWireValue(value.output) }
      : {}),
    workflowKey: value.workflowKey ?? "",
    provider: value.provider ?? "",
    definitionId: value.definitionId ?? "",
    runAs: value.runAs ?? "",
    ...(value.input !== undefined
      ? { input: sanitizeJsonObject(value.input) }
      : {}),
    definitionGeneration: value.definitionGeneration ?? 0n,
    currentStepId: value.currentStepId ?? "",
    steps: (value.steps ?? []).map(toWireWorkflowStepExecution),
  });
}

export function fromWireWorkflowRun(value: wire.WorkflowRun): WorkflowRun {
  return {
    id: value.id,
    status: value.status,
    ...(value.target !== undefined
      ? { target: fromWireBoundWorkflowTarget(value.target) }
      : {}),
    ...(value.trigger !== undefined
      ? { trigger: fromWireWorkflowRunTrigger(value.trigger) }
      : {}),
    ...(value.createdAt !== undefined
      ? { createdAt: fromWireTimestamp(value.createdAt) }
      : {}),
    ...(value.startedAt !== undefined
      ? { startedAt: fromWireTimestamp(value.startedAt) }
      : {}),
    ...(value.completedAt !== undefined
      ? { completedAt: fromWireTimestamp(value.completedAt) }
      : {}),
    statusMessage: value.statusMessage,
    ...(value.output !== undefined
      ? { output: fromWireValue(value.output) }
      : {}),
    workflowKey: value.workflowKey,
    provider: value.provider,
    definitionId: value.definitionId,
    runAs: value.runAs,
    ...(value.input !== undefined ? { input: value.input } : {}),
    definitionGeneration: value.definitionGeneration,
    currentStepId: value.currentStepId,
    steps: value.steps.map(fromWireWorkflowStepExecution),
  };
}

export function toWireWorkflowRunEvent(
  value: Init<WorkflowRunEvent>,
): wire.WorkflowRunEvent {
  return create(wire.WorkflowRunEventSchema, {
    id: value.id ?? "",
    runId: value.runId ?? "",
    stepId: value.stepId ?? "",
    type: value.type ?? "",
    ...(value.data !== undefined
      ? { data: sanitizeJsonObject(value.data) }
      : {}),
    ...(value.createdAt !== undefined
      ? { createdAt: toWireTimestamp(value.createdAt) }
      : {}),
  });
}

export function fromWireWorkflowRunEvent(
  value: wire.WorkflowRunEvent,
): WorkflowRunEvent {
  return {
    id: value.id,
    runId: value.runId,
    stepId: value.stepId,
    type: value.type,
    ...(value.data !== undefined ? { data: value.data } : {}),
    ...(value.createdAt !== undefined
      ? { createdAt: fromWireTimestamp(value.createdAt) }
      : {}),
  };
}

export function toWireWorkflowRunTrigger(
  value: Init<WorkflowRunTrigger>,
): wire.WorkflowRunTrigger {
  return create(wire.WorkflowRunTriggerSchema, {
    kind: toWireWorkflowRunTriggerKind(value.kind ?? { case: undefined }),
  });
}

export function fromWireWorkflowRunTrigger(
  value: wire.WorkflowRunTrigger,
): WorkflowRunTrigger {
  return {
    kind: fromWireWorkflowRunTriggerKind(value.kind),
  };
}

export function toWireWorkflowRunTriggerKind(
  value: Init<WorkflowRunTriggerKind>,
): wire.WorkflowRunTrigger["kind"] {
  switch (value.case) {
    case "manual":
      return {
        case: "manual",
        value: toWireWorkflowManualTrigger(value.value),
      };
    case "schedule":
      return {
        case: "schedule",
        value: toWireWorkflowScheduleTrigger(value.value),
      };
    case "event":
      return {
        case: "event",
        value: toWireWorkflowEventTriggerInvocation(value.value),
      };
    default:
      return { case: undefined };
  }
}

export function fromWireWorkflowRunTriggerKind(
  value: wire.WorkflowRunTrigger["kind"],
): WorkflowRunTriggerKind {
  switch (value.case) {
    case "manual":
      return {
        case: "manual",
        value: fromWireWorkflowManualTrigger(value.value),
      };
    case "schedule":
      return {
        case: "schedule",
        value: fromWireWorkflowScheduleTrigger(value.value),
      };
    case "event":
      return {
        case: "event",
        value: fromWireWorkflowEventTriggerInvocation(value.value),
      };
    default:
      return { case: undefined };
  }
}

export function toWireWorkflowScheduleActivation(
  value: Init<WorkflowScheduleActivation>,
): wire.WorkflowScheduleActivation {
  return create(wire.WorkflowScheduleActivationSchema, {
    cron: value.cron ?? "",
    timezone: value.timezone ?? "",
  });
}

export function fromWireWorkflowScheduleActivation(
  value: wire.WorkflowScheduleActivation,
): WorkflowScheduleActivation {
  return {
    cron: value.cron,
    timezone: value.timezone,
  };
}

export function toWireWorkflowScheduleTrigger(
  value: Init<WorkflowScheduleTrigger>,
): wire.WorkflowScheduleTrigger {
  return create(wire.WorkflowScheduleTriggerSchema, {
    activationId: value.activationId ?? "",
    ...(value.scheduledFor !== undefined
      ? { scheduledFor: toWireTimestamp(value.scheduledFor) }
      : {}),
  });
}

export function fromWireWorkflowScheduleTrigger(
  value: wire.WorkflowScheduleTrigger,
): WorkflowScheduleTrigger {
  return {
    activationId: value.activationId,
    ...(value.scheduledFor !== undefined
      ? { scheduledFor: fromWireTimestamp(value.scheduledFor) }
      : {}),
  };
}

export function toWireWorkflowSignal(
  value: Init<WorkflowSignal>,
): wire.WorkflowSignal {
  return create(wire.WorkflowSignalSchema, {
    id: value.id ?? "",
    name: value.name ?? "",
    ...(value.payload !== undefined
      ? { payload: sanitizeJsonObject(value.payload) }
      : {}),
    ...(value.metadata !== undefined
      ? { metadata: sanitizeJsonObject(value.metadata) }
      : {}),
    ...(value.createdAt !== undefined
      ? { createdAt: toWireTimestamp(value.createdAt) }
      : {}),
    idempotencyKey: value.idempotencyKey ?? "",
    sequence: value.sequence ?? 0n,
  });
}

export function fromWireWorkflowSignal(
  value: wire.WorkflowSignal,
): WorkflowSignal {
  return {
    id: value.id,
    name: value.name,
    ...(value.payload !== undefined ? { payload: value.payload } : {}),
    ...(value.metadata !== undefined ? { metadata: value.metadata } : {}),
    ...(value.createdAt !== undefined
      ? { createdAt: fromWireTimestamp(value.createdAt) }
      : {}),
    idempotencyKey: value.idempotencyKey,
    sequence: value.sequence,
  };
}

export function toWireWorkflowStep(
  value: Init<WorkflowStep>,
): wire.WorkflowStep {
  return create(wire.WorkflowStepSchema, {
    id: value.id ?? "",
    inputs: Object.fromEntries(
      Object.entries(value.inputs ?? {}).map(([key, item]) => [
        key,
        toWireWorkflowValue(item),
      ]),
    ),
    ...(value.when !== undefined
      ? { when: toWireWorkflowStepWhen(value.when) }
      : {}),
    timeoutSeconds: value.timeoutSeconds ?? 0,
    ...(value.metadata !== undefined
      ? { metadata: sanitizeJsonObject(value.metadata) }
      : {}),
    action: toWireWorkflowStepAction(value.action ?? { case: undefined }),
  });
}

export function fromWireWorkflowStep(value: wire.WorkflowStep): WorkflowStep {
  return {
    id: value.id,
    inputs: Object.fromEntries(
      Object.entries(value.inputs).map(([key, item]) => [
        key,
        fromWireWorkflowValue(item),
      ]),
    ),
    ...(value.when !== undefined
      ? { when: fromWireWorkflowStepWhen(value.when) }
      : {}),
    timeoutSeconds: value.timeoutSeconds,
    ...(value.metadata !== undefined ? { metadata: value.metadata } : {}),
    action: fromWireWorkflowStepAction(value.action),
  };
}

export function toWireWorkflowStepAction(
  value: Init<WorkflowStepAction>,
): wire.WorkflowStep["action"] {
  switch (value.case) {
    case "app":
      return { case: "app", value: toWireWorkflowStepAppCall(value.value) };
    case "agent":
      return { case: "agent", value: toWireWorkflowStepAgentTurn(value.value) };
    default:
      return { case: undefined };
  }
}

export function fromWireWorkflowStepAction(
  value: wire.WorkflowStep["action"],
): WorkflowStepAction {
  switch (value.case) {
    case "app":
      return { case: "app", value: fromWireWorkflowStepAppCall(value.value) };
    case "agent":
      return {
        case: "agent",
        value: fromWireWorkflowStepAgentTurn(value.value),
      };
    default:
      return { case: undefined };
  }
}

export function toWireWorkflowStepAgentTurn(
  value: Init<WorkflowStepAgentTurn>,
): wire.WorkflowStepAgentTurn {
  return create(wire.WorkflowStepAgentTurnSchema, {
    provider: value.provider ?? "",
    model: value.model ?? "",
    sessionKey: value.sessionKey ?? "",
    ...(value.prompt !== undefined
      ? { prompt: toWireWorkflowText(value.prompt) }
      : {}),
    messages: (value.messages ?? []).map(toWireWorkflowAgentMessage),
    tools: (value.tools ?? []).map(toWireAgentToolRef),
    ...(value.output !== undefined
      ? { output: toWireAgentOutput(value.output) }
      : {}),
    ...(value.modelOptions !== undefined
      ? { modelOptions: sanitizeJsonObject(value.modelOptions) }
      : {}),
  });
}

export function fromWireWorkflowStepAgentTurn(
  value: wire.WorkflowStepAgentTurn,
): WorkflowStepAgentTurn {
  return {
    provider: value.provider,
    model: value.model,
    sessionKey: value.sessionKey,
    ...(value.prompt !== undefined
      ? { prompt: fromWireWorkflowText(value.prompt) }
      : {}),
    messages: value.messages.map(fromWireWorkflowAgentMessage),
    tools: value.tools.map(fromWireAgentToolRef),
    ...(value.output !== undefined
      ? { output: fromWireAgentOutput(value.output) }
      : {}),
    ...(value.modelOptions !== undefined
      ? { modelOptions: value.modelOptions }
      : {}),
  };
}

export function toWireWorkflowStepAppCall(
  value: Init<WorkflowStepAppCall>,
): wire.WorkflowStepAppCall {
  return create(wire.WorkflowStepAppCallSchema, {
    name: value.name ?? "",
    operation: value.operation ?? "",
    ...(value.input !== undefined
      ? { input: toWireWorkflowValue(value.input) }
      : {}),
    connection: value.connection ?? "",
    instance: value.instance ?? "",
    credentialMode: value.credentialMode ?? "",
  });
}

export function fromWireWorkflowStepAppCall(
  value: wire.WorkflowStepAppCall,
): WorkflowStepAppCall {
  return {
    name: value.name,
    operation: value.operation,
    ...(value.input !== undefined
      ? { input: fromWireWorkflowValue(value.input) }
      : {}),
    connection: value.connection,
    instance: value.instance,
    credentialMode: value.credentialMode,
  };
}

export function toWireWorkflowStepAttempt(
  value: Init<WorkflowStepAttempt>,
): wire.WorkflowStepAttempt {
  return create(wire.WorkflowStepAttemptSchema, {
    id: value.id ?? "",
    status: (value.status ?? 0) as wire.WorkflowStepStatus,
    idempotencyKey: value.idempotencyKey ?? "",
    ...(value.input !== undefined ? { input: toWireValue(value.input) } : {}),
    ...(value.output !== undefined
      ? { output: toWireValue(value.output) }
      : {}),
    statusMessage: value.statusMessage ?? "",
    ...(value.startedAt !== undefined
      ? { startedAt: toWireTimestamp(value.startedAt) }
      : {}),
    ...(value.completedAt !== undefined
      ? { completedAt: toWireTimestamp(value.completedAt) }
      : {}),
  });
}

export function fromWireWorkflowStepAttempt(
  value: wire.WorkflowStepAttempt,
): WorkflowStepAttempt {
  return {
    id: value.id,
    status: value.status,
    idempotencyKey: value.idempotencyKey,
    ...(value.input !== undefined ? { input: fromWireValue(value.input) } : {}),
    ...(value.output !== undefined
      ? { output: fromWireValue(value.output) }
      : {}),
    statusMessage: value.statusMessage,
    ...(value.startedAt !== undefined
      ? { startedAt: fromWireTimestamp(value.startedAt) }
      : {}),
    ...(value.completedAt !== undefined
      ? { completedAt: fromWireTimestamp(value.completedAt) }
      : {}),
  };
}

export function toWireWorkflowStepExecution(
  value: Init<WorkflowStepExecution>,
): wire.WorkflowStepExecution {
  return create(wire.WorkflowStepExecutionSchema, {
    stepId: value.stepId ?? "",
    status: (value.status ?? 0) as wire.WorkflowStepStatus,
    attempts: (value.attempts ?? []).map(toWireWorkflowStepAttempt),
    ...(value.input !== undefined ? { input: toWireValue(value.input) } : {}),
    ...(value.output !== undefined
      ? { output: toWireValue(value.output) }
      : {}),
    statusMessage: value.statusMessage ?? "",
    skipReason: value.skipReason ?? "",
    ...(value.startedAt !== undefined
      ? { startedAt: toWireTimestamp(value.startedAt) }
      : {}),
    ...(value.completedAt !== undefined
      ? { completedAt: toWireTimestamp(value.completedAt) }
      : {}),
  });
}

export function fromWireWorkflowStepExecution(
  value: wire.WorkflowStepExecution,
): WorkflowStepExecution {
  return {
    stepId: value.stepId,
    status: value.status,
    attempts: value.attempts.map(fromWireWorkflowStepAttempt),
    ...(value.input !== undefined ? { input: fromWireValue(value.input) } : {}),
    ...(value.output !== undefined
      ? { output: fromWireValue(value.output) }
      : {}),
    statusMessage: value.statusMessage,
    skipReason: value.skipReason,
    ...(value.startedAt !== undefined
      ? { startedAt: fromWireTimestamp(value.startedAt) }
      : {}),
    ...(value.completedAt !== undefined
      ? { completedAt: fromWireTimestamp(value.completedAt) }
      : {}),
  };
}

export function toWireWorkflowStepInputSource(
  value: Init<WorkflowStepInputSource>,
): wire.WorkflowStepInputSource {
  return create(wire.WorkflowStepInputSourceSchema, {
    stepId: value.stepId ?? "",
    path: value.path ?? "",
  });
}

export function fromWireWorkflowStepInputSource(
  value: wire.WorkflowStepInputSource,
): WorkflowStepInputSource {
  return {
    stepId: value.stepId,
    path: value.path,
  };
}

export function toWireWorkflowStepOutputSource(
  value: Init<WorkflowStepOutputSource>,
): wire.WorkflowStepOutputSource {
  return create(wire.WorkflowStepOutputSourceSchema, {
    stepId: value.stepId ?? "",
    path: value.path ?? "",
  });
}

export function fromWireWorkflowStepOutputSource(
  value: wire.WorkflowStepOutputSource,
): WorkflowStepOutputSource {
  return {
    stepId: value.stepId,
    path: value.path,
  };
}

export function toWireWorkflowStepWhen(
  value: Init<WorkflowStepWhen>,
): wire.WorkflowStepWhen {
  return create(wire.WorkflowStepWhenSchema, {
    ...(value.value !== undefined
      ? { value: toWireWorkflowValue(value.value) }
      : {}),
    ...(value.equals !== undefined
      ? { equals: toWireValue(value.equals) }
      : {}),
  });
}

export function fromWireWorkflowStepWhen(
  value: wire.WorkflowStepWhen,
): WorkflowStepWhen {
  return {
    ...(value.value !== undefined
      ? { value: fromWireWorkflowValue(value.value) }
      : {}),
    ...(value.equals !== undefined
      ? { equals: fromWireValue(value.equals) }
      : {}),
  };
}

export function toWireWorkflowText(
  value: Init<WorkflowText>,
): wire.WorkflowText {
  return create(wire.WorkflowTextSchema, {
    template: value.template ?? "",
  });
}

export function fromWireWorkflowText(value: wire.WorkflowText): WorkflowText {
  return {
    template: value.template,
  };
}

export function toWireWorkflowValue(
  value: Init<WorkflowValue>,
): wire.WorkflowValue {
  return create(wire.WorkflowValueSchema, {
    kind: toWireWorkflowValueKind(value.kind ?? { case: undefined }),
  });
}

export function fromWireWorkflowValue(
  value: wire.WorkflowValue,
): WorkflowValue {
  return {
    kind: fromWireWorkflowValueKind(value.kind),
  };
}

export function toWireWorkflowValueKind(
  value: Init<WorkflowValueKind>,
): wire.WorkflowValue["kind"] {
  switch (value.case) {
    case "literal":
      return { case: "literal", value: toWireValue(value.value) };
    case "object":
      return { case: "object", value: toWireWorkflowObject(value.value) };
    case "array":
      return { case: "array", value: toWireWorkflowArray(value.value) };
    case "template":
      return { case: "template", value: toWireWorkflowText(value.value) };
    case "input":
      return { case: "input", value: toWireWorkflowPathSource(value.value) };
    case "signal":
      return { case: "signal", value: toWireWorkflowPathSource(value.value) };
    case "stepOutput":
      return {
        case: "stepOutput",
        value: toWireWorkflowStepOutputSource(value.value),
      };
    case "stepInput":
      return {
        case: "stepInput",
        value: toWireWorkflowStepInputSource(value.value),
      };
    default:
      return { case: undefined };
  }
}

export function fromWireWorkflowValueKind(
  value: wire.WorkflowValue["kind"],
): WorkflowValueKind {
  switch (value.case) {
    case "literal":
      return { case: "literal", value: fromWireValue(value.value) };
    case "object":
      return { case: "object", value: fromWireWorkflowObject(value.value) };
    case "array":
      return { case: "array", value: fromWireWorkflowArray(value.value) };
    case "template":
      return { case: "template", value: fromWireWorkflowText(value.value) };
    case "input":
      return { case: "input", value: fromWireWorkflowPathSource(value.value) };
    case "signal":
      return { case: "signal", value: fromWireWorkflowPathSource(value.value) };
    case "stepOutput":
      return {
        case: "stepOutput",
        value: fromWireWorkflowStepOutputSource(value.value),
      };
    case "stepInput":
      return {
        case: "stepInput",
        value: fromWireWorkflowStepInputSource(value.value),
      };
    default:
      return { case: undefined };
  }
}
