// Code generated by sdkgen. DO NOT EDIT.

#![allow(dead_code, unused_imports, unused_variables)]

//! Generated native types and clients for agent_provider_handler.proto.

use crate::agent::{
    AgentInteraction, AgentProviderCapabilities, AgentSession, AgentTurn,
    CancelAgentProviderTurnRequest, CreateAgentProviderSessionRequest,
    CreateAgentProviderTurnRequest, GetAgentProviderCapabilitiesRequest,
    GetAgentProviderInteractionRequest, GetAgentProviderSessionRequest,
    GetAgentProviderTurnRequest, ListAgentProviderInteractionsRequest,
    ListAgentProviderInteractionsResponse, ListAgentProviderSessionsRequest,
    ListAgentProviderSessionsResponse, ListAgentProviderTurnEventsRequest,
    ListAgentProviderTurnEventsResponse, ListAgentProviderTurnsRequest,
    ListAgentProviderTurnsResponse, ResolveAgentProviderInteractionRequest,
    UpdateAgentProviderSessionRequest,
};
use crate::codec::agent::{
    from_wire_cancel_agent_provider_turn_request, from_wire_create_agent_provider_session_request,
    from_wire_create_agent_provider_turn_request,
    from_wire_get_agent_provider_capabilities_request,
    from_wire_get_agent_provider_interaction_request, from_wire_get_agent_provider_session_request,
    from_wire_get_agent_provider_turn_request, from_wire_list_agent_provider_interactions_request,
    from_wire_list_agent_provider_sessions_request,
    from_wire_list_agent_provider_turn_events_request, from_wire_list_agent_provider_turns_request,
    from_wire_resolve_agent_provider_interaction_request,
    from_wire_update_agent_provider_session_request, to_wire_agent_interaction,
    to_wire_agent_provider_capabilities, to_wire_agent_session, to_wire_agent_turn,
    to_wire_list_agent_provider_interactions_response,
    to_wire_list_agent_provider_sessions_response,
    to_wire_list_agent_provider_turn_events_response, to_wire_list_agent_provider_turns_response,
};
use crate::generated::v1;
use crate::rpc_support::{GestaltError, gestalt_error_code};

/// Agent is the authoritative agent data boundary. Read RPCs for
/// sessions, turns, turn events, and interactions should use provider-owned
/// control-plane state and should not require a live execution sandbox,
/// pod-level transport, or cached tunnel.
///
/// Handler trait implemented by providers serving the `gestalt.provider.v1.Agent` service.
/// Methods receive the full native request; wire conversion and error
/// mapping live in the generated adapter (see [`AgentProviderServer`]).
/// Embed [`UnimplementedAgentProvider`] to default unimplemented methods.
#[tonic::async_trait]
pub trait AgentProvider: Send + Sync + 'static {
    /// Handles the `CreateSession` RPC.
    async fn create_session(
        &self,
        request: CreateAgentProviderSessionRequest,
    ) -> Result<AgentSession, GestaltError>;
    /// Handles the `GetSession` RPC.
    async fn get_session(
        &self,
        request: GetAgentProviderSessionRequest,
    ) -> Result<AgentSession, GestaltError>;
    /// Handles the `ListSessions` RPC.
    async fn list_sessions(
        &self,
        request: ListAgentProviderSessionsRequest,
    ) -> Result<ListAgentProviderSessionsResponse, GestaltError>;
    /// Handles the `UpdateSession` RPC.
    async fn update_session(
        &self,
        request: UpdateAgentProviderSessionRequest,
    ) -> Result<AgentSession, GestaltError>;
    /// Handles the `CreateTurn` RPC.
    async fn create_turn(
        &self,
        request: CreateAgentProviderTurnRequest,
    ) -> Result<AgentTurn, GestaltError>;
    /// Handles the `GetTurn` RPC.
    async fn get_turn(
        &self,
        request: GetAgentProviderTurnRequest,
    ) -> Result<AgentTurn, GestaltError>;
    /// Handles the `ListTurns` RPC.
    async fn list_turns(
        &self,
        request: ListAgentProviderTurnsRequest,
    ) -> Result<ListAgentProviderTurnsResponse, GestaltError>;
    /// Handles the `CancelTurn` RPC.
    async fn cancel_turn(
        &self,
        request: CancelAgentProviderTurnRequest,
    ) -> Result<AgentTurn, GestaltError>;
    /// Handles the `ListTurnEvents` RPC.
    async fn list_turn_events(
        &self,
        request: ListAgentProviderTurnEventsRequest,
    ) -> Result<ListAgentProviderTurnEventsResponse, GestaltError>;
    /// Handles the `GetInteraction` RPC.
    async fn get_interaction(
        &self,
        request: GetAgentProviderInteractionRequest,
    ) -> Result<AgentInteraction, GestaltError>;
    /// Handles the `ListInteractions` RPC.
    async fn list_interactions(
        &self,
        request: ListAgentProviderInteractionsRequest,
    ) -> Result<ListAgentProviderInteractionsResponse, GestaltError>;
    /// Handles the `ResolveInteraction` RPC.
    async fn resolve_interaction(
        &self,
        request: ResolveAgentProviderInteractionRequest,
    ) -> Result<AgentInteraction, GestaltError>;
    /// Handles the `GetCapabilities` RPC.
    async fn get_capabilities(
        &self,
        request: GetAgentProviderCapabilitiesRequest,
    ) -> Result<AgentProviderCapabilities, GestaltError>;
}

/// Fails every [`AgentProvider`] method with an Unimplemented error;
/// embed this to default the methods a provider does not implement.
#[derive(Debug, Default)]
pub struct UnimplementedAgentProvider;

#[tonic::async_trait]
impl AgentProvider for UnimplementedAgentProvider {
    async fn create_session(
        &self,
        _request: CreateAgentProviderSessionRequest,
    ) -> Result<AgentSession, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "agent create session is not implemented",
        ))
    }
    async fn get_session(
        &self,
        _request: GetAgentProviderSessionRequest,
    ) -> Result<AgentSession, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "agent get session is not implemented",
        ))
    }
    async fn list_sessions(
        &self,
        _request: ListAgentProviderSessionsRequest,
    ) -> Result<ListAgentProviderSessionsResponse, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "agent list sessions is not implemented",
        ))
    }
    async fn update_session(
        &self,
        _request: UpdateAgentProviderSessionRequest,
    ) -> Result<AgentSession, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "agent update session is not implemented",
        ))
    }
    async fn create_turn(
        &self,
        _request: CreateAgentProviderTurnRequest,
    ) -> Result<AgentTurn, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "agent create turn is not implemented",
        ))
    }
    async fn get_turn(
        &self,
        _request: GetAgentProviderTurnRequest,
    ) -> Result<AgentTurn, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "agent get turn is not implemented",
        ))
    }
    async fn list_turns(
        &self,
        _request: ListAgentProviderTurnsRequest,
    ) -> Result<ListAgentProviderTurnsResponse, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "agent list turns is not implemented",
        ))
    }
    async fn cancel_turn(
        &self,
        _request: CancelAgentProviderTurnRequest,
    ) -> Result<AgentTurn, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "agent cancel turn is not implemented",
        ))
    }
    async fn list_turn_events(
        &self,
        _request: ListAgentProviderTurnEventsRequest,
    ) -> Result<ListAgentProviderTurnEventsResponse, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "agent list turn events is not implemented",
        ))
    }
    async fn get_interaction(
        &self,
        _request: GetAgentProviderInteractionRequest,
    ) -> Result<AgentInteraction, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "agent get interaction is not implemented",
        ))
    }
    async fn list_interactions(
        &self,
        _request: ListAgentProviderInteractionsRequest,
    ) -> Result<ListAgentProviderInteractionsResponse, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "agent list interactions is not implemented",
        ))
    }
    async fn resolve_interaction(
        &self,
        _request: ResolveAgentProviderInteractionRequest,
    ) -> Result<AgentInteraction, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "agent resolve interaction is not implemented",
        ))
    }
    async fn get_capabilities(
        &self,
        _request: GetAgentProviderCapabilitiesRequest,
    ) -> Result<AgentProviderCapabilities, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "agent get capabilities is not implemented",
        ))
    }
}

/// Wire dispatch adapter: wraps an `Arc<P>` implementing [`AgentProvider`]
/// and implements the tonic wire trait `v1::agent_server::Agent`.
/// Requests convert from the wire, responses convert to the wire, and
/// handler errors map to gRPC statuses via `status_error`.
pub struct AgentProviderServer<P> {
    handler: std::sync::Arc<P>,
}

impl<P: AgentProvider> AgentProviderServer<P> {
    /// Creates a new dispatch adapter wrapping `handler`.
    pub fn new(handler: std::sync::Arc<P>) -> Self {
        Self { handler }
    }
}

#[tonic::async_trait]
impl<P: AgentProvider> v1::agent_server::Agent for AgentProviderServer<P> {
    async fn create_session(
        &self,
        request: tonic::Request<v1::CreateAgentProviderSessionRequest>,
    ) -> Result<tonic::Response<v1::AgentSession>, tonic::Status> {
        let response = self
            .handler
            .create_session(from_wire_create_agent_provider_session_request(
                request.into_inner(),
            ))
            .await
            .map_err(|e| crate::server_support::status_error("agent create session", e))?;
        Ok(tonic::Response::new(to_wire_agent_session(response)))
    }
    async fn get_session(
        &self,
        request: tonic::Request<v1::GetAgentProviderSessionRequest>,
    ) -> Result<tonic::Response<v1::AgentSession>, tonic::Status> {
        let response = self
            .handler
            .get_session(from_wire_get_agent_provider_session_request(
                request.into_inner(),
            ))
            .await
            .map_err(|e| crate::server_support::status_error("agent get session", e))?;
        Ok(tonic::Response::new(to_wire_agent_session(response)))
    }
    async fn list_sessions(
        &self,
        request: tonic::Request<v1::ListAgentProviderSessionsRequest>,
    ) -> Result<tonic::Response<v1::ListAgentProviderSessionsResponse>, tonic::Status> {
        let response = self
            .handler
            .list_sessions(from_wire_list_agent_provider_sessions_request(
                request.into_inner(),
            ))
            .await
            .map_err(|e| crate::server_support::status_error("agent list sessions", e))?;
        Ok(tonic::Response::new(
            to_wire_list_agent_provider_sessions_response(response),
        ))
    }
    async fn update_session(
        &self,
        request: tonic::Request<v1::UpdateAgentProviderSessionRequest>,
    ) -> Result<tonic::Response<v1::AgentSession>, tonic::Status> {
        let response = self
            .handler
            .update_session(from_wire_update_agent_provider_session_request(
                request.into_inner(),
            ))
            .await
            .map_err(|e| crate::server_support::status_error("agent update session", e))?;
        Ok(tonic::Response::new(to_wire_agent_session(response)))
    }
    async fn create_turn(
        &self,
        request: tonic::Request<v1::CreateAgentProviderTurnRequest>,
    ) -> Result<tonic::Response<v1::AgentTurn>, tonic::Status> {
        let response = self
            .handler
            .create_turn(from_wire_create_agent_provider_turn_request(
                request.into_inner(),
            ))
            .await
            .map_err(|e| crate::server_support::status_error("agent create turn", e))?;
        Ok(tonic::Response::new(to_wire_agent_turn(response)))
    }
    async fn get_turn(
        &self,
        request: tonic::Request<v1::GetAgentProviderTurnRequest>,
    ) -> Result<tonic::Response<v1::AgentTurn>, tonic::Status> {
        let response = self
            .handler
            .get_turn(from_wire_get_agent_provider_turn_request(
                request.into_inner(),
            ))
            .await
            .map_err(|e| crate::server_support::status_error("agent get turn", e))?;
        Ok(tonic::Response::new(to_wire_agent_turn(response)))
    }
    async fn list_turns(
        &self,
        request: tonic::Request<v1::ListAgentProviderTurnsRequest>,
    ) -> Result<tonic::Response<v1::ListAgentProviderTurnsResponse>, tonic::Status> {
        let response = self
            .handler
            .list_turns(from_wire_list_agent_provider_turns_request(
                request.into_inner(),
            ))
            .await
            .map_err(|e| crate::server_support::status_error("agent list turns", e))?;
        Ok(tonic::Response::new(
            to_wire_list_agent_provider_turns_response(response),
        ))
    }
    async fn cancel_turn(
        &self,
        request: tonic::Request<v1::CancelAgentProviderTurnRequest>,
    ) -> Result<tonic::Response<v1::AgentTurn>, tonic::Status> {
        let response = self
            .handler
            .cancel_turn(from_wire_cancel_agent_provider_turn_request(
                request.into_inner(),
            ))
            .await
            .map_err(|e| crate::server_support::status_error("agent cancel turn", e))?;
        Ok(tonic::Response::new(to_wire_agent_turn(response)))
    }
    async fn list_turn_events(
        &self,
        request: tonic::Request<v1::ListAgentProviderTurnEventsRequest>,
    ) -> Result<tonic::Response<v1::ListAgentProviderTurnEventsResponse>, tonic::Status> {
        let response = self
            .handler
            .list_turn_events(from_wire_list_agent_provider_turn_events_request(
                request.into_inner(),
            ))
            .await
            .map_err(|e| crate::server_support::status_error("agent list turn events", e))?;
        Ok(tonic::Response::new(
            to_wire_list_agent_provider_turn_events_response(response),
        ))
    }
    async fn get_interaction(
        &self,
        request: tonic::Request<v1::GetAgentProviderInteractionRequest>,
    ) -> Result<tonic::Response<v1::AgentInteraction>, tonic::Status> {
        let response = self
            .handler
            .get_interaction(from_wire_get_agent_provider_interaction_request(
                request.into_inner(),
            ))
            .await
            .map_err(|e| crate::server_support::status_error("agent get interaction", e))?;
        Ok(tonic::Response::new(to_wire_agent_interaction(response)))
    }
    async fn list_interactions(
        &self,
        request: tonic::Request<v1::ListAgentProviderInteractionsRequest>,
    ) -> Result<tonic::Response<v1::ListAgentProviderInteractionsResponse>, tonic::Status> {
        let response = self
            .handler
            .list_interactions(from_wire_list_agent_provider_interactions_request(
                request.into_inner(),
            ))
            .await
            .map_err(|e| crate::server_support::status_error("agent list interactions", e))?;
        Ok(tonic::Response::new(
            to_wire_list_agent_provider_interactions_response(response),
        ))
    }
    async fn resolve_interaction(
        &self,
        request: tonic::Request<v1::ResolveAgentProviderInteractionRequest>,
    ) -> Result<tonic::Response<v1::AgentInteraction>, tonic::Status> {
        let response = self
            .handler
            .resolve_interaction(from_wire_resolve_agent_provider_interaction_request(
                request.into_inner(),
            ))
            .await
            .map_err(|e| crate::server_support::status_error("agent resolve interaction", e))?;
        Ok(tonic::Response::new(to_wire_agent_interaction(response)))
    }
    async fn get_capabilities(
        &self,
        request: tonic::Request<v1::GetAgentProviderCapabilitiesRequest>,
    ) -> Result<tonic::Response<v1::AgentProviderCapabilities>, tonic::Status> {
        let response = self
            .handler
            .get_capabilities(from_wire_get_agent_provider_capabilities_request(
                request.into_inner(),
            ))
            .await
            .map_err(|e| crate::server_support::status_error("agent get capabilities", e))?;
        Ok(tonic::Response::new(to_wire_agent_provider_capabilities(
            response,
        )))
    }
}
