// Code generated by sdkgen. DO NOT EDIT.

#![allow(dead_code, unused_imports, unused_variables)]

//! Generated native types and clients for cache_provider_handler.proto.

use crate::cache::{
    CacheDeleteManyRequest, CacheDeleteManyResponse, CacheDeleteRequest, CacheDeleteResponse,
    CacheGetManyRequest, CacheGetManyResponse, CacheGetRequest, CacheGetResponse, CacheSetEntry,
    CacheSetManyRequest, CacheSetRequest, CacheTouchRequest, CacheTouchResponse,
};
use crate::codec::cache::{
    from_wire_cache_delete_many_request, from_wire_cache_delete_request,
    from_wire_cache_get_many_request, from_wire_cache_get_request,
    from_wire_cache_set_many_request, from_wire_cache_set_request, from_wire_cache_touch_request,
    to_wire_cache_delete_many_response, to_wire_cache_delete_response,
    to_wire_cache_get_many_response, to_wire_cache_get_response, to_wire_cache_touch_response,
};
use crate::generated::v1;
use crate::rpc_support::{GestaltError, gestalt_error_code};

/// Cache models the shared Gestalt cache-provider protocol.
///
/// Handler trait implemented by providers serving the `gestalt.provider.v1.Cache` service.
/// Methods receive the full native request; wire conversion and error
/// mapping live in the generated adapter (see [`CacheProviderServer`]).
/// Embed [`UnimplementedCacheProvider`] to default unimplemented methods.
#[tonic::async_trait]
pub trait CacheProvider: Send + Sync + 'static {
    /// Handles the `Get` RPC.
    async fn get(&self, key: String) -> Result<CacheGetResponse, GestaltError>;
    /// Handles the `GetMany` RPC.
    async fn get_many(&self, keys: Vec<String>) -> Result<CacheGetManyResponse, GestaltError>;
    /// Handles the `Set` RPC.
    async fn set(
        &self,
        key: String,
        value: Vec<u8>,
        ttl: Option<std::time::Duration>,
    ) -> Result<(), GestaltError>;
    /// Handles the `SetMany` RPC.
    async fn set_many(
        &self,
        entries: Vec<CacheSetEntry>,
        ttl: Option<std::time::Duration>,
    ) -> Result<(), GestaltError>;
    /// Handles the `Delete` RPC.
    async fn delete(&self, key: String) -> Result<CacheDeleteResponse, GestaltError>;
    /// Handles the `DeleteMany` RPC.
    async fn delete_many(&self, keys: Vec<String>)
    -> Result<CacheDeleteManyResponse, GestaltError>;
    /// Handles the `Touch` RPC.
    async fn touch(
        &self,
        key: String,
        ttl: Option<std::time::Duration>,
    ) -> Result<CacheTouchResponse, GestaltError>;
}

/// Fails every [`CacheProvider`] method with an Unimplemented error;
/// embed this to default the methods a provider does not implement.
#[derive(Debug, Default)]
pub struct UnimplementedCacheProvider;

#[tonic::async_trait]
impl CacheProvider for UnimplementedCacheProvider {
    async fn get(&self, key: String) -> Result<CacheGetResponse, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "cache get is not implemented",
        ))
    }
    async fn get_many(&self, keys: Vec<String>) -> Result<CacheGetManyResponse, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "cache get many is not implemented",
        ))
    }
    async fn set(
        &self,
        key: String,
        value: Vec<u8>,
        ttl: Option<std::time::Duration>,
    ) -> Result<(), GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "cache set is not implemented",
        ))
    }
    async fn set_many(
        &self,
        entries: Vec<CacheSetEntry>,
        ttl: Option<std::time::Duration>,
    ) -> Result<(), GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "cache set many is not implemented",
        ))
    }
    async fn delete(&self, key: String) -> Result<CacheDeleteResponse, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "cache delete is not implemented",
        ))
    }
    async fn delete_many(
        &self,
        keys: Vec<String>,
    ) -> Result<CacheDeleteManyResponse, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "cache delete many is not implemented",
        ))
    }
    async fn touch(
        &self,
        key: String,
        ttl: Option<std::time::Duration>,
    ) -> Result<CacheTouchResponse, GestaltError> {
        Err(GestaltError::new(
            gestalt_error_code::UNIMPLEMENTED,
            "cache touch is not implemented",
        ))
    }
}

/// Wire dispatch adapter: wraps an `Arc<P>` implementing [`CacheProvider`]
/// and implements the tonic wire trait `v1::cache_server::Cache`.
/// Requests convert from the wire, responses convert to the wire, and
/// handler errors map to gRPC statuses via `status_error`.
pub struct CacheProviderServer<P> {
    handler: std::sync::Arc<P>,
}

impl<P: CacheProvider> CacheProviderServer<P> {
    /// Creates a new dispatch adapter wrapping `handler`.
    pub fn new(handler: std::sync::Arc<P>) -> Self {
        Self { handler }
    }
}

#[tonic::async_trait]
impl<P: CacheProvider> v1::cache_server::Cache for CacheProviderServer<P> {
    async fn get(
        &self,
        request: tonic::Request<v1::CacheGetRequest>,
    ) -> Result<tonic::Response<v1::CacheGetResponse>, tonic::Status> {
        let native_request = from_wire_cache_get_request(request.into_inner());
        let response = self
            .handler
            .get(native_request.key)
            .await
            .map_err(|e| crate::server_support::status_error("cache get", e))?;
        Ok(tonic::Response::new(to_wire_cache_get_response(response)))
    }
    async fn get_many(
        &self,
        request: tonic::Request<v1::CacheGetManyRequest>,
    ) -> Result<tonic::Response<v1::CacheGetManyResponse>, tonic::Status> {
        let native_request = from_wire_cache_get_many_request(request.into_inner());
        let response = self
            .handler
            .get_many(native_request.keys)
            .await
            .map_err(|e| crate::server_support::status_error("cache get many", e))?;
        Ok(tonic::Response::new(to_wire_cache_get_many_response(
            response,
        )))
    }
    async fn set(
        &self,
        request: tonic::Request<v1::CacheSetRequest>,
    ) -> Result<tonic::Response<()>, tonic::Status> {
        let native_request = from_wire_cache_set_request(request.into_inner());
        self.handler
            .set(native_request.key, native_request.value, native_request.ttl)
            .await
            .map_err(|e| crate::server_support::status_error("cache set", e))?;
        Ok(tonic::Response::new(()))
    }
    async fn set_many(
        &self,
        request: tonic::Request<v1::CacheSetManyRequest>,
    ) -> Result<tonic::Response<()>, tonic::Status> {
        let native_request = from_wire_cache_set_many_request(request.into_inner());
        self.handler
            .set_many(native_request.entries, native_request.ttl)
            .await
            .map_err(|e| crate::server_support::status_error("cache set many", e))?;
        Ok(tonic::Response::new(()))
    }
    async fn delete(
        &self,
        request: tonic::Request<v1::CacheDeleteRequest>,
    ) -> Result<tonic::Response<v1::CacheDeleteResponse>, tonic::Status> {
        let native_request = from_wire_cache_delete_request(request.into_inner());
        let response = self
            .handler
            .delete(native_request.key)
            .await
            .map_err(|e| crate::server_support::status_error("cache delete", e))?;
        Ok(tonic::Response::new(to_wire_cache_delete_response(
            response,
        )))
    }
    async fn delete_many(
        &self,
        request: tonic::Request<v1::CacheDeleteManyRequest>,
    ) -> Result<tonic::Response<v1::CacheDeleteManyResponse>, tonic::Status> {
        let native_request = from_wire_cache_delete_many_request(request.into_inner());
        let response = self
            .handler
            .delete_many(native_request.keys)
            .await
            .map_err(|e| crate::server_support::status_error("cache delete many", e))?;
        Ok(tonic::Response::new(to_wire_cache_delete_many_response(
            response,
        )))
    }
    async fn touch(
        &self,
        request: tonic::Request<v1::CacheTouchRequest>,
    ) -> Result<tonic::Response<v1::CacheTouchResponse>, tonic::Status> {
        let native_request = from_wire_cache_touch_request(request.into_inner());
        let response = self
            .handler
            .touch(native_request.key, native_request.ttl)
            .await
            .map_err(|e| crate::server_support::status_error("cache touch", e))?;
        Ok(tonic::Response::new(to_wire_cache_touch_response(response)))
    }
}
