# Code generated by sdkgen. DO NOT EDIT.

"""Generated wire codec for migration.proto."""

from __future__ import annotations

from typing import Any

from .. import migration as native
from .._gen.v1 import migration_pb2 as _migration_pb2
from . import workflow


def to_wire_apply_workflow_migration_request(
    value: native.ApplyWorkflowMigrationRequest,
) -> Any:
    return _migration_pb2.ApplyWorkflowMigrationRequest(
        provider=value.provider,
        revision_id=value.revision_id,
        spec=None
        if value.spec is None
        else workflow.to_wire_workflow_definition_spec(value.spec),
        idempotency_key=value.idempotency_key,
    )


def from_wire_apply_workflow_migration_request(
    value: Any,
) -> native.ApplyWorkflowMigrationRequest:
    return native.ApplyWorkflowMigrationRequest(
        provider=value.provider,
        revision_id=value.revision_id,
        spec=workflow.from_wire_workflow_definition_spec(value.spec)
        if value.HasField("spec")
        else None,
        idempotency_key=value.idempotency_key,
    )


def to_wire_apply_workflow_migration_response(
    value: native.ApplyWorkflowMigrationResponse,
) -> Any:
    return _migration_pb2.ApplyWorkflowMigrationResponse(
        definition=None
        if value.definition is None
        else workflow.to_wire_workflow_definition(value.definition),
    )


def from_wire_apply_workflow_migration_response(
    value: Any,
) -> native.ApplyWorkflowMigrationResponse:
    return native.ApplyWorkflowMigrationResponse(
        definition=workflow.from_wire_workflow_definition(value.definition)
        if value.HasField("definition")
        else None,
    )
