pub const ENV_PLUGIN_SOCKET: &str = "GESTALT_PLUGIN_SOCKET";
pub const ENV_PLUGIN_PARENT_PID: &str = "GESTALT_PLUGIN_PARENT_PID";
pub const ENV_WRITE_CATALOG: &str = "GESTALT_PLUGIN_WRITE_CATALOG";
pub const ENV_PLUGIN_NAME: &str = "GESTALT_PLUGIN_NAME";
pub const CURRENT_PROTOCOL_VERSION: i32 = 2;
