// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/toolshed/v1/toolshed.proto

package toolshedv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_proto_toolshed_v1_toolshed_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *InvokeRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *InvokeRequest) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *InvokeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InvokeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_proto_toolshed_v1_toolshed_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *InvokeResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ListCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []string               `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCapabilitiesRequest) Reset() {
	*x = ListCapabilitiesRequest{}
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapabilitiesRequest) ProtoMessage() {}

func (x *ListCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*ListCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_toolshed_v1_toolshed_proto_rawDescGZIP(), []int{2}
}

func (x *ListCapabilitiesRequest) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

type ListCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []*Capability          `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCapabilitiesResponse) Reset() {
	*x = ListCapabilitiesResponse{}
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCapabilitiesResponse) ProtoMessage() {}

func (x *ListCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*ListCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_toolshed_v1_toolshed_proto_rawDescGZIP(), []int{3}
}

func (x *ListCapabilitiesResponse) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Capability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    []*Parameter           `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_proto_toolshed_v1_toolshed_proto_rawDescGZIP(), []int{4}
}

func (x *Capability) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Capability) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Capability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Capability) GetParameters() []*Parameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type Parameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_proto_toolshed_v1_toolshed_proto_rawDescGZIP(), []int{5}
}

func (x *Parameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Parameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Parameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Parameter) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_proto_toolshed_v1_toolshed_proto_rawDescGZIP(), []int{6}
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderInfo        `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_proto_toolshed_v1_toolshed_proto_rawDescGZIP(), []int{7}
}

func (x *ListProvidersResponse) GetProviders() []*ProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

type ProviderInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName    string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ConnectionMode string                 `protobuf:"bytes,4,opt,name=connection_mode,json=connectionMode,proto3" json:"connection_mode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toolshed_v1_toolshed_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_proto_toolshed_v1_toolshed_proto_rawDescGZIP(), []int{8}
}

func (x *ProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProviderInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProviderInfo) GetConnectionMode() string {
	if x != nil {
		return x.ConnectionMode
	}
	return ""
}

var File_proto_toolshed_v1_toolshed_proto protoreflect.FileDescriptor

const file_proto_toolshed_v1_toolshed_proto_rawDesc = "" +
	"\n" +
	" proto/toolshed/v1/toolshed.proto\x12\vtoolshed.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xb2\x01\n" +
	"\rInvokeRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12/\n" +
	"\x06params\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06params\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"<\n" +
	"\x0eInvokeResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"7\n" +
	"\x17ListCapabilitiesRequest\x12\x1c\n" +
	"\tproviders\x18\x01 \x03(\tR\tproviders\"W\n" +
	"\x18ListCapabilitiesResponse\x12;\n" +
	"\fcapabilities\x18\x01 \x03(\v2\x17.toolshed.v1.CapabilityR\fcapabilities\"\xa0\x01\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x126\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v2\x16.toolshed.v1.ParameterR\n" +
	"parameters\"q\n" +
	"\tParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\"\x16\n" +
	"\x14ListProvidersRequest\"P\n" +
	"\x15ListProvidersResponse\x127\n" +
	"\tproviders\x18\x01 \x03(\v2\x19.toolshed.v1.ProviderInfoR\tproviders\"\x90\x01\n" +
	"\fProviderInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0fconnection_mode\x18\x04 \x01(\tR\x0econnectionMode2\x8d\x02\n" +
	"\x0fToolshedService\x12A\n" +
	"\x06Invoke\x12\x1a.toolshed.v1.InvokeRequest\x1a\x1b.toolshed.v1.InvokeResponse\x12_\n" +
	"\x10ListCapabilities\x12$.toolshed.v1.ListCapabilitiesRequest\x1a%.toolshed.v1.ListCapabilitiesResponse\x12V\n" +
	"\rListProviders\x12!.toolshed.v1.ListProvidersRequest\x1a\".toolshed.v1.ListProvidersResponseBDZBgithub.com/valon-technologies/gestalt/proto/toolshed/v1;toolshedv1b\x06proto3"

var (
	file_proto_toolshed_v1_toolshed_proto_rawDescOnce sync.Once
	file_proto_toolshed_v1_toolshed_proto_rawDescData []byte
)

func file_proto_toolshed_v1_toolshed_proto_rawDescGZIP() []byte {
	file_proto_toolshed_v1_toolshed_proto_rawDescOnce.Do(func() {
		file_proto_toolshed_v1_toolshed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_toolshed_v1_toolshed_proto_rawDesc), len(file_proto_toolshed_v1_toolshed_proto_rawDesc)))
	})
	return file_proto_toolshed_v1_toolshed_proto_rawDescData
}

var file_proto_toolshed_v1_toolshed_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_toolshed_v1_toolshed_proto_goTypes = []any{
	(*InvokeRequest)(nil),            // 0: toolshed.v1.InvokeRequest
	(*InvokeResponse)(nil),           // 1: toolshed.v1.InvokeResponse
	(*ListCapabilitiesRequest)(nil),  // 2: toolshed.v1.ListCapabilitiesRequest
	(*ListCapabilitiesResponse)(nil), // 3: toolshed.v1.ListCapabilitiesResponse
	(*Capability)(nil),               // 4: toolshed.v1.Capability
	(*Parameter)(nil),                // 5: toolshed.v1.Parameter
	(*ListProvidersRequest)(nil),     // 6: toolshed.v1.ListProvidersRequest
	(*ListProvidersResponse)(nil),    // 7: toolshed.v1.ListProvidersResponse
	(*ProviderInfo)(nil),             // 8: toolshed.v1.ProviderInfo
	(*structpb.Struct)(nil),          // 9: google.protobuf.Struct
}
var file_proto_toolshed_v1_toolshed_proto_depIdxs = []int32{
	9, // 0: toolshed.v1.InvokeRequest.params:type_name -> google.protobuf.Struct
	4, // 1: toolshed.v1.ListCapabilitiesResponse.capabilities:type_name -> toolshed.v1.Capability
	5, // 2: toolshed.v1.Capability.parameters:type_name -> toolshed.v1.Parameter
	8, // 3: toolshed.v1.ListProvidersResponse.providers:type_name -> toolshed.v1.ProviderInfo
	0, // 4: toolshed.v1.ToolshedService.Invoke:input_type -> toolshed.v1.InvokeRequest
	2, // 5: toolshed.v1.ToolshedService.ListCapabilities:input_type -> toolshed.v1.ListCapabilitiesRequest
	6, // 6: toolshed.v1.ToolshedService.ListProviders:input_type -> toolshed.v1.ListProvidersRequest
	1, // 7: toolshed.v1.ToolshedService.Invoke:output_type -> toolshed.v1.InvokeResponse
	3, // 8: toolshed.v1.ToolshedService.ListCapabilities:output_type -> toolshed.v1.ListCapabilitiesResponse
	7, // 9: toolshed.v1.ToolshedService.ListProviders:output_type -> toolshed.v1.ListProvidersResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_toolshed_v1_toolshed_proto_init() }
func file_proto_toolshed_v1_toolshed_proto_init() {
	if File_proto_toolshed_v1_toolshed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_toolshed_v1_toolshed_proto_rawDesc), len(file_proto_toolshed_v1_toolshed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_toolshed_v1_toolshed_proto_goTypes,
		DependencyIndexes: file_proto_toolshed_v1_toolshed_proto_depIdxs,
		MessageInfos:      file_proto_toolshed_v1_toolshed_proto_msgTypes,
	}.Build()
	File_proto_toolshed_v1_toolshed_proto = out.File
	file_proto_toolshed_v1_toolshed_proto_goTypes = nil
	file_proto_toolshed_v1_toolshed_proto_depIdxs = nil
}
