/**
 * Public API surface for executable Gestalt providers.
 *
 * Use this package to define provider runtimes, operation schemas, handlers,
 * host-service clients, and provider-owned telemetry. The provider manifest
 * still owns static identity, connections, hosted HTTP routes, passthrough
 * surfaces, and release metadata.
 *
 * @example
 * ```ts
 * import { defineApp, ok, operation, s } from "@valon-technologies/gestalt";
 *
 * export const app = defineApp({
 *   displayName: "Example Provider",
 *   operations: [
 *     operation({
 *       id: "hello",
 *       input: s.object({ name: s.string({ default: "World" }) }),
 *       output: s.object({ message: s.string() }),
 *       async handler(input) {
 *         return ok({ message: `Hello, ${input.name}` });
 *       },
 *     }),
 *   ],
 * });
 * ```
 *
 * @module
 */
export {
  connectionParam,
  ok,
  request,
  response,
  type Access,
  type Credential,
  type Host,
  type MaybePromise,
  type OperationResult,
  type Request,
  type Response,
  type Subject,
  type SubjectInput,
} from "../../../../src/api.ts";
export {
  type HTTPSubjectRequest,
  HTTPSubjectResolutionError,
  type HTTPSubjectResolutionContext,
  type HTTPSubjectResolver,
  httpSubjectError,
} from "../../../../src/http-subject.ts";
export {
  catalogToJson,
  catalogToYaml,
  schemaToCatalogSchema,
  schemaToParameters,
  writeCatalogYaml,
  type Catalog,
  type CatalogOperation,
  type CatalogParameter,
  type CatalogSchema,
  type OperationAnnotations,
} from "../../../../src/catalog.ts";
export {
  App,
  type AccessContext,
  type AgentInvocationContext,
  type AppInvokeGraphQLRequest,
  type AppInvokeRequest,
  type CredentialContext,
  type HostContext,
  type InvocationContext,
  type ProviderContext,
  type RequestContext,
  type RequestMetaContext,
  type StringList,
  type SubjectContext,
  type SubjectPermissionContext,
} from "../../../../src/app.ts";
export {
  InvokeError,
  decodeAppResult,
  decodeGraphQLResult,
  isOk,
  requireOk,
} from "../../../../src/invoke_support.ts";
export {
  Agent,
  agentOutputKindStructured,
  agentOutputKindText,
  type AgentWorkspace,
  type AgentWorkspaceGitCheckout,
  type PreparedAgentWorkspace,
} from "../../../../src/agent.ts";
export { Workflow } from "../../../../src/workflow.ts";
export {
  GestaltError,
  GestaltErrorCode,
  type DurationMs,
  type Init,
  type RpcStatus,
} from "../../../../src/rpc_support.ts";
export {
  relationshipTargetKindResource,
  relationshipTargetKindSubject,
  relationshipTargetKindSubjectSet,
} from "../../../../src/authorization.ts";
export {
  RuntimeLogHost,
  type RuntimeLogAppendInput,
  type RuntimeLogAppendLogsInput,
  type RuntimeLogAppendResponse,
  type RuntimeLogStreamInput,
  type RuntimeLogStreamName,
  type RuntimeLogWriterOptions,
} from "../../../../src/runtime-log-host.ts";
export {
  AuthenticationProvider,
  defineAuthenticationProvider,
  isAuthenticationProvider,
  type AuthenticatedUser,
  type AuthenticationProviderOptions,
  type AuthenticationSessionSettings,
  type BeginLoginRequest,
  type BeginLoginResponse,
  type CompleteLoginRequest,
} from "../../../../src/auth.ts";
export {
  Cache,
  type CacheDeleteManyRequest,
  type CacheDeleteManyResponse,
  type CacheDeleteRequest,
  type CacheDeleteResponse,
  type CacheGetManyRequest,
  type CacheGetManyResponse,
  type CacheGetRequest,
  type CacheGetResponse,
  type CacheResult,
  type CacheSetEntry,
  type CacheSetManyRequest,
  type CacheSetRequest,
  type CacheTouchRequest,
  type CacheTouchResponse,
} from "../../../../src/cache.ts";
export {
  CacheProvider,
  defineCacheProvider,
  isCacheProvider,
  type CacheEntry,
  type CacheProviderOptions,
  type CacheSetOptions,
} from "../../../../src/providers/cache.ts";
export {
  defineSecretsProvider,
  isSecretsProvider,
  type SecretsProviderOptions,
} from "../../../../src/providers/secrets.ts";
export {
  defineApp,
  isAppProvider,
  operation,
  AppProvider,
  type ConnectionMode,
  type ConnectionParamDefinition,
  type OperationDefinition,
  type OperationOptions,
  type AppDefinitionOptions,
  type SessionCatalog,
  type SessionCatalogHandler,
} from "../../../../src/providers/app.ts";
export {
  isProviderBase,
  ProviderBase,
  slugName,
  type CloseHandler,
  type ConfigureHandler,
  type HealthCheckHandler,
  type ProviderBaseOptions,
  type ProviderKind,
  type ProviderMetadata,
  type StartHandler,
  type WarningsHandler,
} from "../../../../src/provider.ts";
export {
  defineRuntimeProvider,
  isRuntimeProvider,
  RuntimeEgressMode,
  RuntimeProvider,
  type GetRuntimeSessionRequest,
  type HostedApp,
  type ListRuntimeSessionsRequest,
  type RuntimeAgentWorkspace,
  type RuntimeAgentWorkspaceGitCheckout,
  type RuntimeImagePullAuth,
  type RuntimePreparedAgentWorkspace,
  type RuntimeProviderOptions,
  type RuntimeSession,
  type RuntimeSessionLifecycle,
  type RuntimeSupport,
  type PrepareRuntimeWorkspaceRequest,
  type PrepareRuntimeWorkspaceResponse,
  type RemoveRuntimeWorkspaceRequest,
  type StartHostedAppRequest,
  type StartRuntimeSessionRequest,
  type StopRuntimeSessionRequest,
} from "../../../../src/runtime-provider.ts";
export {
  AlreadyExistsError,
  ColumnType,
  CursorDirection,
  IndexedDB,
  NotFoundError,
  TransactionError,
  type ColumnSchema,
  type Cursor,
  type Index,
  type IndexSchema,
  type KeyRange,
  type ObjectStore,
  type ObjectStoreSchema,
  type OpenCursorOptions,
  type Record,
  type Transaction,
  type TransactionDurabilityHint,
  type TransactionIndex,
  type TransactionMode,
  type TransactionObjectStore,
  type TransactionOptions,
} from "../../../../src/providers/indexeddb.ts";
export {
  PresignMethod,
  S3,
  S3ObjectAccess,
  type ByteRange,
  type CopyObjectRequest,
  type CopyObjectResponse,
  type CreateObjectAccessURLRequest,
  type CreateObjectAccessURLResponse,
  type DeleteObjectRequest,
  type HeadObjectRequest,
  type HeadObjectResponse,
  type ListObjectsRequest,
  type ListObjectsResponse,
  type PresignObjectRequest,
  type PresignObjectResponse,
  type ReadObjectChunk,
  type ReadObjectChunkResult,
  type ReadObjectRequest,
  type S3ObjectMeta,
  type S3ObjectRef,
  type WriteObjectOpen,
  type WriteObjectRequest,
  type WriteObjectRequestMsg,
  type WriteObjectResponse,
} from "../../../../src/s3.ts";
export {
  defineS3Provider,
  isS3Provider,
  S3InvalidRangeError,
  S3NotFoundError,
  S3PreconditionFailedError,
  S3Provider,
  type CopyOptions,
  type ListOptions,
  type ListPage,
  type ObjectMeta,
  type ObjectRef,
  type PresignOptions,
  type PresignResult,
  type ProviderReadResult,
  type ReadOptions,
  type S3BodySource,
  type S3ProviderOptions,
  type WriteOptions,
} from "../../../../src/providers/s3.ts";
export {
  AgentExecutionStatus,
  AgentInteractionState,
  AgentInteractionType,
  AgentMessagePartType,
  AgentProvider,
  AgentSessionState,
  AgentToolSourceMode,
  defineAgentProvider,
  isAgentProvider,
  type AgentInteraction,
  type AgentMessage,
  type AgentMessagePart,
  type AgentMessagePartImageRef,
  type AgentMessagePartToolCall,
  type AgentMessagePartToolResult,
  type AgentPreparedWorkspace,
  type AgentProviderCapabilities,
  type AgentProviderOptions,
  type AgentSession,
  type AgentSessionStartConfig,
  type AgentSessionStartHook,
  type AgentSessionStartHookOutput,
  type AgentToolAnnotations,
  type AgentToolRef,
  type AgentTurn,
  type AgentTurnDisplay,
  type AgentTurnEvent,
  type CancelAgentProviderTurnRequest,
  type CreateAgentProviderSessionRequest,
  type CreateAgentProviderTurnRequest,
  type GetAgentProviderCapabilitiesRequest,
  type GetAgentProviderInteractionRequest,
  type GetAgentProviderSessionRequest,
  type GetAgentProviderTurnRequest,
  type ListAgentProviderInteractionsRequest,
  type ListAgentProviderInteractionsResponse,
  type ListAgentProviderSessionsRequest,
  type ListAgentProviderSessionsResponse,
  type ListAgentProviderTurnEventsRequest,
  type ListAgentProviderTurnEventsResponse,
  type ListAgentProviderTurnsRequest,
  type ListAgentProviderTurnsResponse,
  type ListedAgentTool,
  type ResolveAgentProviderInteractionRequest,
  type UpdateAgentProviderSessionRequest,
} from "../../../../src/providers/agent.ts";
export * from "../../../../src/providers/workflow.ts";
