/**
 * Public API surface for executable Gestalt providers.
 *
 * Use this package to define provider runtimes, operation schemas, handlers,
 * host-service clients, and provider-owned telemetry. The provider manifest
 * still owns static identity, connections, hosted HTTP routes, passthrough
 * surfaces, and release metadata.
 *
 * @example
 * ```ts
 * import { defineApp, ok, operation, s } from "@valon-technologies/gestalt";
 *
 * export const app = defineApp({
 *   displayName: "Example Provider",
 *   operations: [
 *     operation({
 *       id: "hello",
 *       input: s.object({ name: s.string({ default: "World" }) }),
 *       output: s.object({ message: s.string() }),
 *       async handler(input) {
 *         return ok({ message: `Hello, ${input.name}` });
 *       },
 *     }),
 *   ],
 * });
 * ```
 *
 * @module
 */
export {
  Authorization,
  AUTHORIZATION_SUBJECT_TYPE_SUBJECT,
  authorizationAction,
  authorizationRelationship,
  authorizationRelationshipKey,
  authorizationRelationshipKeyWithTarget,
  authorizationRelationshipWithTarget,
  authorizationResource,
  authorizationResourceTarget,
  authorizationSubject,
  authorizationSubjectSet,
  authorizationSubjectSetTarget,
  authorizationSubjectTarget,
  type AuthorizationAction,
  type AuthorizationActionSearch,
  type AuthorizationDecision,
  type AuthorizationEffectiveSearchSubjectsInput,
  type AuthorizationEffectiveSubjectSearch,
  type AuthorizationEvaluateInput,
  type AuthorizationExpandInput,
  type AuthorizationExpand,
  type AuthorizationExpandNode,
  type AuthorizationMetadata,
  type AuthorizationReadRelationshipsInput,
  type AuthorizationReadRelationships,
  type AuthorizationRelationship,
  type AuthorizationRelationshipKey,
  type AuthorizationRelationshipTarget,
  type AuthorizationRelationshipTargetKind,
  type AuthorizationResource,
  type AuthorizationResourceSearch,
  type AuthorizationSearchActionsInput,
  type AuthorizationSearchResourcesInput,
  type AuthorizationSearchSubjectsInput,
  type AuthorizationSubject,
  type AuthorizationSubjectSearch,
  type AuthorizationSubjectSet,
  type AuthorizationWriteRelationshipsInput,
} from "../../../../src/authorization.ts";
export {
  connectionParam,
  ok,
  request,
  response,
  type Access,
  type Credential,
  type Host,
  type MaybePromise,
  type OperationResult,
  type Request,
  type Response,
  type Subject,
  type SubjectInput,
} from "../../../../src/api.ts";
export {
  type HTTPSubjectRequest,
  HTTPSubjectResolutionError,
  type HTTPSubjectResolutionContext,
  type HTTPSubjectResolver,
  httpSubjectError,
} from "../../../../src/http-subject.ts";
export {
  catalogToJson,
  catalogToYaml,
  schemaToCatalogSchema,
  schemaToParameters,
  writeCatalogYaml,
  type Catalog,
  type CatalogOperation,
  type CatalogParameter,
  type CatalogSchema,
  type OperationAnnotations,
} from "../../../../src/catalog.ts";
export {
  App,
  type AppGraphQLInvokeOptions,
  type AppInvocationGrant,
  type AppInvokeOptions,
} from "../../../../src/app-access.ts";
export {
  Agent,
  type AgentCancelTurn,
  type AgentCreateSession,
  type AgentCreateTurn,
  type AgentGetSession,
  type AgentGetTurn,
  type AgentListInteractions,
  type AgentListSessions,
  type AgentListTurnEvents,
  type AgentListTurns,
  type AgentResolveInteraction,
  type AgentUpdateSession,
  type AgentWorkspace,
  type AgentWorkspaceGitCheckout,
} from "../../../../src/agent-access.ts";
export * from "../../../../src/workflow-access.ts";
export {
  RuntimeLogHost,
  type RuntimeLogAppendInput,
  type RuntimeLogAppendLogsInput,
  type RuntimeLogAppendResponse,
  type RuntimeLogStreamInput,
  type RuntimeLogStreamName,
  type RuntimeLogWriterOptions,
} from "../../../../src/runtime-log-host.ts";
export {
  AuthenticationProvider,
  defineAuthenticationProvider,
  isAuthenticationProvider,
  type AuthenticatedUser,
  type AuthenticationProviderOptions,
  type AuthenticationSessionSettings,
  type BeginLoginRequest,
  type BeginLoginResponse,
  type CompleteLoginRequest,
} from "../../../../src/auth.ts";
export {
  Cache,
  CacheProvider,
  defineCacheProvider,
  isCacheProvider,
  type CacheEntry,
  type CacheProviderOptions,
  type CacheSetOptions,
} from "../../../../src/cache.ts";
export {
  defineSecretsProvider,
  isSecretsProvider,
  type SecretsProviderOptions,
} from "../../../../src/secrets.ts";
export {
  defineApp,
  isAppProvider,
  operation,
  AppProvider,
  type ConnectionMode,
  type ConnectionParamDefinition,
  type OperationDefinition,
  type OperationOptions,
  type AppDefinitionOptions,
  type SessionCatalog,
  type SessionCatalogHandler,
} from "../../../../src/app.ts";
export {
  isProviderBase,
  ProviderBase,
  slugName,
  type CloseHandler,
  type ConfigureHandler,
  type HealthCheckHandler,
  type ProviderBaseOptions,
  type ProviderKind,
  type ProviderMetadata,
  type StartHandler,
  type WarningsHandler,
} from "../../../../src/provider.ts";
export {
  defineRuntimeProvider,
  isRuntimeProvider,
  RuntimeEgressMode,
  RuntimeProvider,
  type GetRuntimeSessionRequest,
  type HostedApp,
  type ListRuntimeSessionsRequest,
  type RuntimeAgentWorkspace,
  type RuntimeAgentWorkspaceGitCheckout,
  type RuntimeImagePullAuth,
  type RuntimePreparedAgentWorkspace,
  type RuntimeProviderOptions,
  type RuntimeSession,
  type RuntimeSessionLifecycle,
  type RuntimeSupport,
  type PrepareRuntimeWorkspaceRequest,
  type PrepareRuntimeWorkspaceResponse,
  type RemoveRuntimeWorkspaceRequest,
  type StartHostedAppRequest,
  type StartRuntimeSessionRequest,
  type StopRuntimeSessionRequest,
} from "../../../../src/runtime-provider.ts";
export {
  AlreadyExistsError,
  ColumnType,
  CursorDirection,
  IndexedDB,
  NotFoundError,
  TransactionError,
  type ColumnSchema,
  type Cursor,
  type Index,
  type IndexSchema,
  type KeyRange,
  type ObjectStore,
  type ObjectStoreSchema,
  type OpenCursorOptions,
  type Record,
  type Transaction,
  type TransactionDurabilityHint,
  type TransactionIndex,
  type TransactionMode,
  type TransactionObjectStore,
  type TransactionOptions,
} from "../../../../src/indexeddb.ts";
export {
  defineS3Provider,
  isS3Provider,
  PresignMethod,
  S3,
  S3InvalidRangeError,
  S3NotFoundError,
  S3PreconditionFailedError,
  S3Provider,
  type ByteRange,
  type CopyOptions,
  type ListOptions,
  type ListPage,
  type ObjectAccessURL,
  type ObjectAccessURLOptions,
  type ObjectMeta,
  type ObjectRef,
  type PresignOptions,
  type PresignResult,
  type ProviderReadResult,
  type ReadOptions,
  type ReadResult,
  type S3BodySource,
  type S3Object,
  type S3ProviderOptions,
  type WriteOptions,
} from "../../../../src/s3.ts";
export {
  AgentExecutionStatus,
  AgentHost,
  AgentInteractionState,
  AgentInteractionType,
  AgentMessagePartType,
  AgentProvider,
  AgentSessionState,
  AgentToolSourceMode,
  defineAgentProvider,
  isAgentProvider,
  type AgentHostExecuteToolInput,
  type AgentHostListToolsInput,
  type AgentHostResolveConnectionInput,
  type AgentInteraction,
  type AgentMessage,
  type AgentMessagePart,
  type AgentMessagePartImageRef,
  type AgentMessagePartToolCall,
  type AgentMessagePartToolResult,
  type AgentPreparedWorkspace,
  type AgentProviderCapabilities,
  type AgentProviderOptions,
  type AgentSession,
  type AgentSessionStartConfig,
  type AgentSessionStartHook,
  type AgentSessionStartHookOutput,
  type AgentToolAnnotations,
  type AgentToolRef,
  type AgentTurn,
  type AgentTurnDisplay,
  type AgentTurnEvent,
  type CancelAgentProviderTurnRequest,
  type CreateAgentProviderSessionRequest,
  type CreateAgentProviderTurnRequest,
  type ExecuteAgentToolRequest,
  type ExecuteAgentToolResponse,
  type GetAgentProviderCapabilitiesRequest,
  type GetAgentProviderInteractionRequest,
  type GetAgentProviderSessionRequest,
  type GetAgentProviderTurnRequest,
  type ListAgentProviderInteractionsRequest,
  type ListAgentProviderInteractionsResponse,
  type ListAgentProviderSessionsRequest,
  type ListAgentProviderSessionsResponse,
  type ListAgentProviderTurnEventsRequest,
  type ListAgentProviderTurnEventsResponse,
  type ListAgentProviderTurnsRequest,
  type ListAgentProviderTurnsResponse,
  type ListAgentToolsRequest,
  type ListAgentToolsResponse,
  type ListedAgentTool,
  type ResolveAgentConnectionRequest,
  type ResolveAgentProviderInteractionRequest,
  type ResolvedAgentConnection,
  type ResolvedAgentTool,
  type UpdateAgentProviderSessionRequest,
} from "../../../../src/agent.ts";
export * from "../../../../src/workflow.ts";
