// Code generated by sdkgen. DO NOT EDIT.

import type { JsonObject } from "@bufbuild/protobuf";
import { createClient } from "@connectrpc/connect";
import type { Client, Transport } from "@connectrpc/connect";

import {
  createHostServiceGrpcTransport,
  hostServiceMetadataInterceptors,
  parseHostServiceTarget,
  requireHostServiceTarget,
} from "./host-service.ts";

import * as wire from "./internal/gen/v1/authorization_pb.ts";
import {
  fromWireAddRelationshipResponse,
  fromWireCheckAccessManyResponse,
  fromWireCheckAccessResponse,
  fromWireDeleteRelationshipResponse,
  fromWireGetActiveModelRefResponse,
  fromWireListActiveModelResourceTypesResponse,
  fromWireListRelationshipsResponse,
  fromWireSetActiveModelResponse,
  fromWireSetAuthorizationStateResponse,
  toWireAddRelationshipRequest,
  toWireCheckAccessManyRequest,
  toWireCheckAccessRequest,
  toWireDeleteRelationshipRequest,
  toWireListActiveModelResourceTypesRequest,
  toWireListRelationshipsRequest,
  toWireSetActiveModelRequest,
  toWireSetAuthorizationStateRequest,
} from "./internal/codec/authorization.ts";
import { callUnary } from "./internal/codec/support.ts";

export const DefaultAccessPolicy = {
  DEFAULT_ACCESS_POLICY_DENY: 0,
  DEFAULT_ACCESS_POLICY_ALLOW: 1,
} as const;

export type DefaultAccessPolicy = number;

export const RelationshipTargetType = {
  RELATIONSHIP_TARGET_TYPE_UNSPECIFIED: 0,
  RELATIONSHIP_TARGET_TYPE_SUBJECT: 1,
  RELATIONSHIP_TARGET_TYPE_RESOURCE: 2,
  RELATIONSHIP_TARGET_TYPE_SUBJECT_SET: 3,
} as const;

export type RelationshipTargetType = number;

export const SourceLayer = {
  SOURCE_LAYER_UNSPECIFIED: 0,
  SOURCE_LAYER_STATIC_CONFIG: 1,
  SOURCE_LAYER_RUNTIME: 2,
} as const;

export type SourceLayer = number;

export interface Action {
  name: string;
  properties?: JsonObject;
}

export interface AddRelationshipRequest {
  relationship?: Relationship;
}

export interface AddRelationshipResponse {
  relationship?: Relationship;
}

export interface AuthorizationModel {
  id: string;
  version: string;
  resourceTypes: AuthorizationModelResourceType[];
}

export interface AuthorizationModelRef {
  id: string;
  version: string;
  createdAt?: Date;
}

export interface AuthorizationModelResourceType {
  name: string;
  relations: ModelRelation[];
  actions: ModelAction[];
  sourceLayer: SourceLayer;
  defaultAccessPolicy: DefaultAccessPolicy;
}

export interface AuthorizationModelResourceTypeFilter {
  name: string;
  sourceLayer: SourceLayer;
}

export interface CheckAccessManyRequest {
  requests: CheckAccessRequest[];
}

export interface CheckAccessManyResponse {
  decisions: CheckAccessResponse[];
}

export interface CheckAccessRequest {
  subject?: Subject;
  action?: Action;
  resource?: Resource;
}

export interface CheckAccessResponse {
  allowed: boolean;
  modelId: string;
}

export interface DeleteRelationshipRequest {
  relationshipTuple?: RelationshipTuple;
}

export interface DeleteRelationshipResponse {}

export interface GetActiveModelRefResponse {
  model?: AuthorizationModelRef;
}

export interface ListActiveModelResourceTypesRequest {
  filter?: AuthorizationModelResourceTypeFilter;
  pageSize: number;
  pageToken: string;
}

export interface ListActiveModelResourceTypesResponse {
  resourceTypes: AuthorizationModelResourceType[];
  nextPageToken: string;
  modelId: string;
}

export interface ListRelationshipsRequest {
  filter?: RelationshipFilter;
  pageSize: number;
  pageToken: string;
}

export interface ListRelationshipsResponse {
  relationships: Relationship[];
  nextPageToken: string;
}

export interface ModelAction {
  name: string;
  relations: string[];
}

export type ModelAllowedTargetKind =
  | { case: "subjectType"; value: string }
  | { case: "resourceType"; value: string }
  | { case: "subjectSetType"; value: SubjectSetType }
  | { case: undefined; value?: undefined };

export interface ModelAllowedTarget {
  kind: ModelAllowedTargetKind;
}

export interface ModelRelation {
  name: string;
  allowedTargets: ModelAllowedTarget[];
}

export interface Relationship {
  tuple?: RelationshipTuple;
  properties?: JsonObject;
  sourceLayer: SourceLayer;
}

export interface RelationshipFilter {
  target?: RelationshipTarget;
  relation: string;
  resource?: Resource;
  targetType: RelationshipTargetType;
  targetEntityType: string;
  resourceType: string;
  sourceLayer: SourceLayer;
}

export type RelationshipTargetKind =
  | { case: "subject"; value: Subject }
  | { case: "resource"; value: Resource }
  | { case: "subjectSet"; value: SubjectSet }
  | { case: undefined; value?: undefined };

export interface RelationshipTarget {
  kind: RelationshipTargetKind;
}

export interface RelationshipTuple {
  target?: RelationshipTarget;
  relation: string;
  resource?: Resource;
}

export interface Resource {
  type: string;
  id: string;
  properties?: JsonObject;
}

export interface SetActiveModelRequest {
  model?: AuthorizationModel;
}

export interface SetActiveModelResponse {
  model?: AuthorizationModelRef;
}

export interface SetAuthorizationStateRequest {
  model?: AuthorizationModel;
  relationships: Relationship[];
}

export interface SetAuthorizationStateResponse {
  activeModel?: AuthorizationModelRef;
}

export interface Subject {
  type: string;
  id: string;
  properties?: JsonObject;
}

export interface SubjectSet {
  resource?: Resource;
  relation: string;
}

export interface SubjectSetType {
  resourceType: string;
  relation: string;
}

export class Authorization {
  private readonly client: Client<typeof wire.Authorization>;

  constructor(transport: Transport) {
    this.client = createClient(wire.Authorization, transport);
  }

  static connect(name?: string): Authorization {
    const { target, token } = requireHostServiceTarget("authorization");
    const transport = createHostServiceGrpcTransport(
      parseHostServiceTarget("authorization", target),
      hostServiceMetadataInterceptors(token, name?.trim() ?? ""),
    );
    return new Authorization(transport);
  }

  async checkAccess(
    action?: Action,
    resource?: Resource,
  ): Promise<CheckAccessResponse> {
    const request: CheckAccessRequest = {
      ...(action !== undefined ? { action } : {}),
      ...(resource !== undefined ? { resource } : {}),
    };
    const response = await callUnary(() =>
      this.client.checkAccess(toWireCheckAccessRequest(request)),
    );
    return fromWireCheckAccessResponse(response);
  }

  async checkAccessRaw(
    request: CheckAccessRequest,
  ): Promise<CheckAccessResponse> {
    const response = await callUnary(() =>
      this.client.checkAccess(toWireCheckAccessRequest(request)),
    );
    return fromWireCheckAccessResponse(response);
  }

  async checkAccessMany(
    requests: CheckAccessRequest[],
  ): Promise<CheckAccessManyResponse> {
    const request: CheckAccessManyRequest = { requests };
    const response = await callUnary(() =>
      this.client.checkAccessMany(toWireCheckAccessManyRequest(request)),
    );
    return fromWireCheckAccessManyResponse(response);
  }

  async checkAccessManyRaw(
    request: CheckAccessManyRequest,
  ): Promise<CheckAccessManyResponse> {
    const response = await callUnary(() =>
      this.client.checkAccessMany(toWireCheckAccessManyRequest(request)),
    );
    return fromWireCheckAccessManyResponse(response);
  }

  async listRelationships(
    pageSize: number,
    pageToken: string,
    filter?: RelationshipFilter,
  ): Promise<ListRelationshipsResponse> {
    const request: ListRelationshipsRequest = {
      pageSize,
      pageToken,
      ...(filter !== undefined ? { filter } : {}),
    };
    const response = await callUnary(() =>
      this.client.listRelationships(toWireListRelationshipsRequest(request)),
    );
    return fromWireListRelationshipsResponse(response);
  }

  async listRelationshipsRaw(
    request: ListRelationshipsRequest,
  ): Promise<ListRelationshipsResponse> {
    const response = await callUnary(() =>
      this.client.listRelationships(toWireListRelationshipsRequest(request)),
    );
    return fromWireListRelationshipsResponse(response);
  }

  async addRelationship(
    relationship?: Relationship,
  ): Promise<Relationship | undefined> {
    const request: AddRelationshipRequest = {
      ...(relationship !== undefined ? { relationship } : {}),
    };
    const response = fromWireAddRelationshipResponse(
      await callUnary(() =>
        this.client.addRelationship(toWireAddRelationshipRequest(request)),
      ),
    );
    return response.relationship;
  }

  async addRelationshipRaw(
    request: AddRelationshipRequest,
  ): Promise<AddRelationshipResponse> {
    const response = await callUnary(() =>
      this.client.addRelationship(toWireAddRelationshipRequest(request)),
    );
    return fromWireAddRelationshipResponse(response);
  }

  async deleteRelationship(
    relationshipTuple?: RelationshipTuple,
  ): Promise<DeleteRelationshipResponse> {
    const request: DeleteRelationshipRequest = {
      ...(relationshipTuple !== undefined ? { relationshipTuple } : {}),
    };
    const response = await callUnary(() =>
      this.client.deleteRelationship(toWireDeleteRelationshipRequest(request)),
    );
    return fromWireDeleteRelationshipResponse(response);
  }

  async deleteRelationshipRaw(
    request: DeleteRelationshipRequest,
  ): Promise<DeleteRelationshipResponse> {
    const response = await callUnary(() =>
      this.client.deleteRelationship(toWireDeleteRelationshipRequest(request)),
    );
    return fromWireDeleteRelationshipResponse(response);
  }

  async setAuthorizationState(
    relationships: Relationship[],
    model?: AuthorizationModel,
  ): Promise<AuthorizationModelRef | undefined> {
    const request: SetAuthorizationStateRequest = {
      relationships,
      ...(model !== undefined ? { model } : {}),
    };
    const response = fromWireSetAuthorizationStateResponse(
      await callUnary(() =>
        this.client.setAuthorizationState(
          toWireSetAuthorizationStateRequest(request),
        ),
      ),
    );
    return response.activeModel;
  }

  async setAuthorizationStateRaw(
    request: SetAuthorizationStateRequest,
  ): Promise<SetAuthorizationStateResponse> {
    const response = await callUnary(() =>
      this.client.setAuthorizationState(
        toWireSetAuthorizationStateRequest(request),
      ),
    );
    return fromWireSetAuthorizationStateResponse(response);
  }

  async getActiveModelRef(): Promise<AuthorizationModelRef | undefined> {
    const response = fromWireGetActiveModelRefResponse(
      await callUnary(() => this.client.getActiveModelRef({})),
    );
    return response.model;
  }

  async getActiveModelRefRaw(): Promise<GetActiveModelRefResponse> {
    const response = await callUnary(() => this.client.getActiveModelRef({}));
    return fromWireGetActiveModelRefResponse(response);
  }

  async setActiveModel(
    model?: AuthorizationModel,
  ): Promise<AuthorizationModelRef | undefined> {
    const request: SetActiveModelRequest = {
      ...(model !== undefined ? { model } : {}),
    };
    const response = fromWireSetActiveModelResponse(
      await callUnary(() =>
        this.client.setActiveModel(toWireSetActiveModelRequest(request)),
      ),
    );
    return response.model;
  }

  async setActiveModelRaw(
    request: SetActiveModelRequest,
  ): Promise<SetActiveModelResponse> {
    const response = await callUnary(() =>
      this.client.setActiveModel(toWireSetActiveModelRequest(request)),
    );
    return fromWireSetActiveModelResponse(response);
  }

  async listActiveModelResourceTypes(
    pageSize: number,
    pageToken: string,
    filter?: AuthorizationModelResourceTypeFilter,
  ): Promise<ListActiveModelResourceTypesResponse> {
    const request: ListActiveModelResourceTypesRequest = {
      pageSize,
      pageToken,
      ...(filter !== undefined ? { filter } : {}),
    };
    const response = await callUnary(() =>
      this.client.listActiveModelResourceTypes(
        toWireListActiveModelResourceTypesRequest(request),
      ),
    );
    return fromWireListActiveModelResourceTypesResponse(response);
  }

  async listActiveModelResourceTypesRaw(
    request: ListActiveModelResourceTypesRequest,
  ): Promise<ListActiveModelResourceTypesResponse> {
    const response = await callUnary(() =>
      this.client.listActiveModelResourceTypes(
        toWireListActiveModelResourceTypesRequest(request),
      ),
    );
    return fromWireListActiveModelResourceTypesResponse(response);
  }
}
