// Code generated by sdkgen. DO NOT EDIT.

import { create } from "@bufbuild/protobuf";
import type { JsonValue } from "@bufbuild/protobuf";
import { EmptySchema, NullValue } from "@bufbuild/protobuf/wkt";
import { createClient } from "@connectrpc/connect";
import type { Client, Transport } from "@connectrpc/connect";

import {
  createHostServiceGrpcTransport,
  hostServiceMetadataInterceptors,
  parseHostServiceTarget,
  requireHostServiceTarget,
} from "./host-service.ts";

import * as wire from "./internal/gen/v1/datastore_pb.ts";
import { callUnary, fromWireStatus, fromWireTimestamp, fromWireValue, mapRecv, mapSend, toWireStatus, toWireTimestamp, toWireValue, type RpcStatus, type Unit } from "./rpc_support.ts";

export const CursorDirection = {
  CURSOR_NEXT: 0,
  CURSOR_NEXT_UNIQUE: 1,
  CURSOR_PREV: 2,
  CURSOR_PREV_UNIQUE: 3,
} as const;

export type CursorDirection = number;

export const TransactionDurabilityHint = {
  TRANSACTION_DURABILITY_DEFAULT: 0,
  TRANSACTION_DURABILITY_STRICT: 1,
  TRANSACTION_DURABILITY_RELAXED: 2,
} as const;

export type TransactionDurabilityHint = number;

export const TransactionMode = {
  TRANSACTION_READONLY: 0,
  TRANSACTION_READWRITE: 1,
} as const;

export type TransactionMode = number;

export interface BeginTransactionRequest {
  stores: string[];
  mode: TransactionMode;
  durabilityHint: TransactionDurabilityHint;
}

export interface ColumnDef {
  name: string;
  type: number;
  primaryKey: boolean;
  notNull: boolean;
  unique: boolean;
}

export interface CountResponse {
  count: bigint;
}

export interface CreateObjectStoreRequest {
  name: string;
  schema?: ObjectStoreSchema;
}

export type CursorClientMessageMsg =
  | { case: "open"; value: OpenCursorRequest }
  | { case: "command"; value: CursorCommand }
  | { case: undefined; value?: undefined };

export interface CursorClientMessage {
  msg: CursorClientMessageMsg;
}

export type CursorCommandCommand =
  | { case: "next"; value: boolean }
  | { case: "continueToKey"; value: CursorKeyTarget }
  | { case: "advance"; value: number }
  | { case: "update"; value: Record }
  | { case: "delete"; value: boolean }
  | { case: "close"; value: boolean }
  | { case: undefined; value?: undefined };

export interface CursorCommand {
  command: CursorCommandCommand;
}

export interface CursorEntry {
  key: KeyValue[];
  primaryKey: string;
  record?: Record;
}

export interface CursorKeyTarget {
  key: KeyValue[];
}

export type CursorResponseResult =
  | { case: "entry"; value: CursorEntry }
  | { case: "done"; value: boolean }
  | { case: undefined; value?: undefined };

export interface CursorResponse {
  result: CursorResponseResult;
}

export interface DeleteObjectStoreRequest {
  name: string;
}

export interface DeleteResponse {
  deleted: bigint;
}

export interface IndexQueryRequest {
  store: string;
  index: string;
  values: TypedValue[];
  range?: KeyRange;
}

export interface IndexSchema {
  name: string;
  keyPath: string[];
  unique: boolean;
}

export interface KeyRange {
  lower?: TypedValue;
  upper?: TypedValue;
  lowerOpen: boolean;
  upperOpen: boolean;
}

export interface KeyResponse {
  key: string;
}

export type KeyValueKind =
  | { case: "scalar"; value: TypedValue }
  | { case: "array"; value: KeyValueArray }
  | { case: undefined; value?: undefined };

export interface KeyValue {
  kind: KeyValueKind;
}

export interface KeyValueArray {
  elements: KeyValue[];
}

export interface KeysResponse {
  keys: string[];
}

export interface ObjectStoreNameRequest {
  store: string;
}

export interface ObjectStoreRangeRequest {
  store: string;
  range?: KeyRange;
}

export interface ObjectStoreRequest {
  store: string;
  id: string;
}

export interface ObjectStoreSchema {
  indexes: IndexSchema[];
  columns: ColumnDef[];
}

export interface OpenCursorRequest {
  store: string;
  range?: KeyRange;
  direction: CursorDirection;
  keysOnly: boolean;
  index: string;
  values: TypedValue[];
}

export interface Record {
  fields: { [key: string]: TypedValue };
}

export interface RecordRequest {
  store: string;
  record?: Record;
}

export interface RecordResponse {
  record?: Record;
}

export interface RecordsResponse {
  records: Record[];
}

export interface TransactionAbortRequest {
  reason: string;
}

export interface TransactionAbortResponse {
  error?: RpcStatus;
}

export interface TransactionBeginResponse {
}

export type TransactionClientMessageMsg =
  | { case: "begin"; value: BeginTransactionRequest }
  | { case: "operation"; value: TransactionOperation }
  | { case: "commit"; value: TransactionCommitRequest }
  | { case: "abort"; value: TransactionAbortRequest }
  | { case: undefined; value?: undefined };

export interface TransactionClientMessage {
  msg: TransactionClientMessageMsg;
}

export interface TransactionCommitRequest {
}

export interface TransactionCommitResponse {
  error?: RpcStatus;
}

export type TransactionOperationOperation =
  | { case: "get"; value: ObjectStoreRequest }
  | { case: "getKey"; value: ObjectStoreRequest }
  | { case: "add"; value: RecordRequest }
  | { case: "put"; value: RecordRequest }
  | { case: "delete"; value: ObjectStoreRequest }
  | { case: "clear"; value: ObjectStoreNameRequest }
  | { case: "getAll"; value: ObjectStoreRangeRequest }
  | { case: "getAllKeys"; value: ObjectStoreRangeRequest }
  | { case: "count"; value: ObjectStoreRangeRequest }
  | { case: "deleteRange"; value: ObjectStoreRangeRequest }
  | { case: "indexGet"; value: IndexQueryRequest }
  | { case: "indexGetKey"; value: IndexQueryRequest }
  | { case: "indexGetAll"; value: IndexQueryRequest }
  | { case: "indexGetAllKeys"; value: IndexQueryRequest }
  | { case: "indexCount"; value: IndexQueryRequest }
  | { case: "indexDelete"; value: IndexQueryRequest }
  | { case: undefined; value?: undefined };

export interface TransactionOperation {
  requestId: bigint;
  operation: TransactionOperationOperation;
}

export type TransactionOperationResponseResult =
  | { case: "empty"; value: Unit }
  | { case: "record"; value: RecordResponse }
  | { case: "records"; value: RecordsResponse }
  | { case: "key"; value: KeyResponse }
  | { case: "keys"; value: KeysResponse }
  | { case: "count"; value: CountResponse }
  | { case: "delete"; value: DeleteResponse }
  | { case: undefined; value?: undefined };

export interface TransactionOperationResponse {
  requestId: bigint;
  error?: RpcStatus;
  result: TransactionOperationResponseResult;
}

export type TransactionServerMessageMsg =
  | { case: "begin"; value: TransactionBeginResponse }
  | { case: "operation"; value: TransactionOperationResponse }
  | { case: "commit"; value: TransactionCommitResponse }
  | { case: "abort"; value: TransactionAbortResponse }
  | { case: undefined; value?: undefined };

export interface TransactionServerMessage {
  msg: TransactionServerMessageMsg;
}

export type TypedValueKind =
  | { case: "nullValue"; value: null }
  | { case: "stringValue"; value: string }
  | { case: "intValue"; value: bigint }
  | { case: "floatValue"; value: number }
  | { case: "boolValue"; value: boolean }
  | { case: "timeValue"; value: Date }
  | { case: "bytesValue"; value: Uint8Array }
  | { case: "jsonValue"; value: JsonValue }
  | { case: undefined; value?: undefined };

export interface TypedValue {
  kind: TypedValueKind;
}

export function toWireBeginTransactionRequest(value: BeginTransactionRequest): wire.BeginTransactionRequest {
  return create(wire.BeginTransactionRequestSchema, {
    stores: value.stores,
    mode: value.mode as wire.TransactionMode,
    durabilityHint: value.durabilityHint as wire.TransactionDurabilityHint,
  });
}

export function fromWireBeginTransactionRequest(value: wire.BeginTransactionRequest): BeginTransactionRequest {
  return {
    stores: value.stores,
    mode: value.mode,
    durabilityHint: value.durabilityHint,
  };
}

export function toWireColumnDef(value: ColumnDef): wire.ColumnDef {
  return create(wire.ColumnDefSchema, {
    name: value.name,
    type: value.type,
    primaryKey: value.primaryKey,
    notNull: value.notNull,
    unique: value.unique,
  });
}

export function fromWireColumnDef(value: wire.ColumnDef): ColumnDef {
  return {
    name: value.name,
    type: value.type,
    primaryKey: value.primaryKey,
    notNull: value.notNull,
    unique: value.unique,
  };
}

export function toWireCountResponse(value: CountResponse): wire.CountResponse {
  return create(wire.CountResponseSchema, {
    count: value.count,
  });
}

export function fromWireCountResponse(value: wire.CountResponse): CountResponse {
  return {
    count: value.count,
  };
}

export function toWireCreateObjectStoreRequest(value: CreateObjectStoreRequest): wire.CreateObjectStoreRequest {
  return create(wire.CreateObjectStoreRequestSchema, {
    name: value.name,
    ...(value.schema !== undefined ? { schema: toWireObjectStoreSchema(value.schema) } : {}),
  });
}

export function fromWireCreateObjectStoreRequest(value: wire.CreateObjectStoreRequest): CreateObjectStoreRequest {
  return {
    name: value.name,
    ...(value.schema !== undefined ? { schema: fromWireObjectStoreSchema(value.schema) } : {}),
  };
}

export function toWireCursorClientMessage(value: CursorClientMessage): wire.CursorClientMessage {
  return create(wire.CursorClientMessageSchema, {
    msg: toWireCursorClientMessageMsg(value.msg),
  });
}

export function fromWireCursorClientMessage(value: wire.CursorClientMessage): CursorClientMessage {
  return {
    msg: fromWireCursorClientMessageMsg(value.msg),
  };
}

function toWireCursorClientMessageMsg(value: CursorClientMessageMsg): wire.CursorClientMessage["msg"] {
  switch (value.case) {
    case "open":
      return { case: "open", value: toWireOpenCursorRequest(value.value) };
    case "command":
      return { case: "command", value: toWireCursorCommand(value.value) };
    default:
      return { case: undefined };
  }
}

function fromWireCursorClientMessageMsg(value: wire.CursorClientMessage["msg"]): CursorClientMessageMsg {
  switch (value.case) {
    case "open":
      return { case: "open", value: fromWireOpenCursorRequest(value.value) };
    case "command":
      return { case: "command", value: fromWireCursorCommand(value.value) };
    default:
      return { case: undefined };
  }
}

export function toWireCursorCommand(value: CursorCommand): wire.CursorCommand {
  return create(wire.CursorCommandSchema, {
    command: toWireCursorCommandCommand(value.command),
  });
}

export function fromWireCursorCommand(value: wire.CursorCommand): CursorCommand {
  return {
    command: fromWireCursorCommandCommand(value.command),
  };
}

function toWireCursorCommandCommand(value: CursorCommandCommand): wire.CursorCommand["command"] {
  switch (value.case) {
    case "next":
      return { case: "next", value: value.value };
    case "continueToKey":
      return { case: "continueToKey", value: toWireCursorKeyTarget(value.value) };
    case "advance":
      return { case: "advance", value: value.value };
    case "update":
      return { case: "update", value: toWireRecord(value.value) };
    case "delete":
      return { case: "delete", value: value.value };
    case "close":
      return { case: "close", value: value.value };
    default:
      return { case: undefined };
  }
}

function fromWireCursorCommandCommand(value: wire.CursorCommand["command"]): CursorCommandCommand {
  switch (value.case) {
    case "next":
      return { case: "next", value: value.value };
    case "continueToKey":
      return { case: "continueToKey", value: fromWireCursorKeyTarget(value.value) };
    case "advance":
      return { case: "advance", value: value.value };
    case "update":
      return { case: "update", value: fromWireRecord(value.value) };
    case "delete":
      return { case: "delete", value: value.value };
    case "close":
      return { case: "close", value: value.value };
    default:
      return { case: undefined };
  }
}

export function toWireCursorEntry(value: CursorEntry): wire.CursorEntry {
  return create(wire.CursorEntrySchema, {
    key: value.key.map(toWireKeyValue),
    primaryKey: value.primaryKey,
    ...(value.record !== undefined ? { record: toWireRecord(value.record) } : {}),
  });
}

export function fromWireCursorEntry(value: wire.CursorEntry): CursorEntry {
  return {
    key: value.key.map(fromWireKeyValue),
    primaryKey: value.primaryKey,
    ...(value.record !== undefined ? { record: fromWireRecord(value.record) } : {}),
  };
}

export function toWireCursorKeyTarget(value: CursorKeyTarget): wire.CursorKeyTarget {
  return create(wire.CursorKeyTargetSchema, {
    key: value.key.map(toWireKeyValue),
  });
}

export function fromWireCursorKeyTarget(value: wire.CursorKeyTarget): CursorKeyTarget {
  return {
    key: value.key.map(fromWireKeyValue),
  };
}

export function toWireCursorResponse(value: CursorResponse): wire.CursorResponse {
  return create(wire.CursorResponseSchema, {
    result: toWireCursorResponseResult(value.result),
  });
}

export function fromWireCursorResponse(value: wire.CursorResponse): CursorResponse {
  return {
    result: fromWireCursorResponseResult(value.result),
  };
}

function toWireCursorResponseResult(value: CursorResponseResult): wire.CursorResponse["result"] {
  switch (value.case) {
    case "entry":
      return { case: "entry", value: toWireCursorEntry(value.value) };
    case "done":
      return { case: "done", value: value.value };
    default:
      return { case: undefined };
  }
}

function fromWireCursorResponseResult(value: wire.CursorResponse["result"]): CursorResponseResult {
  switch (value.case) {
    case "entry":
      return { case: "entry", value: fromWireCursorEntry(value.value) };
    case "done":
      return { case: "done", value: value.value };
    default:
      return { case: undefined };
  }
}

export function toWireDeleteObjectStoreRequest(value: DeleteObjectStoreRequest): wire.DeleteObjectStoreRequest {
  return create(wire.DeleteObjectStoreRequestSchema, {
    name: value.name,
  });
}

export function fromWireDeleteObjectStoreRequest(value: wire.DeleteObjectStoreRequest): DeleteObjectStoreRequest {
  return {
    name: value.name,
  };
}

export function toWireDeleteResponse(value: DeleteResponse): wire.DeleteResponse {
  return create(wire.DeleteResponseSchema, {
    deleted: value.deleted,
  });
}

export function fromWireDeleteResponse(value: wire.DeleteResponse): DeleteResponse {
  return {
    deleted: value.deleted,
  };
}

export function toWireIndexQueryRequest(value: IndexQueryRequest): wire.IndexQueryRequest {
  return create(wire.IndexQueryRequestSchema, {
    store: value.store,
    index: value.index,
    values: value.values.map(toWireTypedValue),
    ...(value.range !== undefined ? { range: toWireKeyRange(value.range) } : {}),
  });
}

export function fromWireIndexQueryRequest(value: wire.IndexQueryRequest): IndexQueryRequest {
  return {
    store: value.store,
    index: value.index,
    values: value.values.map(fromWireTypedValue),
    ...(value.range !== undefined ? { range: fromWireKeyRange(value.range) } : {}),
  };
}

export function toWireIndexSchema(value: IndexSchema): wire.IndexSchema {
  return create(wire.IndexSchemaSchema, {
    name: value.name,
    keyPath: value.keyPath,
    unique: value.unique,
  });
}

export function fromWireIndexSchema(value: wire.IndexSchema): IndexSchema {
  return {
    name: value.name,
    keyPath: value.keyPath,
    unique: value.unique,
  };
}

export function toWireKeyRange(value: KeyRange): wire.KeyRange {
  return create(wire.KeyRangeSchema, {
    ...(value.lower !== undefined ? { lower: toWireTypedValue(value.lower) } : {}),
    ...(value.upper !== undefined ? { upper: toWireTypedValue(value.upper) } : {}),
    lowerOpen: value.lowerOpen,
    upperOpen: value.upperOpen,
  });
}

export function fromWireKeyRange(value: wire.KeyRange): KeyRange {
  return {
    ...(value.lower !== undefined ? { lower: fromWireTypedValue(value.lower) } : {}),
    ...(value.upper !== undefined ? { upper: fromWireTypedValue(value.upper) } : {}),
    lowerOpen: value.lowerOpen,
    upperOpen: value.upperOpen,
  };
}

export function toWireKeyResponse(value: KeyResponse): wire.KeyResponse {
  return create(wire.KeyResponseSchema, {
    key: value.key,
  });
}

export function fromWireKeyResponse(value: wire.KeyResponse): KeyResponse {
  return {
    key: value.key,
  };
}

export function toWireKeyValue(value: KeyValue): wire.KeyValue {
  return create(wire.KeyValueSchema, {
    kind: toWireKeyValueKind(value.kind),
  });
}

export function fromWireKeyValue(value: wire.KeyValue): KeyValue {
  return {
    kind: fromWireKeyValueKind(value.kind),
  };
}

function toWireKeyValueKind(value: KeyValueKind): wire.KeyValue["kind"] {
  switch (value.case) {
    case "scalar":
      return { case: "scalar", value: toWireTypedValue(value.value) };
    case "array":
      return { case: "array", value: toWireKeyValueArray(value.value) };
    default:
      return { case: undefined };
  }
}

function fromWireKeyValueKind(value: wire.KeyValue["kind"]): KeyValueKind {
  switch (value.case) {
    case "scalar":
      return { case: "scalar", value: fromWireTypedValue(value.value) };
    case "array":
      return { case: "array", value: fromWireKeyValueArray(value.value) };
    default:
      return { case: undefined };
  }
}

export function toWireKeyValueArray(value: KeyValueArray): wire.KeyValueArray {
  return create(wire.KeyValueArraySchema, {
    elements: value.elements.map(toWireKeyValue),
  });
}

export function fromWireKeyValueArray(value: wire.KeyValueArray): KeyValueArray {
  return {
    elements: value.elements.map(fromWireKeyValue),
  };
}

export function toWireKeysResponse(value: KeysResponse): wire.KeysResponse {
  return create(wire.KeysResponseSchema, {
    keys: value.keys,
  });
}

export function fromWireKeysResponse(value: wire.KeysResponse): KeysResponse {
  return {
    keys: value.keys,
  };
}

export function toWireObjectStoreNameRequest(value: ObjectStoreNameRequest): wire.ObjectStoreNameRequest {
  return create(wire.ObjectStoreNameRequestSchema, {
    store: value.store,
  });
}

export function fromWireObjectStoreNameRequest(value: wire.ObjectStoreNameRequest): ObjectStoreNameRequest {
  return {
    store: value.store,
  };
}

export function toWireObjectStoreRangeRequest(value: ObjectStoreRangeRequest): wire.ObjectStoreRangeRequest {
  return create(wire.ObjectStoreRangeRequestSchema, {
    store: value.store,
    ...(value.range !== undefined ? { range: toWireKeyRange(value.range) } : {}),
  });
}

export function fromWireObjectStoreRangeRequest(value: wire.ObjectStoreRangeRequest): ObjectStoreRangeRequest {
  return {
    store: value.store,
    ...(value.range !== undefined ? { range: fromWireKeyRange(value.range) } : {}),
  };
}

export function toWireObjectStoreRequest(value: ObjectStoreRequest): wire.ObjectStoreRequest {
  return create(wire.ObjectStoreRequestSchema, {
    store: value.store,
    id: value.id,
  });
}

export function fromWireObjectStoreRequest(value: wire.ObjectStoreRequest): ObjectStoreRequest {
  return {
    store: value.store,
    id: value.id,
  };
}

export function toWireObjectStoreSchema(value: ObjectStoreSchema): wire.ObjectStoreSchema {
  return create(wire.ObjectStoreSchemaSchema, {
    indexes: value.indexes.map(toWireIndexSchema),
    columns: value.columns.map(toWireColumnDef),
  });
}

export function fromWireObjectStoreSchema(value: wire.ObjectStoreSchema): ObjectStoreSchema {
  return {
    indexes: value.indexes.map(fromWireIndexSchema),
    columns: value.columns.map(fromWireColumnDef),
  };
}

export function toWireOpenCursorRequest(value: OpenCursorRequest): wire.OpenCursorRequest {
  return create(wire.OpenCursorRequestSchema, {
    store: value.store,
    ...(value.range !== undefined ? { range: toWireKeyRange(value.range) } : {}),
    direction: value.direction as wire.CursorDirection,
    keysOnly: value.keysOnly,
    index: value.index,
    values: value.values.map(toWireTypedValue),
  });
}

export function fromWireOpenCursorRequest(value: wire.OpenCursorRequest): OpenCursorRequest {
  return {
    store: value.store,
    ...(value.range !== undefined ? { range: fromWireKeyRange(value.range) } : {}),
    direction: value.direction,
    keysOnly: value.keysOnly,
    index: value.index,
    values: value.values.map(fromWireTypedValue),
  };
}

export function toWireRecord(value: Record): wire.Record {
  return create(wire.RecordSchema, {
    fields: Object.fromEntries(Object.entries(value.fields).map(([key, item]) => [key, toWireTypedValue(item)])),
  });
}

export function fromWireRecord(value: wire.Record): Record {
  return {
    fields: Object.fromEntries(Object.entries(value.fields).map(([key, item]) => [key, fromWireTypedValue(item)])),
  };
}

export function toWireRecordRequest(value: RecordRequest): wire.RecordRequest {
  return create(wire.RecordRequestSchema, {
    store: value.store,
    ...(value.record !== undefined ? { record: toWireRecord(value.record) } : {}),
  });
}

export function fromWireRecordRequest(value: wire.RecordRequest): RecordRequest {
  return {
    store: value.store,
    ...(value.record !== undefined ? { record: fromWireRecord(value.record) } : {}),
  };
}

export function toWireRecordResponse(value: RecordResponse): wire.RecordResponse {
  return create(wire.RecordResponseSchema, {
    ...(value.record !== undefined ? { record: toWireRecord(value.record) } : {}),
  });
}

export function fromWireRecordResponse(value: wire.RecordResponse): RecordResponse {
  return {
    ...(value.record !== undefined ? { record: fromWireRecord(value.record) } : {}),
  };
}

export function toWireRecordsResponse(value: RecordsResponse): wire.RecordsResponse {
  return create(wire.RecordsResponseSchema, {
    records: value.records.map(toWireRecord),
  });
}

export function fromWireRecordsResponse(value: wire.RecordsResponse): RecordsResponse {
  return {
    records: value.records.map(fromWireRecord),
  };
}

export function toWireTransactionAbortRequest(value: TransactionAbortRequest): wire.TransactionAbortRequest {
  return create(wire.TransactionAbortRequestSchema, {
    reason: value.reason,
  });
}

export function fromWireTransactionAbortRequest(value: wire.TransactionAbortRequest): TransactionAbortRequest {
  return {
    reason: value.reason,
  };
}

export function toWireTransactionAbortResponse(value: TransactionAbortResponse): wire.TransactionAbortResponse {
  return create(wire.TransactionAbortResponseSchema, {
    ...(value.error !== undefined ? { error: toWireStatus(value.error) } : {}),
  });
}

export function fromWireTransactionAbortResponse(value: wire.TransactionAbortResponse): TransactionAbortResponse {
  return {
    ...(value.error !== undefined ? { error: fromWireStatus(value.error) } : {}),
  };
}

export function toWireTransactionBeginResponse(value: TransactionBeginResponse): wire.TransactionBeginResponse {
  return create(wire.TransactionBeginResponseSchema, {
  });
}

export function fromWireTransactionBeginResponse(value: wire.TransactionBeginResponse): TransactionBeginResponse {
  return {
  };
}

export function toWireTransactionClientMessage(value: TransactionClientMessage): wire.TransactionClientMessage {
  return create(wire.TransactionClientMessageSchema, {
    msg: toWireTransactionClientMessageMsg(value.msg),
  });
}

export function fromWireTransactionClientMessage(value: wire.TransactionClientMessage): TransactionClientMessage {
  return {
    msg: fromWireTransactionClientMessageMsg(value.msg),
  };
}

function toWireTransactionClientMessageMsg(value: TransactionClientMessageMsg): wire.TransactionClientMessage["msg"] {
  switch (value.case) {
    case "begin":
      return { case: "begin", value: toWireBeginTransactionRequest(value.value) };
    case "operation":
      return { case: "operation", value: toWireTransactionOperation(value.value) };
    case "commit":
      return { case: "commit", value: toWireTransactionCommitRequest(value.value) };
    case "abort":
      return { case: "abort", value: toWireTransactionAbortRequest(value.value) };
    default:
      return { case: undefined };
  }
}

function fromWireTransactionClientMessageMsg(value: wire.TransactionClientMessage["msg"]): TransactionClientMessageMsg {
  switch (value.case) {
    case "begin":
      return { case: "begin", value: fromWireBeginTransactionRequest(value.value) };
    case "operation":
      return { case: "operation", value: fromWireTransactionOperation(value.value) };
    case "commit":
      return { case: "commit", value: fromWireTransactionCommitRequest(value.value) };
    case "abort":
      return { case: "abort", value: fromWireTransactionAbortRequest(value.value) };
    default:
      return { case: undefined };
  }
}

export function toWireTransactionCommitRequest(value: TransactionCommitRequest): wire.TransactionCommitRequest {
  return create(wire.TransactionCommitRequestSchema, {
  });
}

export function fromWireTransactionCommitRequest(value: wire.TransactionCommitRequest): TransactionCommitRequest {
  return {
  };
}

export function toWireTransactionCommitResponse(value: TransactionCommitResponse): wire.TransactionCommitResponse {
  return create(wire.TransactionCommitResponseSchema, {
    ...(value.error !== undefined ? { error: toWireStatus(value.error) } : {}),
  });
}

export function fromWireTransactionCommitResponse(value: wire.TransactionCommitResponse): TransactionCommitResponse {
  return {
    ...(value.error !== undefined ? { error: fromWireStatus(value.error) } : {}),
  };
}

export function toWireTransactionOperation(value: TransactionOperation): wire.TransactionOperation {
  return create(wire.TransactionOperationSchema, {
    requestId: value.requestId,
    operation: toWireTransactionOperationOperation(value.operation),
  });
}

export function fromWireTransactionOperation(value: wire.TransactionOperation): TransactionOperation {
  return {
    requestId: value.requestId,
    operation: fromWireTransactionOperationOperation(value.operation),
  };
}

function toWireTransactionOperationOperation(value: TransactionOperationOperation): wire.TransactionOperation["operation"] {
  switch (value.case) {
    case "get":
      return { case: "get", value: toWireObjectStoreRequest(value.value) };
    case "getKey":
      return { case: "getKey", value: toWireObjectStoreRequest(value.value) };
    case "add":
      return { case: "add", value: toWireRecordRequest(value.value) };
    case "put":
      return { case: "put", value: toWireRecordRequest(value.value) };
    case "delete":
      return { case: "delete", value: toWireObjectStoreRequest(value.value) };
    case "clear":
      return { case: "clear", value: toWireObjectStoreNameRequest(value.value) };
    case "getAll":
      return { case: "getAll", value: toWireObjectStoreRangeRequest(value.value) };
    case "getAllKeys":
      return { case: "getAllKeys", value: toWireObjectStoreRangeRequest(value.value) };
    case "count":
      return { case: "count", value: toWireObjectStoreRangeRequest(value.value) };
    case "deleteRange":
      return { case: "deleteRange", value: toWireObjectStoreRangeRequest(value.value) };
    case "indexGet":
      return { case: "indexGet", value: toWireIndexQueryRequest(value.value) };
    case "indexGetKey":
      return { case: "indexGetKey", value: toWireIndexQueryRequest(value.value) };
    case "indexGetAll":
      return { case: "indexGetAll", value: toWireIndexQueryRequest(value.value) };
    case "indexGetAllKeys":
      return { case: "indexGetAllKeys", value: toWireIndexQueryRequest(value.value) };
    case "indexCount":
      return { case: "indexCount", value: toWireIndexQueryRequest(value.value) };
    case "indexDelete":
      return { case: "indexDelete", value: toWireIndexQueryRequest(value.value) };
    default:
      return { case: undefined };
  }
}

function fromWireTransactionOperationOperation(value: wire.TransactionOperation["operation"]): TransactionOperationOperation {
  switch (value.case) {
    case "get":
      return { case: "get", value: fromWireObjectStoreRequest(value.value) };
    case "getKey":
      return { case: "getKey", value: fromWireObjectStoreRequest(value.value) };
    case "add":
      return { case: "add", value: fromWireRecordRequest(value.value) };
    case "put":
      return { case: "put", value: fromWireRecordRequest(value.value) };
    case "delete":
      return { case: "delete", value: fromWireObjectStoreRequest(value.value) };
    case "clear":
      return { case: "clear", value: fromWireObjectStoreNameRequest(value.value) };
    case "getAll":
      return { case: "getAll", value: fromWireObjectStoreRangeRequest(value.value) };
    case "getAllKeys":
      return { case: "getAllKeys", value: fromWireObjectStoreRangeRequest(value.value) };
    case "count":
      return { case: "count", value: fromWireObjectStoreRangeRequest(value.value) };
    case "deleteRange":
      return { case: "deleteRange", value: fromWireObjectStoreRangeRequest(value.value) };
    case "indexGet":
      return { case: "indexGet", value: fromWireIndexQueryRequest(value.value) };
    case "indexGetKey":
      return { case: "indexGetKey", value: fromWireIndexQueryRequest(value.value) };
    case "indexGetAll":
      return { case: "indexGetAll", value: fromWireIndexQueryRequest(value.value) };
    case "indexGetAllKeys":
      return { case: "indexGetAllKeys", value: fromWireIndexQueryRequest(value.value) };
    case "indexCount":
      return { case: "indexCount", value: fromWireIndexQueryRequest(value.value) };
    case "indexDelete":
      return { case: "indexDelete", value: fromWireIndexQueryRequest(value.value) };
    default:
      return { case: undefined };
  }
}

export function toWireTransactionOperationResponse(value: TransactionOperationResponse): wire.TransactionOperationResponse {
  return create(wire.TransactionOperationResponseSchema, {
    requestId: value.requestId,
    ...(value.error !== undefined ? { error: toWireStatus(value.error) } : {}),
    result: toWireTransactionOperationResponseResult(value.result),
  });
}

export function fromWireTransactionOperationResponse(value: wire.TransactionOperationResponse): TransactionOperationResponse {
  return {
    requestId: value.requestId,
    ...(value.error !== undefined ? { error: fromWireStatus(value.error) } : {}),
    result: fromWireTransactionOperationResponseResult(value.result),
  };
}

function toWireTransactionOperationResponseResult(value: TransactionOperationResponseResult): wire.TransactionOperationResponse["result"] {
  switch (value.case) {
    case "empty":
      return { case: "empty", value: create(EmptySchema) };
    case "record":
      return { case: "record", value: toWireRecordResponse(value.value) };
    case "records":
      return { case: "records", value: toWireRecordsResponse(value.value) };
    case "key":
      return { case: "key", value: toWireKeyResponse(value.value) };
    case "keys":
      return { case: "keys", value: toWireKeysResponse(value.value) };
    case "count":
      return { case: "count", value: toWireCountResponse(value.value) };
    case "delete":
      return { case: "delete", value: toWireDeleteResponse(value.value) };
    default:
      return { case: undefined };
  }
}

function fromWireTransactionOperationResponseResult(value: wire.TransactionOperationResponse["result"]): TransactionOperationResponseResult {
  switch (value.case) {
    case "empty":
      return { case: "empty", value: {} };
    case "record":
      return { case: "record", value: fromWireRecordResponse(value.value) };
    case "records":
      return { case: "records", value: fromWireRecordsResponse(value.value) };
    case "key":
      return { case: "key", value: fromWireKeyResponse(value.value) };
    case "keys":
      return { case: "keys", value: fromWireKeysResponse(value.value) };
    case "count":
      return { case: "count", value: fromWireCountResponse(value.value) };
    case "delete":
      return { case: "delete", value: fromWireDeleteResponse(value.value) };
    default:
      return { case: undefined };
  }
}

export function toWireTransactionServerMessage(value: TransactionServerMessage): wire.TransactionServerMessage {
  return create(wire.TransactionServerMessageSchema, {
    msg: toWireTransactionServerMessageMsg(value.msg),
  });
}

export function fromWireTransactionServerMessage(value: wire.TransactionServerMessage): TransactionServerMessage {
  return {
    msg: fromWireTransactionServerMessageMsg(value.msg),
  };
}

function toWireTransactionServerMessageMsg(value: TransactionServerMessageMsg): wire.TransactionServerMessage["msg"] {
  switch (value.case) {
    case "begin":
      return { case: "begin", value: toWireTransactionBeginResponse(value.value) };
    case "operation":
      return { case: "operation", value: toWireTransactionOperationResponse(value.value) };
    case "commit":
      return { case: "commit", value: toWireTransactionCommitResponse(value.value) };
    case "abort":
      return { case: "abort", value: toWireTransactionAbortResponse(value.value) };
    default:
      return { case: undefined };
  }
}

function fromWireTransactionServerMessageMsg(value: wire.TransactionServerMessage["msg"]): TransactionServerMessageMsg {
  switch (value.case) {
    case "begin":
      return { case: "begin", value: fromWireTransactionBeginResponse(value.value) };
    case "operation":
      return { case: "operation", value: fromWireTransactionOperationResponse(value.value) };
    case "commit":
      return { case: "commit", value: fromWireTransactionCommitResponse(value.value) };
    case "abort":
      return { case: "abort", value: fromWireTransactionAbortResponse(value.value) };
    default:
      return { case: undefined };
  }
}

export function toWireTypedValue(value: TypedValue): wire.TypedValue {
  return create(wire.TypedValueSchema, {
    kind: toWireTypedValueKind(value.kind),
  });
}

export function fromWireTypedValue(value: wire.TypedValue): TypedValue {
  return {
    kind: fromWireTypedValueKind(value.kind),
  };
}

function toWireTypedValueKind(value: TypedValueKind): wire.TypedValue["kind"] {
  switch (value.case) {
    case "nullValue":
      return { case: "nullValue", value: NullValue.NULL_VALUE };
    case "stringValue":
      return { case: "stringValue", value: value.value };
    case "intValue":
      return { case: "intValue", value: value.value };
    case "floatValue":
      return { case: "floatValue", value: value.value };
    case "boolValue":
      return { case: "boolValue", value: value.value };
    case "timeValue":
      return { case: "timeValue", value: toWireTimestamp(value.value) };
    case "bytesValue":
      return { case: "bytesValue", value: value.value };
    case "jsonValue":
      return { case: "jsonValue", value: toWireValue(value.value) };
    default:
      return { case: undefined };
  }
}

function fromWireTypedValueKind(value: wire.TypedValue["kind"]): TypedValueKind {
  switch (value.case) {
    case "nullValue":
      return { case: "nullValue", value: null };
    case "stringValue":
      return { case: "stringValue", value: value.value };
    case "intValue":
      return { case: "intValue", value: value.value };
    case "floatValue":
      return { case: "floatValue", value: value.value };
    case "boolValue":
      return { case: "boolValue", value: value.value };
    case "timeValue":
      return { case: "timeValue", value: fromWireTimestamp(value.value) };
    case "bytesValue":
      return { case: "bytesValue", value: value.value };
    case "jsonValue":
      return { case: "jsonValue", value: fromWireValue(value.value) };
    default:
      return { case: undefined };
  }
}

export class IndexedDB {
  private readonly client: Client<typeof wire.IndexedDB>;

  constructor(transport: Transport) {
    this.client = createClient(wire.IndexedDB, transport);
  }

  static connect(name?: string): IndexedDB {
    const { target, token } = requireHostServiceTarget("IndexedDB");
    const transport = createHostServiceGrpcTransport(
      parseHostServiceTarget("IndexedDB", target),
      hostServiceMetadataInterceptors(token, name?.trim() ?? ""),
    );
    return new IndexedDB(transport);
  }

  async createObjectStore(request: CreateObjectStoreRequest): Promise<void> {
    await callUnary(() => this.client.createObjectStore(toWireCreateObjectStoreRequest(request)));
  }

  async deleteObjectStore(request: DeleteObjectStoreRequest): Promise<void> {
    await callUnary(() => this.client.deleteObjectStore(toWireDeleteObjectStoreRequest(request)));
  }

  async get(request: ObjectStoreRequest): Promise<RecordResponse> {
    const response = await callUnary(() => this.client.get(toWireObjectStoreRequest(request)));
    return fromWireRecordResponse(response);
  }

  async getKey(request: ObjectStoreRequest): Promise<KeyResponse> {
    const response = await callUnary(() => this.client.getKey(toWireObjectStoreRequest(request)));
    return fromWireKeyResponse(response);
  }

  async add(request: RecordRequest): Promise<void> {
    await callUnary(() => this.client.add(toWireRecordRequest(request)));
  }

  async put(request: RecordRequest): Promise<void> {
    await callUnary(() => this.client.put(toWireRecordRequest(request)));
  }

  async delete(request: ObjectStoreRequest): Promise<void> {
    await callUnary(() => this.client.delete(toWireObjectStoreRequest(request)));
  }

  async clear(request: ObjectStoreNameRequest): Promise<void> {
    await callUnary(() => this.client.clear(toWireObjectStoreNameRequest(request)));
  }

  async getAll(request: ObjectStoreRangeRequest): Promise<RecordsResponse> {
    const response = await callUnary(() => this.client.getAll(toWireObjectStoreRangeRequest(request)));
    return fromWireRecordsResponse(response);
  }

  async getAllKeys(request: ObjectStoreRangeRequest): Promise<KeysResponse> {
    const response = await callUnary(() => this.client.getAllKeys(toWireObjectStoreRangeRequest(request)));
    return fromWireKeysResponse(response);
  }

  async count(request: ObjectStoreRangeRequest): Promise<CountResponse> {
    const response = await callUnary(() => this.client.count(toWireObjectStoreRangeRequest(request)));
    return fromWireCountResponse(response);
  }

  async deleteRange(request: ObjectStoreRangeRequest): Promise<DeleteResponse> {
    const response = await callUnary(() => this.client.deleteRange(toWireObjectStoreRangeRequest(request)));
    return fromWireDeleteResponse(response);
  }

  async indexGet(request: IndexQueryRequest): Promise<RecordResponse> {
    const response = await callUnary(() => this.client.indexGet(toWireIndexQueryRequest(request)));
    return fromWireRecordResponse(response);
  }

  async indexGetKey(request: IndexQueryRequest): Promise<KeyResponse> {
    const response = await callUnary(() => this.client.indexGetKey(toWireIndexQueryRequest(request)));
    return fromWireKeyResponse(response);
  }

  async indexGetAll(request: IndexQueryRequest): Promise<RecordsResponse> {
    const response = await callUnary(() => this.client.indexGetAll(toWireIndexQueryRequest(request)));
    return fromWireRecordsResponse(response);
  }

  async indexGetAllKeys(request: IndexQueryRequest): Promise<KeysResponse> {
    const response = await callUnary(() => this.client.indexGetAllKeys(toWireIndexQueryRequest(request)));
    return fromWireKeysResponse(response);
  }

  async indexCount(request: IndexQueryRequest): Promise<CountResponse> {
    const response = await callUnary(() => this.client.indexCount(toWireIndexQueryRequest(request)));
    return fromWireCountResponse(response);
  }

  async indexDelete(request: IndexQueryRequest): Promise<DeleteResponse> {
    const response = await callUnary(() => this.client.indexDelete(toWireIndexQueryRequest(request)));
    return fromWireDeleteResponse(response);
  }

  openCursor(requests: AsyncIterable<CursorClientMessage>): AsyncIterable<CursorResponse> {
    return mapRecv(this.client.openCursor(mapSend(requests, toWireCursorClientMessage)), fromWireCursorResponse);
  }

  transaction(requests: AsyncIterable<TransactionClientMessage>): AsyncIterable<TransactionServerMessage> {
    return mapRecv(this.client.transaction(mapSend(requests, toWireTransactionClientMessage)), fromWireTransactionServerMessage);
  }

}
