/**
 * @packageDocumentation
 *
 * Authored TypeScript APIs for building Gestalt providers, helper CLIs, and
 * runtime adapters.
 *
 * @example
 * ```ts
 * import { defineApp, ok, operation, s } from "@valon-technologies/gestalt";
 *
 * export const app = defineApp({
 *   displayName: "Example Provider",
 *   operations: [
 *     operation({
 *       id: "hello",
 *       input: s.object({ name: s.string({ default: "World" }) }),
 *       output: s.object({ message: s.string() }),
 *       async handler(input) {
 *         return ok({ message: `Hello, ${input.name}` });
 *       },
 *     }),
 *   ],
 * });
 * ```
 *
 * @example
 * ```ts
 * import { parseRuntimeArgs, serve } from "@valon-technologies/gestalt/runtime";
 * ```
 */
export {
  Authorization,
  AuthorizationProvider,
  AUTHORIZATION_SUBJECT_TYPE_SUBJECT,
  authorizationAction,
  createAuthorizationProviderService,
  defineAuthorizationProvider,
  authorizationRelationship,
  authorizationRelationshipKeyWithTarget,
  authorizationRelationshipKey,
  authorizationRelationshipWithTarget,
  authorizationResource,
  authorizationResourceTarget,
  authorizationSubject,
  authorizationSubjectSet,
  authorizationSubjectSetTarget,
  authorizationSubjectTarget,
  isAuthorizationProvider,
  type AuthorizationAction,
  type AuthorizationActionSearch,
  type AuthorizationDecision,
  type AuthorizationEvaluateInput,
  type AuthorizationEvaluateManyInput,
  type AuthorizationEvaluationsResponse,
  type AuthorizationEffectiveSearchSubjectsInput,
  type AuthorizationEffectiveSubjectSearch,
  type AuthorizationExpandInput,
  type AuthorizationExpand,
  type AuthorizationExpandNode,
  type AuthorizationGetActiveModel,
  type AuthorizationListModelsInput,
  type AuthorizationListModels,
  type AuthorizationMetadata,
  type AuthorizationModel,
  type AuthorizationModelAction,
  type AuthorizationModelAllowedTarget,
  type AuthorizationModelAllowedTargetKind,
  type AuthorizationModelComputedUserset,
  type AuthorizationModelRef,
  type AuthorizationModelRelation,
  type AuthorizationModelResourceType,
  type AuthorizationModelRewrite,
  type AuthorizationModelRewriteKind,
  type AuthorizationModelRewriteThis,
  type AuthorizationModelRewriteUnion,
  type AuthorizationModelSubjectSetTarget,
  type AuthorizationModelTupleToUserset,
  type AuthorizationProviderOptions,
  type AuthorizationReadRelationshipsInput,
  type AuthorizationReadRelationships,
  type AuthorizationRelationship,
  type AuthorizationRelationshipKey,
  type AuthorizationRelationshipTarget,
  type AuthorizationRelationshipTargetKind,
  type AuthorizationResource,
  type AuthorizationSubjectSet,
  type AuthorizationResourceSearch,
  type AuthorizationSearchActionsInput,
  type AuthorizationSearchResourcesInput,
  type AuthorizationSearchSubjectsInput,
  type AuthorizationSubject,
  type AuthorizationSubjectSearch,
  type AuthorizationWriteRelationshipsInput,
  type AuthorizationWriteModelInput,
} from "./authorization.ts";
export {
  connectionParam,
  ok,
  response,
  responseBrand,
  request,
  type Access,
  type Host,
  type MaybePromise,
  type Credential,
  type ExternalIdentity,
  type OperationResult,
  type Request,
  type Response,
  type Subject,
  type SubjectInput,
} from "./api.ts";
export { type JsonObject, type JsonValue } from "./protocol.ts";
export {
  type HTTPSubjectRequest,
  type HTTPSubjectResolutionContext,
  HTTPSubjectResolutionError,
  type HTTPSubjectResolver,
  httpSubjectError,
} from "./http-subject.ts";
export {
  catalogToJson,
  catalogToYaml,
  schemaToCatalogSchema,
  schemaToParameters,
  writeCatalogYaml,
  type Catalog,
  type CatalogOperation,
  type CatalogParameter,
  type CatalogSchema,
  type OperationAnnotations,
} from "./catalog.ts";
export {
  buildProviderBinary,
  bunBuildCommand,
  bunTarget,
  parseBuildArgs,
} from "./build.ts";
export {
  App,
  type AppGraphQLInvokeOptions,
  type AppInvocationGrant,
  type AppInvokeOptions,
} from "./app-access.ts";
export {
  Agent,
  type AgentCancelTurn,
  type AgentCreateSession,
  type AgentCreateTurn,
  type AgentGetSession,
  type AgentGetTurn,
  type AgentListInteractions,
  type AgentListSessions,
  type AgentListTurnEvents,
  type AgentListTurns,
  type AgentResolveInteraction,
  type AgentUpdateSession,
  type AgentWorkspace,
  type AgentWorkspaceGitCheckout,
} from "./agent-access.ts";
export {
  Workflow,
  type WorkflowCreateDefinition,
  type WorkflowCreateTrigger,
  type WorkflowCreateSchedule,
  type WorkflowDeleteDefinition,
  type WorkflowDeleteTrigger,
  type WorkflowDeleteSchedule,
  type WorkflowGetDefinition,
  type WorkflowGetTrigger,
  type WorkflowGetSchedule,
  type WorkflowPauseTrigger,
  type WorkflowPauseSchedule,
  type WorkflowPublishEvent,
  type WorkflowResumeTrigger,
  type WorkflowResumeSchedule,
  type WorkflowSignalOrStartRun,
  type WorkflowSignalRun,
  type WorkflowStartRun,
  type WorkflowUpdateDefinition,
  type WorkflowUpdateTrigger,
  type WorkflowUpdateSchedule,
} from "./workflow-access.ts";
export {
  ENV_RUNTIME_SESSION_ID,
  RuntimeLogHost,
  type RuntimeLogAppendInput,
  type RuntimeLogAppendLogsInput,
  type RuntimeLogAppendResponse,
  type RuntimeLogStreamInput,
  type RuntimeLogStreamName,
  type RuntimeLogWriterOptions,
} from "./runtime-log-host.ts";
export {
  AuthenticationProvider,
  defineAuthenticationProvider,
  isAuthenticationProvider,
  type AuthenticatedUser,
  type AuthenticationProviderOptions,
  type AuthenticationSessionSettings,
  type BeginLoginRequest,
  type BeginLoginResponse,
  type CompleteLoginRequest,
} from "./auth.ts";
export {
  Cache,
  CacheProvider,
  defineCacheProvider,
  isCacheProvider,
  type CacheEntry,
  type CacheProviderOptions,
  type CacheSetOptions,
} from "./cache.ts";
export {
  ENV_HOST_SERVICE_SOCKET,
  ENV_HOST_SERVICE_TOKEN,
  HOST_SERVICE_BINDING_HEADER,
  HOST_SERVICE_RELAY_TOKEN_HEADER,
} from "./host-service.ts";
export {
  defineSecretsProvider,
  isSecretsProvider,
  type SecretsProviderOptions,
} from "./secrets.ts";
export {
  type ConnectedToken,
  AppProvider,
  defineApp,
  isAppProvider,
  operation,
  type ConnectionMode,
  type ConnectionParamDefinition,
  type OperationDefinition,
  type OperationOptions,
  type PostConnectHandler,
  type AppDefinitionOptions,
  type SessionCatalog,
  type SessionCatalogHandler,
} from "./app.ts";
export {
  ProviderBase,
  isProviderBase,
  slugName,
  type CloseHandler,
  type ConfigureHandler,
  type HealthCheckHandler,
  type ProviderKind,
  type ProviderMetadata,
  type ProviderBaseOptions,
  type StartHandler,
  type WarningsHandler,
} from "./provider.ts";
export {
  RuntimeEgressMode,
  RuntimeProvider,
  createRuntimeProviderService,
  defineRuntimeProvider,
  isRuntimeProvider,
  type GetRuntimeSessionRequest,
  type HostedApp,
  type ListRuntimeSessionsRequest,
  type RuntimeAgentWorkspace,
  type RuntimeAgentWorkspaceGitCheckout,
  type RuntimeImagePullAuth,
  type RuntimePreparedAgentWorkspace,
  type RuntimeProviderOptions,
  type RuntimeSession,
  type RuntimeSessionLifecycle,
  type RuntimeSupport,
  type PrepareRuntimeWorkspaceRequest,
  type PrepareRuntimeWorkspaceResponse,
  type RemoveRuntimeWorkspaceRequest,
  type StartHostedAppRequest,
  type StartRuntimeSessionRequest,
  type StopRuntimeSessionRequest,
} from "./runtime-provider.ts";
export {
  array,
  boolean,
  type InferSchema,
  integer,
  number,
  object,
  optional,
  s,
  string,
  type Schema,
  type SchemaOptions,
} from "./schema.ts";
export {
  CURRENT_PROTOCOL_VERSION,
  ENV_PROVIDER_PARENT_PID,
  ENV_PROVIDER_SOCKET,
  ENV_WRITE_CATALOG,
  createAuthenticationService,
  createCacheService,
  createSecretsService,
  createProviderService,
  createRuntimeService,
  loadProviderFromTarget,
  main as runtimeMain,
  parseRuntimeArgs,
  runBundledProvider,
  runLoadedProvider,
  serve,
} from "./runtime.ts";
export {
  defaultProviderName,
  formatModuleTarget,
  formatProviderTarget,
  parseModuleTarget,
  parseProviderTarget,
  readPackageConfig,
  readPackageProviderTarget,
  resolveProviderImportUrl,
  resolveProviderModulePath,
  type ModuleTarget,
  type PackageConfig,
  type ProviderTarget,
} from "./target.ts";
export {
  IndexedDB,
  CursorDirection,
  NotFoundError,
  AlreadyExistsError,
  TransactionError,
  IndexedDBCursorSnapshot,
  ColumnType,
  compareIndexedDBValues,
  indexedDBRangeBounds,
  newIndexedDBCursorSnapshot,
  type ObjectStore,
  type Index,
  type Transaction,
  type TransactionObjectStore,
  type TransactionIndex,
  type Cursor,
  type Record,
  type KeyRange,
  type IndexedDBCursorSnapshotEntry,
  type IndexedDBOpenCursorRequest,
  type TransactionMode,
  type TransactionDurabilityHint,
  type TransactionOptions,
  type ColumnSchema,
  type IndexSchema,
  type ObjectStoreSchema,
  type OpenCursorOptions,
} from "./indexeddb.ts";
export {
  S3,
  S3Provider,
  S3InvalidRangeError,
  S3NotFoundError,
  S3PreconditionFailedError,
  PresignMethod,
  createS3Service,
  defineS3Provider,
  isS3Provider,
  type S3Object,
  type ByteRange,
  type CopyOptions,
  type ListOptions,
  type ListPage,
  type ObjectAccessURL,
  type ObjectAccessURLOptions,
  type ObjectMeta,
  type ObjectRef,
  type PresignOptions,
  type PresignResult,
  type ProviderReadResult,
  type ReadOptions,
  type ReadResult,
  type S3BodySource,
  type S3ProviderOptions,
  type WriteOptions,
} from "./s3.ts";
export {
  AgentHost,
  AgentExecutionStatus,
  AgentInteractionState,
  AgentInteractionType,
  AgentMessagePartType,
  AgentProvider,
  AgentSessionState,
  AgentToolSourceMode,
  createAgentProviderService,
  defineAgentProvider,
  isAgentProvider,
  type AgentActor,
  type AgentHostExecuteToolInput,
  type AgentHostListToolsInput,
  type AgentHostResolveConnectionInput,
  type AgentInteraction,
  type AgentMessage,
  type AgentMessagePart,
  type AgentMessagePartImageRef,
  type AgentMessagePartToolCall,
  type AgentMessagePartToolResult,
  type AgentPreparedWorkspace,
  type AgentProviderCapabilities,
  type AgentProviderOptions,
  type AgentSession,
  type AgentSessionStartConfig,
  type AgentSessionStartHook,
  type AgentSessionStartHookOutput,
  type AgentToolAnnotations,
  type AgentToolRef,
  type AgentTurn,
  type AgentTurnDisplay,
  type AgentTurnEvent,
  type CancelAgentProviderTurnRequest,
  type CreateAgentProviderSessionRequest,
  type CreateAgentProviderTurnRequest,
  type ExecuteAgentToolRequest,
  type ExecuteAgentToolResponse,
  type GetAgentProviderCapabilitiesRequest,
  type GetAgentProviderInteractionRequest,
  type GetAgentProviderSessionRequest,
  type GetAgentProviderTurnRequest,
  type ListAgentToolsRequest,
  type ListAgentToolsResponse,
  type ListAgentProviderInteractionsRequest,
  type ListAgentProviderInteractionsResponse,
  type ListAgentProviderSessionsRequest,
  type ListAgentProviderSessionsResponse,
  type ListAgentProviderTurnEventsRequest,
  type ListAgentProviderTurnEventsResponse,
  type ListAgentProviderTurnsRequest,
  type ListAgentProviderTurnsResponse,
  type ListedAgentTool,
  type ResolveAgentConnectionRequest,
  type ResolveAgentProviderInteractionRequest,
  type ResolvedAgentConnection,
  type ResolvedAgentTool,
  type UpdateAgentProviderSessionRequest,
} from "./agent.ts";
export {
  WorkflowProvider,
  WorkflowRunStatus,
  boundWorkflowDefinition,
  boundWorkflowDefinitionFromDefinition,
  boundWorkflowDefinitionInputFromDefinition,
  boundWorkflowEventTrigger,
  boundWorkflowEventTriggerFromTrigger,
  boundWorkflowEventTriggerInputFromTrigger,
  boundWorkflowRun,
  boundWorkflowRunFromRun,
  boundWorkflowRunInputFromRun,
  boundWorkflowSchedule,
  boundWorkflowScheduleFromSchedule,
  boundWorkflowScheduleInputFromSchedule,
  boundWorkflowTarget,
  boundWorkflowTargetFromTarget,
  boundWorkflowTargetInputFromTarget,
  boundWorkflowTargetFromProto,
  boundWorkflowTargetToProto,
  createWorkflowProviderService,
  defineWorkflowProvider,
  isWorkflowProvider,
  workflowActor,
  workflowActorInputFromActor,
  workflowEvent,
  workflowEventFromEvent,
  workflowEventInputFromEvent,
  workflowEventMatch,
  workflowEventMatchInputFromMatch,
  workflowEventTriggerInvocation,
  workflowAgentMessage,
  workflowAgentMessageFromProto,
  workflowAgentMessageInputFromMessage,
  workflowAgentMessageToProto,
  workflowRunTrigger,
  workflowRunTriggerFromTrigger,
  workflowRunTriggerInputFromTrigger,
  workflowScheduleTrigger,
  workflowSignal,
  workflowSignalFromSignal,
  workflowSignalInputFromSignal,
  type BoundWorkflowDefinition,
  type BoundWorkflowEventTrigger,
  type BoundWorkflowRun,
  type BoundWorkflowSchedule,
  type BoundWorkflowTarget,
  type CancelWorkflowProviderRunRequest,
  type CreateWorkflowProviderDefinitionRequest,
  type DeleteWorkflowProviderDefinitionRequest,
  type DeleteWorkflowProviderEventTriggerRequest,
  type DeleteWorkflowProviderScheduleRequest,
  type GetWorkflowProviderDefinitionRequest,
  type GetWorkflowProviderEventTriggerRequest,
  type GetWorkflowProviderRunRequest,
  type GetWorkflowProviderScheduleRequest,
  type ListWorkflowProviderEventTriggersRequest,
  type ListWorkflowProviderRunsRequest,
  type ListWorkflowProviderRunsResponse,
  type ListWorkflowProviderSchedulesRequest,
  type WorkflowDefinition,
  type WorkflowEventTrigger,
  type WorkflowRun,
  type WorkflowRunSignal,
  type WorkflowSchedule,
  type PauseWorkflowProviderEventTriggerRequest,
  type PauseWorkflowProviderScheduleRequest,
  type PublishWorkflowProviderEventRequest,
  type ResumeWorkflowProviderEventTriggerRequest,
  type ResumeWorkflowProviderScheduleRequest,
  type SignalOrStartWorkflowProviderRunRequest,
  type SignalWorkflowProviderRunRequest,
  type SignalWorkflowRunResponse,
  type StartWorkflowProviderRunRequest,
  type UpdateWorkflowProviderDefinitionRequest,
  type UpsertWorkflowProviderEventTriggerRequest,
  type UpsertWorkflowProviderScheduleRequest,
  type WorkflowActor,
  type WorkflowEvent,
  type WorkflowEventMatch,
  type WorkflowEventTriggerInvocation,
  workflowStep,
  workflowStepAgentTurn,
  workflowStepAgentTurnFromProto,
  workflowStepAgentTurnInputFromTurn,
  workflowStepAgentTurnToProto,
  workflowStepFromProto,
  workflowStepInputFromStep,
  workflowStepOutputSource,
  workflowStepOutputSourceFromProto,
  workflowStepOutputSourceInputFromSource,
  workflowStepOutputSourceToProto,
  workflowStepAppCall,
  workflowStepAppCallFromProto,
  workflowStepAppCallInputFromCall,
  workflowStepAppCallToProto,
  workflowStepToProto,
  workflowStepWhen,
  workflowStepWhenFromProto,
  workflowStepWhenInputFromWhen,
  workflowStepWhenToProto,
  workflowText,
  workflowTextFromProto,
  workflowTextInputFromText,
  workflowTextToProto,
  workflowValue,
  workflowValueFromProto,
  workflowValueInputFromValue,
  workflowValueToProto,
  type WorkflowAgentMessage,
  type WorkflowProviderOptions,
  type WorkflowRunTrigger,
  type WorkflowScheduleTrigger,
  type WorkflowSignal,
  type WorkflowStep,
  type WorkflowStepAgentTurn,
  type WorkflowStepOutputSource,
  type WorkflowStepAppCall,
  type WorkflowStepWhen,
  type WorkflowText,
  type WorkflowValue,
} from "./workflow.ts";
export {
  WorkflowValueError,
  evaluateWorkflowStepInputs,
  evaluateWorkflowValue,
  latestWorkflowSignal,
  mapPathValue,
  parseWorkflowRunContext,
  pathValue,
  renderWorkflowTemplate,
  workflowRunContext,
  workflowSignalsContext,
  type WorkflowEvalContext,
  type WorkflowExecutionRequest,
  type WorkflowRunContextActor,
  type WorkflowRunContext,
  type WorkflowRunContextSignal,
  type WorkflowRunContextTrigger,
} from "./workflow.ts";
export {
  GENAI_OPERATION_CHAT,
  GENAI_OPERATION_EXECUTE_TOOL,
  GENAI_OPERATION_INVOKE_AGENT,
  GENAI_PROVIDER_NAME,
  GENAI_TOOL_TYPE_DATASTORE,
  GENAI_TOOL_TYPE_EXTENSION,
  GenAIOperation,
  TELEMETRY_INSTRUMENTATION_NAME,
  withAgentInvocation,
  withModelOperation,
  withToolExecution,
  type AgentInvocationOptions,
  type ModelOperationOptions,
  type TokenUsage,
  type ToolExecutionOptions,
} from "./telemetry.ts";
