/**
 * @packageDocumentation
 *
 * Authored TypeScript APIs for building Gestalt providers, helper CLIs, and
 * runtime adapters.
 *
 * @example
 * ```ts
 * import { definePlugin, ok, operation, s } from "@valon-technologies/gestalt";
 *
 * export const plugin = definePlugin({
 *   displayName: "Example Provider",
 *   operations: [
 *     operation({
 *       id: "hello",
 *       input: s.object({ name: s.string({ default: "World" }) }),
 *       output: s.object({ message: s.string() }),
 *       async handler(input) {
 *         return ok({ message: `Hello, ${input.name}` });
 *       },
 *     }),
 *   ],
 * });
 * ```
 *
 * @example
 * ```ts
 * import { parseRuntimeArgs, serve } from "@valon-technologies/gestalt/runtime";
 * ```
 */
export {
  AGENT_SESSION_ACTION_EDIT,
  AGENT_SESSION_ACTION_VIEW,
  AGENT_SESSION_RELATION_EDITOR,
  AGENT_SESSION_RESOURCE_TYPE,
  Authorization,
  AuthorizationClient,
  AuthorizationProvider,
  AUTHORIZATION_SUBJECT_TYPE_SUBJECT,
  ENV_AUTHORIZATION_SOCKET,
  ENV_AUTHORIZATION_SOCKET_TOKEN,
  agentSessionAuthorizationResource,
  agentSessionEditorRelationship,
  agentSessionEditorWriteRequest,
  authorizationAction,
  createAuthorizationProviderService,
  defineAuthorizationProvider,
  authorizationRelationship,
  authorizationRelationshipKeyWithTarget,
  authorizationRelationshipKey,
  authorizationRelationshipWithTarget,
  authorizationResource,
  authorizationResourceTarget,
  authorizationSubject,
  authorizationSubjectSet,
  authorizationSubjectSetTarget,
  authorizationSubjectTarget,
  isAuthorizationProvider,
  type AuthorizationAction,
  type AuthorizationActionSearch,
  type AuthorizationDecision,
  type AuthorizationEvaluateInput,
  type AuthorizationEvaluateManyInput,
  type AuthorizationEvaluationsResponse,
  type AuthorizationEffectiveSearchSubjectsInput,
  type AuthorizationEffectiveSubjectSearch,
  type AuthorizationExpandInput,
  type AuthorizationExpand,
  type AuthorizationExpandNode,
  type AuthorizationGetActiveModel,
  type AuthorizationListModelsInput,
  type AuthorizationListModels,
  type AuthorizationMetadata,
  type AuthorizationModel,
  type AuthorizationModelAction,
  type AuthorizationModelAllowedTarget,
  type AuthorizationModelAllowedTargetKind,
  type AuthorizationModelComputedUserset,
  type AuthorizationModelRef,
  type AuthorizationModelRelation,
  type AuthorizationModelResourceType,
  type AuthorizationModelRewrite,
  type AuthorizationModelRewriteKind,
  type AuthorizationModelRewriteThis,
  type AuthorizationModelRewriteUnion,
  type AuthorizationModelSubjectSetTarget,
  type AuthorizationModelTupleToUserset,
  type AuthorizationProviderOptions,
  type AuthorizationReadRelationshipsInput,
  type AuthorizationReadRelationships,
  type AuthorizationRelationship,
  type AuthorizationRelationshipKey,
  type AuthorizationRelationshipTarget,
  type AuthorizationRelationshipTargetKind,
  type AuthorizationResource,
  type AuthorizationSubjectSet,
  type AuthorizationResourceSearch,
  type AuthorizationSearchActionsInput,
  type AuthorizationSearchResourcesInput,
  type AuthorizationSearchSubjectsInput,
  type AuthorizationSubject,
  type AuthorizationSubjectSearch,
  type AuthorizationWriteRelationshipsInput,
  type AuthorizationWriteModelInput,
} from "./authorization.ts";
export {
  connectionParam,
  ok,
  response,
  responseBrand,
  request,
  type Access,
  type Host,
  type MaybePromise,
  type Credential,
  type ExternalIdentity,
  type OperationResult,
  type Request,
  type Response,
  type Subject,
  type SubjectInput,
} from "./api.ts";
export {
  type HTTPSubjectRequest,
  type HTTPSubjectResolutionContext,
  HTTPSubjectResolutionError,
  type HTTPSubjectResolver,
  httpSubjectError,
} from "./http-subject.ts";
export {
  catalogToJson,
  catalogToYaml,
  schemaToCatalogSchema,
  schemaToParameters,
  writeCatalogYaml,
  type Catalog,
  type CatalogOperation,
  type CatalogParameter,
  type CatalogSchema,
  type OperationAnnotations,
} from "./catalog.ts";
export {
  buildProviderBinary,
  bunBuildCommand,
  bunTarget,
  parseBuildArgs,
} from "./build.ts";
export {
  ENV_PLUGIN_INVOKER_SOCKET,
  ENV_PLUGIN_INVOKER_SOCKET_TOKEN,
  PluginInvoker,
  type PluginGraphQLInvokeOptions,
  type PluginInvocationGrant,
  type PluginInvokeOptions,
} from "./invoker.ts";
export {
  ENV_AGENT_MANAGER_SOCKET,
  ENV_AGENT_MANAGER_SOCKET_TOKEN,
  AgentManager,
  type AgentManagerCancelTurn,
  type AgentManagerCreateSession,
  type AgentManagerCreateTurn,
  type AgentManagerGetSession,
  type AgentManagerGetTurn,
  type AgentManagerListInteractions,
  type AgentManagerListSessions,
  type AgentManagerListTurnEvents,
  type AgentManagerListTurns,
  type AgentManagerResolveInteraction,
  type AgentManagerUpdateSession,
  type AgentManagerWorkspace,
  type AgentManagerWorkspaceGitCheckout,
} from "./agent-manager.ts";
export {
  ENV_WORKFLOW_MANAGER_SOCKET,
  ENV_WORKFLOW_MANAGER_SOCKET_TOKEN,
  WorkflowManager,
  type WorkflowManagerCreateDefinition,
  type WorkflowManagerCreateTrigger,
  type WorkflowManagerCreateSchedule,
  type WorkflowManagerDeleteDefinition,
  type WorkflowManagerDeleteTrigger,
  type WorkflowManagerDeleteSchedule,
  type WorkflowManagerGetDefinition,
  type WorkflowManagerGetTrigger,
  type WorkflowManagerGetSchedule,
  type WorkflowManagerPauseTrigger,
  type WorkflowManagerPauseSchedule,
  type WorkflowManagerPublishEvent,
  type WorkflowManagerResumeTrigger,
  type WorkflowManagerResumeSchedule,
  type WorkflowManagerSignalOrStartRun,
  type WorkflowManagerSignalRun,
  type WorkflowManagerStartRun,
  type WorkflowManagerUpdateDefinition,
  type WorkflowManagerUpdateTrigger,
  type WorkflowManagerUpdateSchedule,
} from "./workflow-manager.ts";
export {
  ENV_RUNTIME_LOG_HOST_SOCKET,
  ENV_RUNTIME_LOG_HOST_SOCKET_TOKEN,
  ENV_RUNTIME_SESSION_ID,
  RuntimeLogHost,
  type RuntimeLogAppendInput,
  type RuntimeLogAppendLogsInput,
  type RuntimeLogAppendResponse,
  type RuntimeLogStreamInput,
  type RuntimeLogStreamName,
  type RuntimeLogWriterOptions,
} from "./runtime-log-host.ts";
export {
  AuthenticationProvider,
  defineAuthenticationProvider,
  isAuthenticationProvider,
  type AuthenticatedUser,
  type AuthenticationProviderOptions,
  type AuthenticationSessionSettings,
  type BeginLoginRequest,
  type BeginLoginResponse,
  type CompleteLoginRequest,
} from "./auth.ts";
export {
  Cache,
  CacheProvider,
  cacheSocketEnv,
  cacheSocketTokenEnv,
  defineCacheProvider,
  isCacheProvider,
  ENV_CACHE_SOCKET,
  ENV_CACHE_SOCKET_TOKEN,
  type CacheEntry,
  type CacheProviderOptions,
  type CacheSetOptions,
} from "./cache.ts";
export {
  defineSecretsProvider,
  isSecretsProvider,
  type SecretsProviderOptions,
} from "./secrets.ts";
export {
  type ConnectedToken,
  PluginProvider,
  connectionModeToProtoValue,
  connectionParamToProto,
  definePlugin,
  isPluginProvider,
  operation,
  type ConnectionMode,
  type ConnectionParamDefinition,
  type OperationDefinition,
  type OperationOptions,
  type PostConnectHandler,
  type PluginDefinitionOptions,
  type SessionCatalog,
  type SessionCatalogHandler,
} from "./plugin.ts";
export {
  ProviderBase,
  isProviderBase,
  slugName,
  type CloseHandler,
  type ConfigureHandler,
  type HealthCheckHandler,
  type ProviderKind,
  type ProviderMetadata,
  type ProviderBaseOptions,
  type StartHandler,
  type WarningsHandler,
} from "./provider.ts";
export {
  PluginRuntimeEgressMode,
  PluginRuntimeProvider,
  createPluginRuntimeProviderService,
  definePluginRuntimeProvider,
  isPluginRuntimeProvider,
  type GetPluginRuntimeSessionRequest,
  type HostedPlugin,
  type ListPluginRuntimeSessionsRequest,
  type PluginRuntimeAgentWorkspace,
  type PluginRuntimeAgentWorkspaceGitCheckout,
  type PluginRuntimeImagePullAuth,
  type PluginRuntimePreparedAgentWorkspace,
  type PluginRuntimeProviderOptions,
  type PluginRuntimeSession,
  type PluginRuntimeSessionLifecycle,
  type PluginRuntimeSupport,
  type PreparePluginRuntimeWorkspaceRequest,
  type PreparePluginRuntimeWorkspaceResponse,
  type RemovePluginRuntimeWorkspaceRequest,
  type StartHostedPluginRequest,
  type StartPluginRuntimeSessionRequest,
  type StopPluginRuntimeSessionRequest,
} from "./pluginruntime.ts";
export {
  array,
  boolean,
  type InferSchema,
  integer,
  number,
  object,
  optional,
  s,
  string,
  type Schema,
  type SchemaOptions,
} from "./schema.ts";
export {
  CURRENT_PROTOCOL_VERSION,
  ENV_PROVIDER_PARENT_PID,
  ENV_PROVIDER_SOCKET,
  ENV_WRITE_CATALOG,
  createAuthenticationService,
  createCacheService,
  createSecretsService,
  createProviderService,
  createRuntimeService,
  loadProviderFromTarget,
  main as runtimeMain,
  parseRuntimeArgs,
  runBundledProvider,
  runLoadedProvider,
  serve,
} from "./runtime.ts";
export {
  defaultProviderName,
  formatModuleTarget,
  formatProviderTarget,
  parseModuleTarget,
  parseProviderTarget,
  readPackageConfig,
  readPackageProviderTarget,
  resolveProviderImportUrl,
  resolveProviderModulePath,
  type ModuleTarget,
  type PackageConfig,
  type ProviderTarget,
} from "./target.ts";
export {
  IndexedDB,
  ObjectStore,
  Index,
  Transaction,
  TransactionObjectStore,
  TransactionIndex,
  Cursor,
  CursorDirection,
  NotFoundError,
  AlreadyExistsError,
  TransactionError,
  ColumnType,
  indexedDBSocketEnv,
  indexedDBSocketTokenEnv,
  type Record,
  type KeyRange,
  type TransactionMode,
  type TransactionDurabilityHint,
  type TransactionOptions,
  type ColumnSchema,
  type IndexSchema,
  type ObjectStoreSchema,
  type OpenCursorOptions,
} from "./indexeddb.ts";
export {
  S3,
  S3Object,
  S3Provider,
  S3InvalidRangeError,
  S3NotFoundError,
  S3PreconditionFailedError,
  PresignMethod,
  createS3Service,
  defineS3Provider,
  isS3Provider,
  ENV_S3_SOCKET,
  ENV_S3_SOCKET_TOKEN,
  s3SocketEnv,
  s3SocketTokenEnv,
  type ByteRange,
  type CopyOptions,
  type ListOptions,
  type ListPage,
  type ObjectAccessURL,
  type ObjectAccessURLOptions,
  type ObjectMeta,
  type ObjectRef,
  type PresignOptions,
  type PresignResult,
  type ProviderReadResult,
  type ReadOptions,
  type ReadResult,
  type S3BodySource,
  type S3ProviderOptions,
  type WriteOptions,
} from "./s3.ts";
export {
  ENV_AGENT_HOST_SOCKET,
  ENV_AGENT_HOST_SOCKET_TOKEN,
  AgentHost,
  AgentExecutionStatus,
  AgentInteractionState,
  AgentInteractionType,
  AgentMessagePartType,
  AgentProvider,
  AgentSessionState,
  AgentToolSourceMode,
  createAgentProviderService,
  defineAgentProvider,
  isAgentProvider,
  type AgentActor,
  type AgentHostExecuteToolInput,
  type AgentHostListToolsInput,
  type AgentHostResolveConnectionInput,
  type AgentInteraction,
  type AgentMessage,
  type AgentMessagePart,
  type AgentMessagePartImageRef,
  type AgentMessagePartToolCall,
  type AgentMessagePartToolResult,
  type AgentPreparedWorkspace,
  type AgentProviderCapabilities,
  type AgentProviderOptions,
  type AgentSession,
  type AgentSessionStartConfig,
  type AgentSessionStartHook,
  type AgentSessionStartHookOutput,
  type AgentSubjectContext,
  type AgentToolAnnotations,
  type AgentToolRef,
  type AgentTurn,
  type AgentTurnDisplay,
  type AgentTurnEvent,
  type CancelAgentProviderTurnRequest,
  type CreateAgentProviderSessionRequest,
  type CreateAgentProviderTurnRequest,
  type ExecuteAgentToolRequest,
  type ExecuteAgentToolResponse,
  type GetAgentProviderCapabilitiesRequest,
  type GetAgentProviderInteractionRequest,
  type GetAgentProviderSessionRequest,
  type GetAgentProviderTurnRequest,
  type ListAgentToolsRequest,
  type ListAgentToolsResponse,
  type ListAgentProviderInteractionsRequest,
  type ListAgentProviderInteractionsResponse,
  type ListAgentProviderSessionsRequest,
  type ListAgentProviderSessionsResponse,
  type ListAgentProviderTurnEventsRequest,
  type ListAgentProviderTurnEventsResponse,
  type ListAgentProviderTurnsRequest,
  type ListAgentProviderTurnsResponse,
  type ListedAgentTool,
  type ResolveAgentConnectionRequest,
  type ResolveAgentProviderInteractionRequest,
  type ResolvedAgentConnection,
  type ResolvedAgentTool,
  type UpdateAgentProviderSessionRequest,
} from "./agent.ts";
export {
  ENV_WORKFLOW_HOST_SOCKET,
  ENV_WORKFLOW_HOST_SOCKET_TOKEN,
  WorkflowHost,
  WorkflowProvider,
  WorkflowRunStatus,
  boundWorkflowAgentTarget,
  boundWorkflowAgentTargetInputFromTarget,
  boundWorkflowEventTrigger,
  boundWorkflowEventTriggerFromTrigger,
  boundWorkflowEventTriggerInputFromTrigger,
  boundWorkflowPluginTarget,
  boundWorkflowPluginTargetInputFromTarget,
  boundWorkflowRun,
  boundWorkflowRunFromRun,
  boundWorkflowRunInputFromRun,
  boundWorkflowSchedule,
  boundWorkflowScheduleFromSchedule,
  boundWorkflowScheduleInputFromSchedule,
  boundWorkflowTarget,
  boundWorkflowTargetFromTarget,
  boundWorkflowTargetInputFromTarget,
  createWorkflowProviderService,
  defineWorkflowProvider,
  isWorkflowProvider,
  workflowAccessPermission,
  workflowAccessPermissionInputFromPermission,
  workflowActor,
  workflowActorInputFromActor,
  workflowEvent,
  workflowEventFromEvent,
  workflowEventInputFromEvent,
  workflowEventMatch,
  workflowEventMatchInputFromMatch,
  workflowEventTriggerInvocation,
  workflowExecutionReference,
  workflowExecutionReferenceFromReference,
  workflowExecutionReferenceInputFromReference,
  workflowOutputBinding,
  workflowOutputBindingInputFromBinding,
  workflowOutputDelivery,
  workflowOutputDeliveryInputFromDelivery,
  workflowOutputValueSource,
  workflowOutputValueSourceInputFromSource,
  workflowRunAsSubject,
  workflowRunAsSubjectInputFromSubject,
  workflowRunTrigger,
  workflowRunTriggerFromTrigger,
  workflowRunTriggerInputFromTrigger,
  workflowScheduleTrigger,
  workflowSignal,
  workflowSignalFromSignal,
  workflowSignalInputFromSignal,
  type BoundWorkflowAgentTarget,
  type BoundWorkflowEventTrigger,
  type BoundWorkflowPluginTarget,
  type BoundWorkflowRun,
  type BoundWorkflowSchedule,
  type BoundWorkflowTarget,
  type CancelWorkflowProviderRunRequest,
  type DeleteWorkflowProviderEventTriggerRequest,
  type DeleteWorkflowProviderScheduleRequest,
  type GetWorkflowExecutionReferenceRequest,
  type GetWorkflowProviderEventTriggerRequest,
  type GetWorkflowProviderRunRequest,
  type GetWorkflowProviderScheduleRequest,
  type InvokeWorkflowOperationInput,
  type InvokeWorkflowOperationResponse,
  type ListWorkflowExecutionReferencesRequest,
  type ListWorkflowProviderEventTriggersRequest,
  type ListWorkflowProviderRunsRequest,
  type ListWorkflowProviderSchedulesRequest,
  type ManagedWorkflowDefinition,
  type ManagedWorkflowEventTrigger,
  type ManagedWorkflowRun,
  type ManagedWorkflowRunSignal,
  type ManagedWorkflowSchedule,
  type PauseWorkflowProviderEventTriggerRequest,
  type PauseWorkflowProviderScheduleRequest,
  type PublishWorkflowProviderEventRequest,
  type PutWorkflowExecutionReferenceRequest,
  type ResumeWorkflowProviderEventTriggerRequest,
  type ResumeWorkflowProviderScheduleRequest,
  type SignalOrStartWorkflowProviderRunRequest,
  type SignalWorkflowProviderRunRequest,
  type SignalWorkflowRunResponse,
  type StartWorkflowProviderRunRequest,
  type UpsertWorkflowProviderEventTriggerRequest,
  type UpsertWorkflowProviderScheduleRequest,
  type WorkflowAccessPermission,
  type WorkflowActor,
  type WorkflowEvent,
  type WorkflowEventMatch,
  type WorkflowEventTriggerInvocation,
  type WorkflowExecutionReference,
  type WorkflowOutputBinding,
  type WorkflowOutputDelivery,
  type WorkflowOutputValueSource,
  type WorkflowProviderOptions,
  type WorkflowRunAsSubject,
  type WorkflowRunTrigger,
  type WorkflowScheduleTrigger,
  type WorkflowSignal,
} from "./workflow.ts";
export {
  GENAI_OPERATION_CHAT,
  GENAI_OPERATION_EXECUTE_TOOL,
  GENAI_OPERATION_INVOKE_AGENT,
  GENAI_PROVIDER_NAME,
  GENAI_TOOL_TYPE_DATASTORE,
  GENAI_TOOL_TYPE_EXTENSION,
  GenAIOperation,
  TELEMETRY_INSTRUMENTATION_NAME,
  withAgentInvocation,
  withModelOperation,
  withToolExecution,
  type AgentInvocationOptions,
  type ModelOperationOptions,
  type TokenUsage,
  type ToolExecutionOptions,
} from "./telemetry.ts";
