"""Public authoring surface for Gestalt Python providers.

The package is published as ``gestalt-sdk`` and imported as ``gestalt``.
Use it for executable provider code: integration operations, host-service
providers, host-service clients, and provider-owned telemetry.

.. code-block:: python

    from gestalt import Model, App, operation

    class SearchInput(Model):
        query: str

    app = App("search")

    @app.operation(title="Search")
    def search(params: SearchInput):
        return {"query": params.query}

Transport internals are owned by the SDK. Provider code should use the authored
helpers exported here.
"""

from importlib import import_module

from ._api import (
    OK,
    Access,
    Credential,
    Error,
    Host,
    Model,
    Request,
    Response,
    Subject,
    field,
    parse_subject_id,
)

_AGENT_PROTOCOL_EXPORTS = (
    "AGENT_EXECUTION_STATUS_CANCELED",
    "AGENT_EXECUTION_STATUS_FAILED",
    "AGENT_EXECUTION_STATUS_PENDING",
    "AGENT_EXECUTION_STATUS_RUNNING",
    "AGENT_EXECUTION_STATUS_SUCCEEDED",
    "AGENT_EXECUTION_STATUS_UNSPECIFIED",
    "AGENT_EXECUTION_STATUS_WAITING_FOR_INPUT",
    "AGENT_INTERACTION_STATE_CANCELED",
    "AGENT_INTERACTION_STATE_PENDING",
    "AGENT_INTERACTION_STATE_RESOLVED",
    "AGENT_INTERACTION_STATE_UNSPECIFIED",
    "AGENT_INTERACTION_TYPE_APPROVAL",
    "AGENT_INTERACTION_TYPE_CLARIFICATION",
    "AGENT_INTERACTION_TYPE_INPUT",
    "AGENT_INTERACTION_TYPE_UNSPECIFIED",
    "AGENT_MESSAGE_PART_TYPE_IMAGE_REF",
    "AGENT_MESSAGE_PART_TYPE_JSON",
    "AGENT_MESSAGE_PART_TYPE_TEXT",
    "AGENT_MESSAGE_PART_TYPE_TOOL_CALL",
    "AGENT_MESSAGE_PART_TYPE_TOOL_RESULT",
    "AGENT_MESSAGE_PART_TYPE_UNSPECIFIED",
    "AGENT_SESSION_STATE_ACTIVE",
    "AGENT_SESSION_STATE_ARCHIVED",
    "AGENT_SESSION_STATE_UNSPECIFIED",
    "AGENT_TOOL_SOURCE_MODE_MCP_CATALOG",
    "AGENT_TOOL_SOURCE_MODE_NONE",
    "AGENT_TOOL_SOURCE_MODE_UNSPECIFIED",
    "AgentInteraction",
    "AgentMessage",
    "AgentMessagePart",
    "AgentMessagePartImageRef",
    "AgentMessagePartToolCall",
    "AgentMessagePartToolResult",
    "AgentProviderCapabilities",
    "AgentPreparedWorkspace",
    "AgentOutput",
    "AgentSessionStartConfig",
    "AgentSessionStartHook",
    "AgentSessionStartHookOutput",
    "AgentSession",
    "AgentToolAnnotations",
    "AgentToolRef",
    "AgentStructuredOutput",
    "AgentTextOutput",
    "AgentTurn",
    "AgentTurnDisplay",
    "AgentTurnEvent",
    "AgentTurnOutput",
    "AgentTurnStructuredOutput",
    "CancelAgentProviderTurnRequest",
    "CreateAgentProviderSessionRequest",
    "CreateAgentProviderTurnRequest",
    "ExecuteAgentToolRequest",
    "ExecuteAgentToolResponse",
    "GetAgentProviderCapabilitiesRequest",
    "GetAgentProviderInteractionRequest",
    "GetAgentProviderSessionRequest",
    "GetAgentProviderTurnRequest",
    "ListAgentProviderInteractionsResponse",
    "ListAgentProviderInteractionsRequest",
    "ListAgentProviderSessionsRequest",
    "ListAgentProviderSessionsResponse",
    "ListAgentProviderTurnEventsRequest",
    "ListAgentProviderTurnEventsResponse",
    "ListAgentProviderTurnsRequest",
    "ListAgentProviderTurnsResponse",
    "ListAgentToolsRequest",
    "ListAgentToolsResponse",
    "ListedAgentTool",
    "ResolvedAgentTool",
    "ResolvedAgentConnection",
    "ResolveAgentConnectionRequest",
    "ResolveAgentProviderInteractionRequest",
    "UpdateAgentProviderSessionRequest",
)

_AGENT_HELPER_EXPORTS = (
    "AgentCancelTurn",
    "Agent",
    "AgentProtocol",
    "AgentCreateSession",
    "AgentCreateTurn",
    "AgentGetSession",
    "AgentGetTurn",
    "AgentListInteractions",
    "AgentListSessions",
    "AgentListTurnEvents",
    "AgentListTurns",
    "AgentResolveInteraction",
    "AgentUpdateSession",
    "ListAgentInteractionsResponse",
    "ListAgentSessionsResponse",
    "ListAgentTurnEventsResponse",
    "ListAgentTurnsResponse",
    "AgentMessage",
    "AgentMessagePartImageRef",
    "AgentMessagePart",
    "AgentMessagePartToolCall",
    "AgentMessagePartToolResult",
    "AgentToolRef",
    "AgentWorkspaceGitCheckout",
    "AgentWorkspace",
    "AgentHost",
    "AgentHostProtocol",
    "agent_actor_from_dict",
    "agent_actor_to_dict",
    "agent_message_from_dict",
    "agent_message_part_from_dict",
    "agent_message_part_to_dict",
    "agent_message_to_dict",
    "agent_messages_from_dicts",
    "agent_messages_to_dicts",
    "subject_from_dict",
    "subject_to_dict",
    "agent_tool_ref_from_dict",
    "agent_tool_ref_to_dict",
    "prepared_workspace_from_dict",
    "prepared_workspace_to_dict",
)

_AUTHENTICATION_AUTHORED_EXPORTS = (
    "AuthenticatedUser",
    "BeginLoginRequest",
    "BeginLoginResponse",
    "CompleteLoginRequest",
)

_PROTOCOL_TYPE_EXPORTS = (
    "JsonObject",
    "JsonValue",
)

_AUTHORIZATION_AUTHORED_EXPORTS = (
    "AccessDecision",
    "AccessEvaluationRequest",
    "AccessEvaluationsRequest",
    "AccessEvaluationsResponse",
    "ActionSearchRequest",
    "ActionSearchResponse",
    "AuthorizationAction",
    "AuthorizationMetadata",
    "AuthorizationModel",
    "AuthorizationModelAction",
    "AuthorizationModelAllowedTarget",
    "AuthorizationModelComputedUserset",
    "AuthorizationModelRef",
    "AuthorizationModelRelation",
    "AuthorizationModelResourceType",
    "AuthorizationModelRewrite",
    "AuthorizationModelRewriteThis",
    "AuthorizationModelRewriteUnion",
    "AuthorizationModelSubjectSetTarget",
    "AuthorizationModelTupleToUserset",
    "AuthorizationRelationshipTarget",
    "AuthorizationResource",
    "AuthorizationSubject",
    "AuthorizationSubjectSet",
    "EffectiveSubjectSearchRequest",
    "EffectiveSubjectSearchResponse",
    "ExpandNode",
    "ExpandRequest",
    "ExpandResponse",
    "GetActiveModelResponse",
    "ListModelsRequest",
    "ListModelsResponse",
    "ReadRelationshipsRequest",
    "ReadRelationshipsResponse",
    "Relationship",
    "RelationshipKey",
    "ResourceSearchRequest",
    "ResourceSearchResponse",
    "SubjectSearchRequest",
    "SubjectSearchResponse",
    "WriteModelRequest",
    "WriteRelationshipsRequest",
)

_AUTHORIZATION_HELPER_EXPORTS = ("AUTHORIZATION_SUBJECT_TYPE_SUBJECT",)

_RUNTIME_PROVIDER_AUTHORED_EXPORTS = (
    "GetRuntimeSessionRequest",
    "GetRuntimeSupportRequest",
    "HostedApp",
    "ListRuntimeSessionsRequest",
    "ListRuntimeSessionsResponse",
    "RUNTIME_EGRESS_MODE_CIDR",
    "RUNTIME_EGRESS_MODE_HOSTNAME",
    "RUNTIME_EGRESS_MODE_NONE",
    "RUNTIME_EGRESS_MODE_UNSPECIFIED",
    "RuntimeImagePullAuth",
    "RuntimeSession",
    "RuntimeSessionLifecycle",
    "RuntimeSupport",
    "PrepareRuntimeWorkspaceRequest",
    "PrepareRuntimeWorkspaceResponse",
    "RemoveRuntimeWorkspaceRequest",
    "StartHostedAppRequest",
    "StartRuntimeSessionRequest",
    "StopRuntimeSessionRequest",
)

_WORKFLOW_AUTHORED_EXPORTS = (
    "ApplyWorkflowProviderDefinitionRequest",
    "BoundWorkflowTarget",
    "CancelWorkflowProviderRunRequest",
    "DeliverWorkflowProviderEventRequest",
    "DeleteWorkflowProviderDefinitionRequest",
    "GetWorkflowProviderDefinitionRequest",
    "GetWorkflowProviderRunEventsRequest",
    "GetWorkflowProviderRunEventsResponse",
    "GetWorkflowProviderRunOutputRequest",
    "GetWorkflowProviderRunOutputResponse",
    "GetWorkflowProviderRunRequest",
    "ListWorkflowProviderDefinitionsRequest",
    "ListWorkflowProviderDefinitionsResponse",
    "ListWorkflowProviderRunsResponse",
    "ListWorkflowProviderRunsRequest",
    "SetWorkflowProviderActivationPausedRequest",
    "SetWorkflowProviderDefinitionPausedRequest",
    "SignalOrStartWorkflowProviderRunRequest",
    "SignalWorkflowProviderRunRequest",
    "SignalWorkflowRunResponse",
    "StartWorkflowProviderRunRequest",
    "WORKFLOW_RUN_STATUS_CANCELED",
    "WORKFLOW_RUN_STATUS_FAILED",
    "WORKFLOW_RUN_STATUS_PENDING",
    "WORKFLOW_RUN_STATUS_RUNNING",
    "WORKFLOW_RUN_STATUS_SUCCEEDED",
    "WORKFLOW_RUN_STATUS_UNSPECIFIED",
    "WORKFLOW_STEP_STATUS_FAILED",
    "WORKFLOW_STEP_STATUS_PENDING",
    "WORKFLOW_STEP_STATUS_RUNNING",
    "WORKFLOW_STEP_STATUS_SKIPPED",
    "WORKFLOW_STEP_STATUS_SUCCEEDED",
    "WORKFLOW_STEP_STATUS_UNKNOWN",
    "WORKFLOW_STEP_STATUS_UNSPECIFIED",
    "WorkflowActivation",
    "WorkflowAgentMessage",
    "WorkflowApplyDefinition",
    "WorkflowDefinition",
    "WorkflowDefinitionSpec",
    "WorkflowDeleteDefinition",
    "WorkflowDeliverEvent",
    "WorkflowEvent",
    "WorkflowEventMatch",
    "WorkflowEventTriggerInvocation",
    "WorkflowGetDefinition",
    "WorkflowGetRun",
    "WorkflowGetRunEvents",
    "WorkflowGetRunOutput",
    "Workflow",
    "WorkflowJsonObject",
    "WorkflowJsonScalar",
    "WorkflowJsonValue",
    "WorkflowProtocol",
    "WorkflowRun",
    "WorkflowRunEvent",
    "WorkflowRunSignal",
    "WorkflowRunTrigger",
    "WorkflowScheduleTrigger",
    "WorkflowSetActivationPaused",
    "WorkflowSetDefinitionPaused",
    "WorkflowSignalOrStartRun",
    "WorkflowSignalRun",
    "WorkflowStartRun",
    "WorkflowStep",
    "WorkflowStepAgentTurn",
    "WorkflowStepAppCall",
    "WorkflowStepAttempt",
    "WorkflowStepExecution",
    "WorkflowStepOutputSource",
    "WorkflowStepWhen",
    "WorkflowText",
    "WorkflowValue",
    "WorkflowValueInput",
    "WorkflowValuePayload",
    "WorkflowSignal",
    "bound_workflow_target",
    "bound_workflow_target_from_target",
    "bound_workflow_target_input_from_target",
    "workflow_event",
    "workflow_event_from_event",
    "workflow_event_input_from_event",
    "workflow_event_match",
    "workflow_event_match_input_from_match",
    "workflow_event_trigger_invocation",
    "workflow_definition",
    "workflow_definition_from_definition",
    "workflow_definition_input_from_definition",
    "workflow_definition_spec",
    "workflow_definition_spec_input_from_spec",
    "workflow_agent_message",
    "workflow_agent_message_input_from_message",
    "workflow_run",
    "workflow_run_event",
    "workflow_run_event_input_from_event",
    "workflow_run_from_proto",
    "workflow_run_from_run",
    "workflow_run_input_from_run",
    "workflow_run_status_name",
    "workflow_run_trigger",
    "workflow_run_trigger_from_trigger",
    "workflow_run_trigger_input_from_trigger",
    "workflow_schedule_trigger",
    "workflow_signal",
    "workflow_signal_from_signal",
    "workflow_signal_input_from_signal",
    "workflow_step",
    "workflow_step_agent_turn",
    "workflow_step_agent_turn_input_from_turn",
    "workflow_step_attempt",
    "workflow_step_attempt_input_from_attempt",
    "workflow_step_execution",
    "workflow_step_execution_input_from_execution",
    "workflow_step_input_from_step",
    "workflow_step_output_source",
    "workflow_step_output_source_input_from_source",
    "workflow_step_app_call",
    "workflow_step_app_call_input_from_call",
    "workflow_step_when",
    "workflow_step_when_input_from_when",
    "workflow_text",
    "workflow_text_input_from_text",
    "workflow_value",
    "workflow_value_input_from_value",
)

_WORKFLOW_HELPER_EXPORTS = (
    "WorkflowEvalContext",
    "WorkflowExecutionRequest",
    "WorkflowRunContextActor",
    "WorkflowRunContext",
    "WorkflowRunContextSignal",
    "WorkflowRunContextTrigger",
    "WorkflowValueError",
    "evaluate_workflow_step_inputs",
    "evaluate_workflow_value",
    "latest_workflow_signal",
    "map_path_value",
    "parse_workflow_run_context",
    "path_value",
    "render_workflow_template",
    "workflow_run_context",
    "workflow_signals_context",
)

_LAZY_EXPORTS = {
    "AgentHost": ("._agent", "AgentHost"),
    "AgentHostProtocol": ("._agent", "AgentHostProtocol"),
    "Agent": ("._agent", "Agent"),
    "AgentProtocol": ("._agent", "AgentProtocol"),
    "AgentProvider": ("._providers", "AgentProvider"),
    "AlreadyExistsError": ("._indexeddb", "AlreadyExistsError"),
    "AuthenticatedUser": ("._authentication", "AuthenticatedUser"),
    "AuthenticationProvider": ("._providers", "AuthenticationProvider"),
    "Authorization": ("._authorization", "Authorization"),
    "AuthorizationProtocol": ("._authorization", "AuthorizationProtocol"),
    "AuthorizationProvider": ("._providers", "AuthorizationProvider"),
    "BeginLoginRequest": ("._authentication", "BeginLoginRequest"),
    "BeginLoginResponse": ("._authentication", "BeginLoginResponse"),
    "ByteRange": ("._s3", "ByteRange"),
    "Cache": ("._cache", "Cache"),
    "CacheEntry": ("._cache", "CacheEntry"),
    "CacheProtocol": ("._cache", "CacheProtocol"),
    "CacheProvider": ("._providers", "CacheProvider"),
    "CURSOR_NEXT": ("._indexeddb", "CURSOR_NEXT"),
    "CURSOR_NEXT_UNIQUE": ("._indexeddb", "CURSOR_NEXT_UNIQUE"),
    "CURSOR_PREV": ("._indexeddb", "CURSOR_PREV"),
    "CURSOR_PREV_UNIQUE": ("._indexeddb", "CURSOR_PREV_UNIQUE"),
    "ENV_HOST_SERVICE_SOCKET": ("._grpc_transport", "ENV_HOST_SERVICE_SOCKET"),
    "ENV_HOST_SERVICE_TOKEN": ("._grpc_transport", "ENV_HOST_SERVICE_TOKEN"),
    "ENV_RUNTIME_SESSION_ID": ("._runtime_log_host", "ENV_RUNTIME_SESSION_ID"),
    "HOST_SERVICE_BINDING_HEADER": ("._grpc_transport", "HOST_SERVICE_BINDING_HEADER"),
    "Catalog": ("._catalog", "Catalog"),
    "CatalogOperation": ("._catalog", "CatalogOperation"),
    "CatalogParameter": ("._catalog", "CatalogParameter"),
    "Closer": ("._providers", "Closer"),
    "CompleteLoginRequest": ("._authentication", "CompleteLoginRequest"),
    "CopyOptions": ("._s3", "CopyOptions"),
    "Cursor": ("._indexeddb", "Cursor"),
    "ExternalTokenValidator": ("._providers", "ExternalTokenValidator"),
    "HealthChecker": ("._providers", "HealthChecker"),
    "HTTPSubjectRequest": ("._http_subject", "HTTPSubjectRequest"),
    "HTTPSubjectResolutionError": (
        "._http_subject",
        "HTTPSubjectResolutionError",
    ),
    "Index": ("._indexeddb", "Index"),
    "IndexProtocol": ("._indexeddb", "IndexProtocol"),
    "IndexedDBProtocol": ("._indexeddb", "IndexedDBProtocol"),
    "CursorProtocol": ("._indexeddb", "CursorProtocol"),
    "IndexedDBCursorSnapshot": ("._indexeddb", "IndexedDBCursorSnapshot"),
    "IndexedDBCursorSnapshotEntry": (
        "._indexeddb",
        "IndexedDBCursorSnapshotEntry",
    ),
    "ObjectStoreProtocol": ("._indexeddb", "ObjectStoreProtocol"),
    "IndexedDBOpenCursorRequest": ("._indexeddb", "IndexedDBOpenCursorRequest"),
    "TransactionProtocol": ("._indexeddb", "TransactionProtocol"),
    "TransactionIndexProtocol": ("._indexeddb", "TransactionIndexProtocol"),
    "TransactionObjectStoreProtocol": ("._indexeddb", "TransactionObjectStoreProtocol"),
    "IndexedDB": ("._indexeddb", "IndexedDB"),
    "IndexSchema": ("._indexeddb", "IndexSchema"),
    "KeyRange": ("._indexeddb", "KeyRange"),
    "ListOptions": ("._s3", "ListOptions"),
    "ListPage": ("._s3", "ListPage"),
    "MetadataProvider": ("._providers", "MetadataProvider"),
    "NotFoundError": ("._indexeddb", "NotFoundError"),
    "ObjectMeta": ("._s3", "ObjectMeta"),
    "ObjectAccessURL": ("._s3", "ObjectAccessURL"),
    "ObjectAccessURLOptions": ("._s3", "ObjectAccessURLOptions"),
    "ObjectRef": ("._s3", "ObjectRef"),
    "ObjectStore": ("._indexeddb", "ObjectStore"),
    "ObjectStoreSchema": ("._indexeddb", "ObjectStoreSchema"),
    "OperationAnnotations": ("._catalog", "OperationAnnotations"),
    "App": ("._app", "App"),
    "AppProtocol": ("._app_access", "AppProtocol"),
    "AppProvider": ("._providers", "AppProvider"),
    "AppProviderAdapter": ("._providers", "AppProviderAdapter"),
    "RuntimeProvider": ("._providers", "RuntimeProvider"),
    "PresignMethod": ("._s3", "PresignMethod"),
    "PresignOptions": ("._s3", "PresignOptions"),
    "PresignResult": ("._s3", "PresignResult"),
    "ProviderReadResult": ("._s3", "ProviderReadResult"),
    "ProviderKind": ("._providers", "ProviderKind"),
    "ProviderMetadata": ("._providers", "ProviderMetadata"),
    "ReadOptions": ("._s3", "ReadOptions"),
    "RuntimeLogHandler": ("._runtime_log_host", "RuntimeLogHandler"),
    "RuntimeLogHost": ("._runtime_log_host", "RuntimeLogHost"),
    "RuntimeLogWriter": ("._runtime_log_host", "RuntimeLogWriter"),
    "S3": ("._s3", "S3"),
    "S3Protocol": ("._s3", "S3Protocol"),
    "S3InvalidRangeError": ("._s3", "S3InvalidRangeError"),
    "S3NotFoundError": ("._s3", "S3NotFoundError"),
    "S3Object": ("._s3", "S3Object"),
    "S3ObjectProtocol": ("._s3", "S3ObjectProtocol"),
    "S3PreconditionFailedError": ("._s3", "S3PreconditionFailedError"),
    "S3Provider": ("._providers", "S3Provider"),
    "S3ReadStream": ("._s3", "S3ReadStream"),
    "SecretsProvider": ("._providers", "SecretsProvider"),
    "SessionCatalogProvider": ("._catalog", "SessionCatalogProvider"),
    "SessionTTLProvider": ("._providers", "SessionTTLProvider"),
    "Starter": ("._providers", "Starter"),
    "Transaction": ("._indexeddb", "Transaction"),
    "TransactionError": ("._indexeddb", "TransactionError"),
    "TransactionIndex": ("._indexeddb", "TransactionIndex"),
    "TransactionObjectStore": ("._indexeddb", "TransactionObjectStore"),
    "Workflow": ("._workflow", "Workflow"),
    "WorkflowProtocol": ("._workflow", "WorkflowProtocol"),
    "WarningsProvider": ("._providers", "WarningsProvider"),
    "WorkflowProvider": ("._providers", "WorkflowProvider"),
    "WriteOptions": ("._s3", "WriteOptions"),
    "compare_indexeddb_values": ("._indexeddb", "compare_indexeddb_values"),
    "http_subject": ("._app", "http_subject"),
    "http_subject_error": ("._http_subject", "http_subject_error"),
    "indexeddb_range_bounds": ("._indexeddb", "indexeddb_range_bounds"),
    "new_indexeddb_cursor_snapshot": (
        "._indexeddb",
        "new_indexeddb_cursor_snapshot",
    ),
    "operation": ("._app", "operation"),
    "session_catalog": ("._app", "session_catalog"),
}

_LAZY_EXPORTS.update({name: ("._agent", name) for name in _AGENT_PROTOCOL_EXPORTS})
_LAZY_EXPORTS.update({name: ("._agent", name) for name in _AGENT_HELPER_EXPORTS})
_LAZY_EXPORTS.update(
    {name: ("._authentication", name) for name in _AUTHENTICATION_AUTHORED_EXPORTS}
)
_LAZY_EXPORTS.update({name: ("._protocol", name) for name in _PROTOCOL_TYPE_EXPORTS})
_LAZY_EXPORTS.update(
    {name: ("._authorization", name) for name in _AUTHORIZATION_AUTHORED_EXPORTS}
)
_LAZY_EXPORTS.update(
    {name: ("._authorization", name) for name in _AUTHORIZATION_HELPER_EXPORTS}
)
_LAZY_EXPORTS.update(
    {name: ("._runtime_provider", name) for name in _RUNTIME_PROVIDER_AUTHORED_EXPORTS}
)
_LAZY_EXPORTS.update(
    {name: ("._workflow", name) for name in _WORKFLOW_AUTHORED_EXPORTS}
)
_LAZY_EXPORTS.update(
    {name: ("._workflow", name) for name in _WORKFLOW_HELPER_EXPORTS}
)

_LAZY_MODULES = {
    "telemetry": ".telemetry",
}


def __getattr__(name: str):
    module_name = _LAZY_MODULES.get(name)
    if module_name is not None:
        value = import_module(module_name, __name__)
        globals()[name] = value
        return value

    export = _LAZY_EXPORTS.get(name)
    if export is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr_name = export
    value = getattr(import_module(module_name, __name__), attr_name)
    globals()[name] = value
    return value


__all__ = [
    *_AGENT_PROTOCOL_EXPORTS,
    *_AGENT_HELPER_EXPORTS,
    *_AUTHENTICATION_AUTHORED_EXPORTS,
    *_PROTOCOL_TYPE_EXPORTS,
    *_AUTHORIZATION_AUTHORED_EXPORTS,
    *_AUTHORIZATION_HELPER_EXPORTS,
    *_RUNTIME_PROVIDER_AUTHORED_EXPORTS,
    *_WORKFLOW_AUTHORED_EXPORTS,
    *_WORKFLOW_HELPER_EXPORTS,
    "AgentHost",
    "Agent",
    "AgentProvider",
    "AlreadyExistsError",
    "AuthenticationProvider",
    "Authorization",
    "AuthorizationProtocol",
    "AuthorizationProvider",
    "Cache",
    "CacheEntry",
    "CacheProtocol",
    "CacheProvider",
    "ENV_HOST_SERVICE_SOCKET",
    "ENV_HOST_SERVICE_TOKEN",
    "HOST_SERVICE_BINDING_HEADER",
    "Access",
    "CURSOR_NEXT",
    "CURSOR_NEXT_UNIQUE",
    "CURSOR_PREV",
    "CURSOR_PREV_UNIQUE",
    "Catalog",
    "CatalogOperation",
    "CatalogParameter",
    "Credential",
    "Closer",
    "Cursor",
    "Error",
    "Catalog",
    "HealthChecker",
    "HTTPSubjectRequest",
    "HTTPSubjectResolutionError",
    "Host",
    "Index",
    "IndexProtocol",
    "IndexedDBProtocol",
    "CursorProtocol",
    "IndexedDBCursorSnapshot",
    "IndexedDBCursorSnapshotEntry",
    "ObjectStoreProtocol",
    "IndexedDBOpenCursorRequest",
    "TransactionProtocol",
    "TransactionIndexProtocol",
    "TransactionObjectStoreProtocol",
    "IndexedDB",
    "IndexSchema",
    "KeyRange",
    "ListOptions",
    "ListPage",
    "MetadataProvider",
    "Model",
    "NotFoundError",
    "OK",
    "ObjectMeta",
    "ObjectAccessURL",
    "ObjectAccessURLOptions",
    "ObjectRef",
    "ObjectStore",
    "ObjectStoreSchema",
    "OperationAnnotations",
    "App",
    "AppProtocol",
    "AppProvider",
    "AppProviderAdapter",
    "RuntimeProvider",
    "PresignMethod",
    "PresignOptions",
    "PresignResult",
    "ProviderReadResult",
    "ProviderKind",
    "ProviderMetadata",
    "Request",
    "Response",
    "ReadOptions",
    "RuntimeLogHandler",
    "RuntimeLogHost",
    "RuntimeLogWriter",
    "S3",
    "S3Protocol",
    "S3InvalidRangeError",
    "S3NotFoundError",
    "S3Object",
    "S3ObjectProtocol",
    "S3PreconditionFailedError",
    "S3Provider",
    "S3ReadStream",
    "SecretsProvider",
    "Subject",
    "SessionCatalogProvider",
    "SessionTTLProvider",
    "Starter",
    "Transaction",
    "TransactionError",
    "TransactionIndex",
    "TransactionObjectStore",
    "WorkflowProvider",
    "Workflow",
    "WarningsProvider",
    "compare_indexeddb_values",
    "WriteOptions",
    "ByteRange",
    "CopyOptions",
    "field",
    "http_subject",
    "http_subject_error",
    "indexeddb_range_bounds",
    "new_indexeddb_cursor_snapshot",
    "operation",
    "parse_subject_id",
    "session_catalog",
    "telemetry",
]
