# Code generated by sdkgen. DO NOT EDIT.

"""Generated provider SDK surface for authentication.proto."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, overload

import grpc
from google.protobuf import empty_pb2 as _empty_pb2

from ._codec import authentication as _codec
from ._codec import support as _support
from ._gen.v1 import authentication_pb2_grpc as _authentication_pb2_grpc

_empty: Any = _empty_pb2


@dataclass(frozen=True, slots=True)
class AuthSessionSettings:
    """AuthSessionSettings configures how the host persists authenticated sessions."""

    session_ttl_seconds: int = 0


@dataclass(frozen=True, slots=True)
class AuthenticatedUser:
    """AuthenticatedUser is the normalized user identity returned by an authentication
    provider after a login or token-validation flow.
    """

    subject: str = ""
    email: str = ""
    email_verified: bool = False
    display_name: str = ""
    avatar_url: str = ""
    claims: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class BeginLoginRequest:
    """BeginLoginRequest starts an interactive login flow."""

    #: callback_url is the host-managed URL the provider should redirect back to.
    callback_url: str = ""
    #: host_state is opaque state generated by the host and echoed back on
    #: completion.
    host_state: str = ""
    #: scopes are the provider-specific scopes the host is requesting.
    scopes: list[str] = field(default_factory=list)
    #: options carries provider-specific login parameters.
    options: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class BeginLoginResponse:
    """BeginLoginResponse returns the provider-managed authorization URL and opaque
    provider state that must be preserved until completion.
    """

    authorization_url: str = ""
    provider_state: bytes = b""


@dataclass(frozen=True, slots=True)
class CompleteLoginRequest:
    """CompleteLoginRequest finishes an interactive login flow."""

    #: query contains the callback URL query parameters returned by the identity
    #: provider.
    query: dict[str, str] = field(default_factory=dict)
    #: provider_state is the opaque state returned from BeginLoginResponse.
    provider_state: bytes = b""
    #: callback_url is the fully qualified callback URL used by the host.
    callback_url: str = ""


@dataclass(frozen=True, slots=True)
class ValidateExternalTokenRequest:
    """ValidateExternalTokenRequest asks the provider to validate a token minted
    outside the interactive login flow.
    """

    token: str = ""


class Authentication:
    """Authentication models the shared Gestalt authentication protocol.

    Client for the gestalt.provider.v1.Authentication service.
    """

    def __init__(self, channel: grpc.Channel, *, timeout: float | None = None) -> None:
        self._stub = _authentication_pb2_grpc.AuthenticationStub(channel)
        self._timeout = timeout

    @overload
    def begin_login(self, request: BeginLoginRequest) -> BeginLoginResponse: ...

    @overload
    def begin_login(
        self, *, callback_url: str = ..., host_state: str = ..., scopes: list[str] = ...
    ) -> BeginLoginResponse: ...

    def begin_login(
        self,
        request: BeginLoginRequest | None = None,
        *,
        callback_url: str | None = None,
        host_state: str | None = None,
        scopes: list[str] | None = None,
    ) -> BeginLoginResponse:
        if request is None:
            request = BeginLoginRequest(
                callback_url=callback_url or "",
                host_state=host_state or "",
                scopes=scopes if scopes is not None else [],
            )
        elif callback_url is not None or host_state is not None or scopes is not None:
            raise ValueError("pass either request or keyword arguments, not both")
        response = _support.call_unary(
            lambda: self._stub.BeginLogin(
                _codec.to_wire_begin_login_request(request), timeout=self._timeout
            )
        )
        return _codec.from_wire_begin_login_response(response)

    @overload
    def complete_login(self, request: CompleteLoginRequest) -> AuthenticatedUser: ...

    @overload
    def complete_login(
        self, *, provider_state: bytes = ..., callback_url: str = ...
    ) -> AuthenticatedUser: ...

    def complete_login(
        self,
        request: CompleteLoginRequest | None = None,
        *,
        provider_state: bytes | None = None,
        callback_url: str | None = None,
    ) -> AuthenticatedUser:
        if request is None:
            request = CompleteLoginRequest(
                provider_state=provider_state or b"", callback_url=callback_url or ""
            )
        elif provider_state is not None or callback_url is not None:
            raise ValueError("pass either request or keyword arguments, not both")
        response = _support.call_unary(
            lambda: self._stub.CompleteLogin(
                _codec.to_wire_complete_login_request(request), timeout=self._timeout
            )
        )
        return _codec.from_wire_authenticated_user(response)

    @overload
    def validate_external_token(
        self, request: ValidateExternalTokenRequest
    ) -> AuthenticatedUser: ...

    @overload
    def validate_external_token(self, *, token: str = ...) -> AuthenticatedUser: ...

    def validate_external_token(
        self,
        request: ValidateExternalTokenRequest | None = None,
        *,
        token: str | None = None,
    ) -> AuthenticatedUser:
        if request is None:
            request = ValidateExternalTokenRequest(token=token or "")
        elif token is not None:
            raise ValueError("pass either request or keyword arguments, not both")
        response = _support.call_unary(
            lambda: self._stub.ValidateExternalToken(
                _codec.to_wire_validate_external_token_request(request),
                timeout=self._timeout,
            )
        )
        return _codec.from_wire_authenticated_user(response)

    def get_session_settings(self) -> AuthSessionSettings:
        response = _support.call_unary(
            lambda: self._stub.GetSessionSettings(_empty.Empty(), timeout=self._timeout)
        )
        return _codec.from_wire_auth_session_settings(response)
