# Code generated by sdkgen. DO NOT EDIT.

"""Generated provider SDK surface for external_credential.proto."""

from __future__ import annotations

import datetime
from dataclasses import dataclass, field
from typing import Any

import grpc

from ._gen.v1 import external_credential_pb2 as _external_credential_pb2
from ._gen.v1 import external_credential_pb2_grpc as _external_credential_pb2_grpc
from .rpc_support import call_unary, from_wire_timestamp, to_wire_timestamp

_wire: Any = _external_credential_pb2
_wire_grpc: Any = _external_credential_pb2_grpc


@dataclass(frozen=True, slots=True)
class DeleteExternalCredentialRequest:
    id: str = ""


@dataclass(frozen=True, slots=True)
class ExchangeExternalCredentialRequest:
    provider: str = ""
    connection: str = ""
    connection_id: str = ""
    credential_subject_id: str = ""
    actor_subject_id: str = ""
    instance: str = ""
    auth: ExternalCredentialAuthConfig | None = None
    credential_json: str = ""
    connection_params: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class ExchangeExternalCredentialResponse:
    token_response: ExternalCredentialTokenResponse | None = None


@dataclass(frozen=True, slots=True)
class ExternalCredential:
    id: str = ""
    subject_id: str = ""
    instance: str = ""
    access_token: str = ""
    refresh_token: str = ""
    scopes: str = ""
    expires_at: datetime.datetime | None = None
    last_refreshed_at: datetime.datetime | None = None
    refresh_error_count: int = 0
    metadata_json: str = ""
    created_at: datetime.datetime | None = None
    updated_at: datetime.datetime | None = None
    connection_id: str = ""


@dataclass(frozen=True, slots=True)
class ExternalCredentialAuthConfig:
    type: str = ""
    token: str = ""
    token_prefix: str = ""
    grant_type: str = ""
    token_url: str = ""
    client_id: str = ""
    client_secret: str = ""
    client_auth: str = ""
    token_exchange: str = ""
    scopes: list[str] = field(default_factory=list)
    scope_param: str = ""
    scope_separator: str = ""
    token_params: dict[str, str] = field(default_factory=dict)
    refresh_params: dict[str, str] = field(default_factory=dict)
    accept_header: str = ""
    access_token_path: str = ""
    token_exchange_drivers: list[ExternalCredentialTokenExchangeDriver] = field(default_factory=list)
    refresh_token: str = ""


@dataclass(frozen=True, slots=True)
class ExternalCredentialLookup:
    subject_id: str = ""
    instance: str = ""
    connection_id: str = ""


@dataclass(frozen=True, slots=True)
class ExternalCredentialTokenExchangeDriver:
    type: str = ""
    target_principal: str = ""
    scopes: list[str] = field(default_factory=list)
    lifetime_seconds: int = 0
    endpoint: str = ""
    params: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class ExternalCredentialTokenResponse:
    access_token: str = ""
    refresh_token: str = ""
    expires_in: int = 0
    token_type: str = ""
    extra_json: str = ""
    refresh_source: str = ""


@dataclass(frozen=True, slots=True)
class GetExternalCredentialRequest:
    lookup: ExternalCredentialLookup | None = None


@dataclass(frozen=True, slots=True)
class ListExternalCredentialsRequest:
    subject_id: str = ""
    instance: str = ""
    connection_id: str = ""


@dataclass(frozen=True, slots=True)
class ListExternalCredentialsResponse:
    credentials: list[ExternalCredential] = field(default_factory=list)


@dataclass(frozen=True, slots=True)
class ResolveExternalCredentialRequest:
    provider: str = ""
    connection: str = ""
    connection_id: str = ""
    mode: str = ""
    credential_subject_id: str = ""
    actor_subject_id: str = ""
    instance: str = ""
    auth: ExternalCredentialAuthConfig | None = None
    connection_params: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class ResolveExternalCredentialResponse:
    token: str = ""
    expires_at: datetime.datetime | None = None
    metadata_json: str = ""
    params: dict[str, str] = field(default_factory=dict)
    credential: ExternalCredential | None = None


@dataclass(frozen=True, slots=True)
class UpsertExternalCredentialRequest:
    credential: ExternalCredential | None = None
    preserve_timestamps: bool = False


@dataclass(frozen=True, slots=True)
class ValidateExternalCredentialConfigRequest:
    provider: str = ""
    connection: str = ""
    connection_id: str = ""
    mode: str = ""
    auth: ExternalCredentialAuthConfig | None = None
    connection_params: dict[str, str] = field(default_factory=dict)


def to_wire_delete_external_credential_request(value: DeleteExternalCredentialRequest) -> Any:
    return _wire.DeleteExternalCredentialRequest(
        id=value.id,
    )


def from_wire_delete_external_credential_request(value: Any) -> DeleteExternalCredentialRequest:
    return DeleteExternalCredentialRequest(
        id=value.id,
    )


def to_wire_exchange_external_credential_request(value: ExchangeExternalCredentialRequest) -> Any:
    return _wire.ExchangeExternalCredentialRequest(
        provider=value.provider,
        connection=value.connection,
        connection_id=value.connection_id,
        credential_subject_id=value.credential_subject_id,
        actor_subject_id=value.actor_subject_id,
        instance=value.instance,
        auth=None if value.auth is None else to_wire_external_credential_auth_config(value.auth),
        credential_json=value.credential_json,
        connection_params=value.connection_params,
    )


def from_wire_exchange_external_credential_request(value: Any) -> ExchangeExternalCredentialRequest:
    return ExchangeExternalCredentialRequest(
        provider=value.provider,
        connection=value.connection,
        connection_id=value.connection_id,
        credential_subject_id=value.credential_subject_id,
        actor_subject_id=value.actor_subject_id,
        instance=value.instance,
        auth=from_wire_external_credential_auth_config(value.auth) if value.HasField("auth") else None,
        credential_json=value.credential_json,
        connection_params=dict(value.connection_params),
    )


def to_wire_exchange_external_credential_response(value: ExchangeExternalCredentialResponse) -> Any:
    return _wire.ExchangeExternalCredentialResponse(
        token_response=None if value.token_response is None else to_wire_external_credential_token_response(value.token_response),
    )


def from_wire_exchange_external_credential_response(value: Any) -> ExchangeExternalCredentialResponse:
    return ExchangeExternalCredentialResponse(
        token_response=from_wire_external_credential_token_response(value.token_response) if value.HasField("token_response") else None,
    )


def to_wire_external_credential(value: ExternalCredential) -> Any:
    return _wire.ExternalCredential(
        id=value.id,
        subject_id=value.subject_id,
        instance=value.instance,
        access_token=value.access_token,
        refresh_token=value.refresh_token,
        scopes=value.scopes,
        expires_at=None if value.expires_at is None else to_wire_timestamp(value.expires_at),
        last_refreshed_at=None if value.last_refreshed_at is None else to_wire_timestamp(value.last_refreshed_at),
        refresh_error_count=value.refresh_error_count,
        metadata_json=value.metadata_json,
        created_at=None if value.created_at is None else to_wire_timestamp(value.created_at),
        updated_at=None if value.updated_at is None else to_wire_timestamp(value.updated_at),
        connection_id=value.connection_id,
    )


def from_wire_external_credential(value: Any) -> ExternalCredential:
    return ExternalCredential(
        id=value.id,
        subject_id=value.subject_id,
        instance=value.instance,
        access_token=value.access_token,
        refresh_token=value.refresh_token,
        scopes=value.scopes,
        expires_at=from_wire_timestamp(value.expires_at) if value.HasField("expires_at") else None,
        last_refreshed_at=from_wire_timestamp(value.last_refreshed_at) if value.HasField("last_refreshed_at") else None,
        refresh_error_count=value.refresh_error_count,
        metadata_json=value.metadata_json,
        created_at=from_wire_timestamp(value.created_at) if value.HasField("created_at") else None,
        updated_at=from_wire_timestamp(value.updated_at) if value.HasField("updated_at") else None,
        connection_id=value.connection_id,
    )


def to_wire_external_credential_auth_config(value: ExternalCredentialAuthConfig) -> Any:
    return _wire.ExternalCredentialAuthConfig(
        type=value.type,
        token=value.token,
        token_prefix=value.token_prefix,
        grant_type=value.grant_type,
        token_url=value.token_url,
        client_id=value.client_id,
        client_secret=value.client_secret,
        client_auth=value.client_auth,
        token_exchange=value.token_exchange,
        scopes=value.scopes,
        scope_param=value.scope_param,
        scope_separator=value.scope_separator,
        token_params=value.token_params,
        refresh_params=value.refresh_params,
        accept_header=value.accept_header,
        access_token_path=value.access_token_path,
        token_exchange_drivers=[to_wire_external_credential_token_exchange_driver(item) for item in value.token_exchange_drivers],
        refresh_token=value.refresh_token,
    )


def from_wire_external_credential_auth_config(value: Any) -> ExternalCredentialAuthConfig:
    return ExternalCredentialAuthConfig(
        type=value.type,
        token=value.token,
        token_prefix=value.token_prefix,
        grant_type=value.grant_type,
        token_url=value.token_url,
        client_id=value.client_id,
        client_secret=value.client_secret,
        client_auth=value.client_auth,
        token_exchange=value.token_exchange,
        scopes=list(value.scopes),
        scope_param=value.scope_param,
        scope_separator=value.scope_separator,
        token_params=dict(value.token_params),
        refresh_params=dict(value.refresh_params),
        accept_header=value.accept_header,
        access_token_path=value.access_token_path,
        token_exchange_drivers=[from_wire_external_credential_token_exchange_driver(item) for item in value.token_exchange_drivers],
        refresh_token=value.refresh_token,
    )


def to_wire_external_credential_lookup(value: ExternalCredentialLookup) -> Any:
    return _wire.ExternalCredentialLookup(
        subject_id=value.subject_id,
        instance=value.instance,
        connection_id=value.connection_id,
    )


def from_wire_external_credential_lookup(value: Any) -> ExternalCredentialLookup:
    return ExternalCredentialLookup(
        subject_id=value.subject_id,
        instance=value.instance,
        connection_id=value.connection_id,
    )


def to_wire_external_credential_token_exchange_driver(value: ExternalCredentialTokenExchangeDriver) -> Any:
    return _wire.ExternalCredentialTokenExchangeDriver(
        type=value.type,
        target_principal=value.target_principal,
        scopes=value.scopes,
        lifetime_seconds=value.lifetime_seconds,
        endpoint=value.endpoint,
        params=value.params,
    )


def from_wire_external_credential_token_exchange_driver(value: Any) -> ExternalCredentialTokenExchangeDriver:
    return ExternalCredentialTokenExchangeDriver(
        type=value.type,
        target_principal=value.target_principal,
        scopes=list(value.scopes),
        lifetime_seconds=value.lifetime_seconds,
        endpoint=value.endpoint,
        params=dict(value.params),
    )


def to_wire_external_credential_token_response(value: ExternalCredentialTokenResponse) -> Any:
    return _wire.ExternalCredentialTokenResponse(
        access_token=value.access_token,
        refresh_token=value.refresh_token,
        expires_in=value.expires_in,
        token_type=value.token_type,
        extra_json=value.extra_json,
        refresh_source=value.refresh_source,
    )


def from_wire_external_credential_token_response(value: Any) -> ExternalCredentialTokenResponse:
    return ExternalCredentialTokenResponse(
        access_token=value.access_token,
        refresh_token=value.refresh_token,
        expires_in=value.expires_in,
        token_type=value.token_type,
        extra_json=value.extra_json,
        refresh_source=value.refresh_source,
    )


def to_wire_get_external_credential_request(value: GetExternalCredentialRequest) -> Any:
    return _wire.GetExternalCredentialRequest(
        lookup=None if value.lookup is None else to_wire_external_credential_lookup(value.lookup),
    )


def from_wire_get_external_credential_request(value: Any) -> GetExternalCredentialRequest:
    return GetExternalCredentialRequest(
        lookup=from_wire_external_credential_lookup(value.lookup) if value.HasField("lookup") else None,
    )


def to_wire_list_external_credentials_request(value: ListExternalCredentialsRequest) -> Any:
    return _wire.ListExternalCredentialsRequest(
        subject_id=value.subject_id,
        instance=value.instance,
        connection_id=value.connection_id,
    )


def from_wire_list_external_credentials_request(value: Any) -> ListExternalCredentialsRequest:
    return ListExternalCredentialsRequest(
        subject_id=value.subject_id,
        instance=value.instance,
        connection_id=value.connection_id,
    )


def to_wire_list_external_credentials_response(value: ListExternalCredentialsResponse) -> Any:
    return _wire.ListExternalCredentialsResponse(
        credentials=[to_wire_external_credential(item) for item in value.credentials],
    )


def from_wire_list_external_credentials_response(value: Any) -> ListExternalCredentialsResponse:
    return ListExternalCredentialsResponse(
        credentials=[from_wire_external_credential(item) for item in value.credentials],
    )


def to_wire_resolve_external_credential_request(value: ResolveExternalCredentialRequest) -> Any:
    return _wire.ResolveExternalCredentialRequest(
        provider=value.provider,
        connection=value.connection,
        connection_id=value.connection_id,
        mode=value.mode,
        credential_subject_id=value.credential_subject_id,
        actor_subject_id=value.actor_subject_id,
        instance=value.instance,
        auth=None if value.auth is None else to_wire_external_credential_auth_config(value.auth),
        connection_params=value.connection_params,
    )


def from_wire_resolve_external_credential_request(value: Any) -> ResolveExternalCredentialRequest:
    return ResolveExternalCredentialRequest(
        provider=value.provider,
        connection=value.connection,
        connection_id=value.connection_id,
        mode=value.mode,
        credential_subject_id=value.credential_subject_id,
        actor_subject_id=value.actor_subject_id,
        instance=value.instance,
        auth=from_wire_external_credential_auth_config(value.auth) if value.HasField("auth") else None,
        connection_params=dict(value.connection_params),
    )


def to_wire_resolve_external_credential_response(value: ResolveExternalCredentialResponse) -> Any:
    return _wire.ResolveExternalCredentialResponse(
        token=value.token,
        expires_at=None if value.expires_at is None else to_wire_timestamp(value.expires_at),
        metadata_json=value.metadata_json,
        params=value.params,
        credential=None if value.credential is None else to_wire_external_credential(value.credential),
    )


def from_wire_resolve_external_credential_response(value: Any) -> ResolveExternalCredentialResponse:
    return ResolveExternalCredentialResponse(
        token=value.token,
        expires_at=from_wire_timestamp(value.expires_at) if value.HasField("expires_at") else None,
        metadata_json=value.metadata_json,
        params=dict(value.params),
        credential=from_wire_external_credential(value.credential) if value.HasField("credential") else None,
    )


def to_wire_upsert_external_credential_request(value: UpsertExternalCredentialRequest) -> Any:
    return _wire.UpsertExternalCredentialRequest(
        credential=None if value.credential is None else to_wire_external_credential(value.credential),
        preserve_timestamps=value.preserve_timestamps,
    )


def from_wire_upsert_external_credential_request(value: Any) -> UpsertExternalCredentialRequest:
    return UpsertExternalCredentialRequest(
        credential=from_wire_external_credential(value.credential) if value.HasField("credential") else None,
        preserve_timestamps=value.preserve_timestamps,
    )


def to_wire_validate_external_credential_config_request(value: ValidateExternalCredentialConfigRequest) -> Any:
    return _wire.ValidateExternalCredentialConfigRequest(
        provider=value.provider,
        connection=value.connection,
        connection_id=value.connection_id,
        mode=value.mode,
        auth=None if value.auth is None else to_wire_external_credential_auth_config(value.auth),
        connection_params=value.connection_params,
    )


def from_wire_validate_external_credential_config_request(value: Any) -> ValidateExternalCredentialConfigRequest:
    return ValidateExternalCredentialConfigRequest(
        provider=value.provider,
        connection=value.connection,
        connection_id=value.connection_id,
        mode=value.mode,
        auth=from_wire_external_credential_auth_config(value.auth) if value.HasField("auth") else None,
        connection_params=dict(value.connection_params),
    )


class ExternalCredentials:
    """Client for the gestalt.provider.v1.ExternalCredentials service."""

    def __init__(self, channel: grpc.Channel) -> None:
        self._stub = _wire_grpc.ExternalCredentialsStub(channel)

    def upsert_credential(self, request: UpsertExternalCredentialRequest) -> ExternalCredential:
        response = call_unary(lambda: self._stub.UpsertCredential(to_wire_upsert_external_credential_request(request)))
        return from_wire_external_credential(response)

    def get_credential(self, request: GetExternalCredentialRequest) -> ExternalCredential:
        response = call_unary(lambda: self._stub.GetCredential(to_wire_get_external_credential_request(request)))
        return from_wire_external_credential(response)

    def list_credentials(self, request: ListExternalCredentialsRequest) -> ListExternalCredentialsResponse:
        response = call_unary(lambda: self._stub.ListCredentials(to_wire_list_external_credentials_request(request)))
        return from_wire_list_external_credentials_response(response)

    def delete_credential(self, request: DeleteExternalCredentialRequest) -> None:
        call_unary(lambda: self._stub.DeleteCredential(to_wire_delete_external_credential_request(request)))

    def validate_credential_config(self, request: ValidateExternalCredentialConfigRequest) -> None:
        call_unary(lambda: self._stub.ValidateCredentialConfig(to_wire_validate_external_credential_config_request(request)))

    def resolve_credential(self, request: ResolveExternalCredentialRequest) -> ResolveExternalCredentialResponse:
        response = call_unary(lambda: self._stub.ResolveCredential(to_wire_resolve_external_credential_request(request)))
        return from_wire_resolve_external_credential_response(response)

    def exchange_credential(self, request: ExchangeExternalCredentialRequest) -> ExchangeExternalCredentialResponse:
        response = call_unary(lambda: self._stub.ExchangeCredential(to_wire_exchange_external_credential_request(request)))
        return from_wire_exchange_external_credential_response(response)
