# Code generated by sdkgen. DO NOT EDIT.

"""Public support surface for generated Gestalt SDK clients: the canonical
error model and the native representations of well-known types that appear in
generated signatures. The call helpers and wire converters live in the
internal _codec package."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterator

JsonValue = bool | int | float | str | list["JsonValue"] | dict[str, "JsonValue"] | None
"""The native representation of a JSON value carried in structured payloads."""


@dataclass(frozen=True, slots=True)
class RpcStatus:
    """The native representation of google.rpc.Status carried in response
    payloads, mirroring the canonical error model."""

    code: int = 0
    message: str = ""


class GestaltErrorCode:
    """Canonical SDK error codes, drawn from the standard gRPC status codes."""

    CANCELED = 1
    UNKNOWN = 2
    INVALID_ARGUMENT = 3
    DEADLINE_EXCEEDED = 4
    NOT_FOUND = 5
    ALREADY_EXISTS = 6
    PERMISSION_DENIED = 7
    RESOURCE_EXHAUSTED = 8
    FAILED_PRECONDITION = 9
    ABORTED = 10
    OUT_OF_RANGE = 11
    UNIMPLEMENTED = 12
    INTERNAL = 13
    UNAVAILABLE = 14
    DATA_LOSS = 15
    UNAUTHENTICATED = 16


class GestaltError(Exception):
    """Canonical SDK error: one code, a message, and the underlying cause.
    Transport error types never appear in the public SDK surface."""

    def __init__(self, code: int, message: str) -> None:
        super().__init__(message)
        self.code = code
        self.message = message


class ByteStream(Iterator[bytes]):
    """Byte payload stream of a framed read.

    ``read`` buffers the remaining stream — mirroring boto3's
    ``StreamingBody.read`` — and consumes it, so each stream supports one
    buffering call.
    """

    def __init__(self, chunks: Iterator[bytes]) -> None:
        self._chunks = chunks

    def __iter__(self) -> Iterator[bytes]:
        return self

    def __next__(self) -> bytes:
        return next(self._chunks)

    def read(self) -> bytes:
        """Buffer the remaining payload chunks into one bytes value."""
        return b"".join(self._chunks)
