apiVersion: gestaltd.config/v3
server:
  public:
    port: 8080
  encryptionKey: "replace-with-64-hex-characters"
  providers:
    indexeddb: main
providers:
  indexeddb:
    main:
      source: https://github.com/valon-technologies/gestalt-providers/releases/download/indexeddb/relationaldb/v0.0.1-alpha.1/provider-release.yaml
      config:
        dsn: sqlite:///var/lib/gestaltd/gestalt.db
  ui:
    root:
      source: https://github.com/valon-technologies/gestalt-providers/releases/download/web/default/v0.0.1-alpha.1/provider-release.yaml
      path: /
  secrets:
    env:
      source: env
plugins:
  httpbin:
    displayName: HTTPBin
    source: https://github.com/valon-technologies/gestalt-providers/releases/download/plugins/httpbin/v0.0.1-alpha.1/provider-release.yaml
    allowedHosts:
      - httpbin.org
