// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Agent_CreateSession_FullMethodName      = "/gestalt.provider.v1.Agent/CreateSession"
	Agent_GetSession_FullMethodName         = "/gestalt.provider.v1.Agent/GetSession"
	Agent_ListSessions_FullMethodName       = "/gestalt.provider.v1.Agent/ListSessions"
	Agent_UpdateSession_FullMethodName      = "/gestalt.provider.v1.Agent/UpdateSession"
	Agent_CreateTurn_FullMethodName         = "/gestalt.provider.v1.Agent/CreateTurn"
	Agent_GetTurn_FullMethodName            = "/gestalt.provider.v1.Agent/GetTurn"
	Agent_ListTurns_FullMethodName          = "/gestalt.provider.v1.Agent/ListTurns"
	Agent_CancelTurn_FullMethodName         = "/gestalt.provider.v1.Agent/CancelTurn"
	Agent_ListTurnEvents_FullMethodName     = "/gestalt.provider.v1.Agent/ListTurnEvents"
	Agent_GetInteraction_FullMethodName     = "/gestalt.provider.v1.Agent/GetInteraction"
	Agent_ListInteractions_FullMethodName   = "/gestalt.provider.v1.Agent/ListInteractions"
	Agent_ResolveInteraction_FullMethodName = "/gestalt.provider.v1.Agent/ResolveInteraction"
	Agent_GetCapabilities_FullMethodName    = "/gestalt.provider.v1.Agent/GetCapabilities"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Agent is the authoritative agent data boundary. Read RPCs for
// sessions, turns, turn events, and interactions should use provider-owned
// control-plane state and should not require a live execution sandbox,
// pod-level transport, or cached tunnel.
type AgentClient interface {
	CreateSession(ctx context.Context, in *CreateAgentProviderSessionRequest, opts ...grpc.CallOption) (*AgentSession, error)
	GetSession(ctx context.Context, in *GetAgentProviderSessionRequest, opts ...grpc.CallOption) (*AgentSession, error)
	ListSessions(ctx context.Context, in *ListAgentProviderSessionsRequest, opts ...grpc.CallOption) (*ListAgentProviderSessionsResponse, error)
	UpdateSession(ctx context.Context, in *UpdateAgentProviderSessionRequest, opts ...grpc.CallOption) (*AgentSession, error)
	CreateTurn(ctx context.Context, in *CreateAgentProviderTurnRequest, opts ...grpc.CallOption) (*AgentTurn, error)
	GetTurn(ctx context.Context, in *GetAgentProviderTurnRequest, opts ...grpc.CallOption) (*AgentTurn, error)
	ListTurns(ctx context.Context, in *ListAgentProviderTurnsRequest, opts ...grpc.CallOption) (*ListAgentProviderTurnsResponse, error)
	CancelTurn(ctx context.Context, in *CancelAgentProviderTurnRequest, opts ...grpc.CallOption) (*AgentTurn, error)
	ListTurnEvents(ctx context.Context, in *ListAgentProviderTurnEventsRequest, opts ...grpc.CallOption) (*ListAgentProviderTurnEventsResponse, error)
	GetInteraction(ctx context.Context, in *GetAgentProviderInteractionRequest, opts ...grpc.CallOption) (*AgentInteraction, error)
	ListInteractions(ctx context.Context, in *ListAgentProviderInteractionsRequest, opts ...grpc.CallOption) (*ListAgentProviderInteractionsResponse, error)
	ResolveInteraction(ctx context.Context, in *ResolveAgentProviderInteractionRequest, opts ...grpc.CallOption) (*AgentInteraction, error)
	GetCapabilities(ctx context.Context, in *GetAgentProviderCapabilitiesRequest, opts ...grpc.CallOption) (*AgentProviderCapabilities, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) CreateSession(ctx context.Context, in *CreateAgentProviderSessionRequest, opts ...grpc.CallOption) (*AgentSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentSession)
	err := c.cc.Invoke(ctx, Agent_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetSession(ctx context.Context, in *GetAgentProviderSessionRequest, opts ...grpc.CallOption) (*AgentSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentSession)
	err := c.cc.Invoke(ctx, Agent_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListSessions(ctx context.Context, in *ListAgentProviderSessionsRequest, opts ...grpc.CallOption) (*ListAgentProviderSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentProviderSessionsResponse)
	err := c.cc.Invoke(ctx, Agent_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) UpdateSession(ctx context.Context, in *UpdateAgentProviderSessionRequest, opts ...grpc.CallOption) (*AgentSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentSession)
	err := c.cc.Invoke(ctx, Agent_UpdateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CreateTurn(ctx context.Context, in *CreateAgentProviderTurnRequest, opts ...grpc.CallOption) (*AgentTurn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentTurn)
	err := c.cc.Invoke(ctx, Agent_CreateTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetTurn(ctx context.Context, in *GetAgentProviderTurnRequest, opts ...grpc.CallOption) (*AgentTurn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentTurn)
	err := c.cc.Invoke(ctx, Agent_GetTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListTurns(ctx context.Context, in *ListAgentProviderTurnsRequest, opts ...grpc.CallOption) (*ListAgentProviderTurnsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentProviderTurnsResponse)
	err := c.cc.Invoke(ctx, Agent_ListTurns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CancelTurn(ctx context.Context, in *CancelAgentProviderTurnRequest, opts ...grpc.CallOption) (*AgentTurn, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentTurn)
	err := c.cc.Invoke(ctx, Agent_CancelTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListTurnEvents(ctx context.Context, in *ListAgentProviderTurnEventsRequest, opts ...grpc.CallOption) (*ListAgentProviderTurnEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentProviderTurnEventsResponse)
	err := c.cc.Invoke(ctx, Agent_ListTurnEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetInteraction(ctx context.Context, in *GetAgentProviderInteractionRequest, opts ...grpc.CallOption) (*AgentInteraction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentInteraction)
	err := c.cc.Invoke(ctx, Agent_GetInteraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ListInteractions(ctx context.Context, in *ListAgentProviderInteractionsRequest, opts ...grpc.CallOption) (*ListAgentProviderInteractionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentProviderInteractionsResponse)
	err := c.cc.Invoke(ctx, Agent_ListInteractions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ResolveInteraction(ctx context.Context, in *ResolveAgentProviderInteractionRequest, opts ...grpc.CallOption) (*AgentInteraction, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentInteraction)
	err := c.cc.Invoke(ctx, Agent_ResolveInteraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetCapabilities(ctx context.Context, in *GetAgentProviderCapabilitiesRequest, opts ...grpc.CallOption) (*AgentProviderCapabilities, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentProviderCapabilities)
	err := c.cc.Invoke(ctx, Agent_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
//
// Agent is the authoritative agent data boundary. Read RPCs for
// sessions, turns, turn events, and interactions should use provider-owned
// control-plane state and should not require a live execution sandbox,
// pod-level transport, or cached tunnel.
type AgentServer interface {
	CreateSession(context.Context, *CreateAgentProviderSessionRequest) (*AgentSession, error)
	GetSession(context.Context, *GetAgentProviderSessionRequest) (*AgentSession, error)
	ListSessions(context.Context, *ListAgentProviderSessionsRequest) (*ListAgentProviderSessionsResponse, error)
	UpdateSession(context.Context, *UpdateAgentProviderSessionRequest) (*AgentSession, error)
	CreateTurn(context.Context, *CreateAgentProviderTurnRequest) (*AgentTurn, error)
	GetTurn(context.Context, *GetAgentProviderTurnRequest) (*AgentTurn, error)
	ListTurns(context.Context, *ListAgentProviderTurnsRequest) (*ListAgentProviderTurnsResponse, error)
	CancelTurn(context.Context, *CancelAgentProviderTurnRequest) (*AgentTurn, error)
	ListTurnEvents(context.Context, *ListAgentProviderTurnEventsRequest) (*ListAgentProviderTurnEventsResponse, error)
	GetInteraction(context.Context, *GetAgentProviderInteractionRequest) (*AgentInteraction, error)
	ListInteractions(context.Context, *ListAgentProviderInteractionsRequest) (*ListAgentProviderInteractionsResponse, error)
	ResolveInteraction(context.Context, *ResolveAgentProviderInteractionRequest) (*AgentInteraction, error)
	GetCapabilities(context.Context, *GetAgentProviderCapabilitiesRequest) (*AgentProviderCapabilities, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) CreateSession(context.Context, *CreateAgentProviderSessionRequest) (*AgentSession, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedAgentServer) GetSession(context.Context, *GetAgentProviderSessionRequest) (*AgentSession, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedAgentServer) ListSessions(context.Context, *ListAgentProviderSessionsRequest) (*ListAgentProviderSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedAgentServer) UpdateSession(context.Context, *UpdateAgentProviderSessionRequest) (*AgentSession, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSession not implemented")
}
func (UnimplementedAgentServer) CreateTurn(context.Context, *CreateAgentProviderTurnRequest) (*AgentTurn, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTurn not implemented")
}
func (UnimplementedAgentServer) GetTurn(context.Context, *GetAgentProviderTurnRequest) (*AgentTurn, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTurn not implemented")
}
func (UnimplementedAgentServer) ListTurns(context.Context, *ListAgentProviderTurnsRequest) (*ListAgentProviderTurnsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTurns not implemented")
}
func (UnimplementedAgentServer) CancelTurn(context.Context, *CancelAgentProviderTurnRequest) (*AgentTurn, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTurn not implemented")
}
func (UnimplementedAgentServer) ListTurnEvents(context.Context, *ListAgentProviderTurnEventsRequest) (*ListAgentProviderTurnEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTurnEvents not implemented")
}
func (UnimplementedAgentServer) GetInteraction(context.Context, *GetAgentProviderInteractionRequest) (*AgentInteraction, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInteraction not implemented")
}
func (UnimplementedAgentServer) ListInteractions(context.Context, *ListAgentProviderInteractionsRequest) (*ListAgentProviderInteractionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInteractions not implemented")
}
func (UnimplementedAgentServer) ResolveInteraction(context.Context, *ResolveAgentProviderInteractionRequest) (*AgentInteraction, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveInteraction not implemented")
}
func (UnimplementedAgentServer) GetCapabilities(context.Context, *GetAgentProviderCapabilitiesRequest) (*AgentProviderCapabilities, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call panics, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentProviderSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CreateSession(ctx, req.(*CreateAgentProviderSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentProviderSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetSession(ctx, req.(*GetAgentProviderSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentProviderSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListSessions(ctx, req.(*ListAgentProviderSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAgentProviderSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_UpdateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).UpdateSession(ctx, req.(*UpdateAgentProviderSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CreateTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentProviderTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CreateTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_CreateTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CreateTurn(ctx, req.(*CreateAgentProviderTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentProviderTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetTurn(ctx, req.(*GetAgentProviderTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListTurns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentProviderTurnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListTurns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListTurns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListTurns(ctx, req.(*ListAgentProviderTurnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CancelTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAgentProviderTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CancelTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_CancelTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CancelTurn(ctx, req.(*CancelAgentProviderTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListTurnEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentProviderTurnEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListTurnEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListTurnEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListTurnEvents(ctx, req.(*ListAgentProviderTurnEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentProviderInteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetInteraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetInteraction(ctx, req.(*GetAgentProviderInteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ListInteractions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentProviderInteractionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ListInteractions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ListInteractions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ListInteractions(ctx, req.(*ListAgentProviderInteractionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ResolveInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveAgentProviderInteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ResolveInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ResolveInteraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ResolveInteraction(ctx, req.(*ResolveAgentProviderInteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentProviderCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetCapabilities(ctx, req.(*GetAgentProviderCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gestalt.provider.v1.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _Agent_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _Agent_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _Agent_ListSessions_Handler,
		},
		{
			MethodName: "UpdateSession",
			Handler:    _Agent_UpdateSession_Handler,
		},
		{
			MethodName: "CreateTurn",
			Handler:    _Agent_CreateTurn_Handler,
		},
		{
			MethodName: "GetTurn",
			Handler:    _Agent_GetTurn_Handler,
		},
		{
			MethodName: "ListTurns",
			Handler:    _Agent_ListTurns_Handler,
		},
		{
			MethodName: "CancelTurn",
			Handler:    _Agent_CancelTurn_Handler,
		},
		{
			MethodName: "ListTurnEvents",
			Handler:    _Agent_ListTurnEvents_Handler,
		},
		{
			MethodName: "GetInteraction",
			Handler:    _Agent_GetInteraction_Handler,
		},
		{
			MethodName: "ListInteractions",
			Handler:    _Agent_ListInteractions_Handler,
		},
		{
			MethodName: "ResolveInteraction",
			Handler:    _Agent_ResolveInteraction_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _Agent_GetCapabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/agent.proto",
}
