// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: v1/runtime_provider.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Runtime_GetSupport_FullMethodName       = "/gestalt.provider.v1.Runtime/GetSupport"
	Runtime_StartSession_FullMethodName     = "/gestalt.provider.v1.Runtime/StartSession"
	Runtime_GetSession_FullMethodName       = "/gestalt.provider.v1.Runtime/GetSession"
	Runtime_ListSessions_FullMethodName     = "/gestalt.provider.v1.Runtime/ListSessions"
	Runtime_StopSession_FullMethodName      = "/gestalt.provider.v1.Runtime/StopSession"
	Runtime_PrepareWorkspace_FullMethodName = "/gestalt.provider.v1.Runtime/PrepareWorkspace"
	Runtime_RemoveWorkspace_FullMethodName  = "/gestalt.provider.v1.Runtime/RemoveWorkspace"
	Runtime_StartApp_FullMethodName         = "/gestalt.provider.v1.Runtime/StartApp"
)

// RuntimeClient is the client API for Runtime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RuntimeClient interface {
	GetSupport(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeSupport, error)
	StartSession(ctx context.Context, in *StartRuntimeSessionRequest, opts ...grpc.CallOption) (*RuntimeSession, error)
	GetSession(ctx context.Context, in *GetRuntimeSessionRequest, opts ...grpc.CallOption) (*RuntimeSession, error)
	ListSessions(ctx context.Context, in *ListRuntimeSessionsRequest, opts ...grpc.CallOption) (*ListRuntimeSessionsResponse, error)
	StopSession(ctx context.Context, in *StopRuntimeSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PrepareWorkspace(ctx context.Context, in *PrepareRuntimeWorkspaceRequest, opts ...grpc.CallOption) (*PrepareRuntimeWorkspaceResponse, error)
	RemoveWorkspace(ctx context.Context, in *RemoveRuntimeWorkspaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StartApp(ctx context.Context, in *StartHostedAppRequest, opts ...grpc.CallOption) (*HostedApp, error)
}

type runtimeClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeClient(cc grpc.ClientConnInterface) RuntimeClient {
	return &runtimeClient{cc}
}

func (c *runtimeClient) GetSupport(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RuntimeSupport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeSupport)
	err := c.cc.Invoke(ctx, Runtime_GetSupport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) StartSession(ctx context.Context, in *StartRuntimeSessionRequest, opts ...grpc.CallOption) (*RuntimeSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeSession)
	err := c.cc.Invoke(ctx, Runtime_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) GetSession(ctx context.Context, in *GetRuntimeSessionRequest, opts ...grpc.CallOption) (*RuntimeSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RuntimeSession)
	err := c.cc.Invoke(ctx, Runtime_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) ListSessions(ctx context.Context, in *ListRuntimeSessionsRequest, opts ...grpc.CallOption) (*ListRuntimeSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRuntimeSessionsResponse)
	err := c.cc.Invoke(ctx, Runtime_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) StopSession(ctx context.Context, in *StopRuntimeSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Runtime_StopSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) PrepareWorkspace(ctx context.Context, in *PrepareRuntimeWorkspaceRequest, opts ...grpc.CallOption) (*PrepareRuntimeWorkspaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareRuntimeWorkspaceResponse)
	err := c.cc.Invoke(ctx, Runtime_PrepareWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) RemoveWorkspace(ctx context.Context, in *RemoveRuntimeWorkspaceRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Runtime_RemoveWorkspace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeClient) StartApp(ctx context.Context, in *StartHostedAppRequest, opts ...grpc.CallOption) (*HostedApp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostedApp)
	err := c.cc.Invoke(ctx, Runtime_StartApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeServer is the server API for Runtime service.
// All implementations must embed UnimplementedRuntimeServer
// for forward compatibility.
type RuntimeServer interface {
	GetSupport(context.Context, *emptypb.Empty) (*RuntimeSupport, error)
	StartSession(context.Context, *StartRuntimeSessionRequest) (*RuntimeSession, error)
	GetSession(context.Context, *GetRuntimeSessionRequest) (*RuntimeSession, error)
	ListSessions(context.Context, *ListRuntimeSessionsRequest) (*ListRuntimeSessionsResponse, error)
	StopSession(context.Context, *StopRuntimeSessionRequest) (*emptypb.Empty, error)
	PrepareWorkspace(context.Context, *PrepareRuntimeWorkspaceRequest) (*PrepareRuntimeWorkspaceResponse, error)
	RemoveWorkspace(context.Context, *RemoveRuntimeWorkspaceRequest) (*emptypb.Empty, error)
	StartApp(context.Context, *StartHostedAppRequest) (*HostedApp, error)
	mustEmbedUnimplementedRuntimeServer()
}

// UnimplementedRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeServer struct{}

func (UnimplementedRuntimeServer) GetSupport(context.Context, *emptypb.Empty) (*RuntimeSupport, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupport not implemented")
}
func (UnimplementedRuntimeServer) StartSession(context.Context, *StartRuntimeSessionRequest) (*RuntimeSession, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedRuntimeServer) GetSession(context.Context, *GetRuntimeSessionRequest) (*RuntimeSession, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedRuntimeServer) ListSessions(context.Context, *ListRuntimeSessionsRequest) (*ListRuntimeSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedRuntimeServer) StopSession(context.Context, *StopRuntimeSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method StopSession not implemented")
}
func (UnimplementedRuntimeServer) PrepareWorkspace(context.Context, *PrepareRuntimeWorkspaceRequest) (*PrepareRuntimeWorkspaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareWorkspace not implemented")
}
func (UnimplementedRuntimeServer) RemoveWorkspace(context.Context, *RemoveRuntimeWorkspaceRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWorkspace not implemented")
}
func (UnimplementedRuntimeServer) StartApp(context.Context, *StartHostedAppRequest) (*HostedApp, error) {
	return nil, status.Error(codes.Unimplemented, "method StartApp not implemented")
}
func (UnimplementedRuntimeServer) mustEmbedUnimplementedRuntimeServer() {}
func (UnimplementedRuntimeServer) testEmbeddedByValue()                 {}

// UnsafeRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeServer will
// result in compilation errors.
type UnsafeRuntimeServer interface {
	mustEmbedUnimplementedRuntimeServer()
}

func RegisterRuntimeServer(s grpc.ServiceRegistrar, srv RuntimeServer) {
	// If the following call panics, it indicates UnimplementedRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Runtime_ServiceDesc, srv)
}

func _Runtime_GetSupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).GetSupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_GetSupport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).GetSupport(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRuntimeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).StartSession(ctx, req.(*StartRuntimeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).GetSession(ctx, req.(*GetRuntimeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRuntimeSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).ListSessions(ctx, req.(*ListRuntimeSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_StopSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRuntimeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).StopSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_StopSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).StopSession(ctx, req.(*StopRuntimeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_PrepareWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareRuntimeWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).PrepareWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_PrepareWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).PrepareWorkspace(ctx, req.(*PrepareRuntimeWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_RemoveWorkspace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRuntimeWorkspaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).RemoveWorkspace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_RemoveWorkspace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).RemoveWorkspace(ctx, req.(*RemoveRuntimeWorkspaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Runtime_StartApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartHostedAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeServer).StartApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Runtime_StartApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeServer).StartApp(ctx, req.(*StartHostedAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Runtime_ServiceDesc is the grpc.ServiceDesc for Runtime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Runtime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gestalt.provider.v1.Runtime",
	HandlerType: (*RuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSupport",
			Handler:    _Runtime_GetSupport_Handler,
		},
		{
			MethodName: "StartSession",
			Handler:    _Runtime_StartSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _Runtime_GetSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _Runtime_ListSessions_Handler,
		},
		{
			MethodName: "StopSession",
			Handler:    _Runtime_StopSession_Handler,
		},
		{
			MethodName: "PrepareWorkspace",
			Handler:    _Runtime_PrepareWorkspace_Handler,
		},
		{
			MethodName: "RemoveWorkspace",
			Handler:    _Runtime_RemoveWorkspace_Handler,
		},
		{
			MethodName: "StartApp",
			Handler:    _Runtime_StartApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/runtime_provider.proto",
}
