config:
  server:
    baseUrl: "https://gestalt.example.com"
    encryptionKey: "ci-test-encryption-key"
  auth:
    config:
      clientId: "ci-test-client-id"
      clientSecret: "ci-test-client-secret"

image:
  tag: "ci-test"

preparation:
  enabled: true
