// Code generated by sdkgen. DO NOT EDIT.

package client

import (
	proto "github.com/valon-technologies/gestalt/server/rpc/protov1/v1"
)

func ToWireAuthSessionSettings(value *AuthSessionSettings) *proto.AuthSessionSettings {
	if value == nil {
		return nil
	}
	out := &proto.AuthSessionSettings{
		SessionTtlSeconds: value.SessionTtlSeconds,
	}
	return out
}

func FromWireAuthSessionSettings(value *proto.AuthSessionSettings) *AuthSessionSettings {
	if value == nil {
		return nil
	}
	out := &AuthSessionSettings{
		SessionTtlSeconds: value.SessionTtlSeconds,
	}
	return out
}

func ToWireAuthenticatedUser(value *AuthenticatedUser) *proto.AuthenticatedUser {
	if value == nil {
		return nil
	}
	out := &proto.AuthenticatedUser{
		Subject:       value.Subject,
		Email:         value.Email,
		EmailVerified: value.EmailVerified,
		DisplayName:   value.DisplayName,
		AvatarUrl:     value.AvatarUrl,
		Claims:        value.Claims,
	}
	return out
}

func FromWireAuthenticatedUser(value *proto.AuthenticatedUser) *AuthenticatedUser {
	if value == nil {
		return nil
	}
	out := &AuthenticatedUser{
		Subject:       value.Subject,
		Email:         value.Email,
		EmailVerified: value.EmailVerified,
		DisplayName:   value.DisplayName,
		AvatarUrl:     value.AvatarUrl,
		Claims:        value.Claims,
	}
	return out
}

func ToWireBeginLoginRequest(value *BeginLoginRequest) *proto.BeginLoginRequest {
	if value == nil {
		return nil
	}
	out := &proto.BeginLoginRequest{
		CallbackUrl: value.CallbackUrl,
		HostState:   value.HostState,
		Scopes:      value.Scopes,
		Options:     value.Options,
	}
	return out
}

func FromWireBeginLoginRequest(value *proto.BeginLoginRequest) *BeginLoginRequest {
	if value == nil {
		return nil
	}
	out := &BeginLoginRequest{
		CallbackUrl: value.CallbackUrl,
		HostState:   value.HostState,
		Scopes:      value.Scopes,
		Options:     value.Options,
	}
	return out
}

func ToWireBeginLoginResponse(value *BeginLoginResponse) *proto.BeginLoginResponse {
	if value == nil {
		return nil
	}
	out := &proto.BeginLoginResponse{
		AuthorizationUrl: value.AuthorizationUrl,
		ProviderState:    value.ProviderState,
	}
	return out
}

func FromWireBeginLoginResponse(value *proto.BeginLoginResponse) *BeginLoginResponse {
	if value == nil {
		return nil
	}
	out := &BeginLoginResponse{
		AuthorizationUrl: value.AuthorizationUrl,
		ProviderState:    value.ProviderState,
	}
	return out
}

func ToWireCompleteLoginRequest(value *CompleteLoginRequest) *proto.CompleteLoginRequest {
	if value == nil {
		return nil
	}
	out := &proto.CompleteLoginRequest{
		Query:         value.Query,
		ProviderState: value.ProviderState,
		CallbackUrl:   value.CallbackUrl,
	}
	return out
}

func FromWireCompleteLoginRequest(value *proto.CompleteLoginRequest) *CompleteLoginRequest {
	if value == nil {
		return nil
	}
	out := &CompleteLoginRequest{
		Query:         value.Query,
		ProviderState: value.ProviderState,
		CallbackUrl:   value.CallbackUrl,
	}
	return out
}

func ToWireValidateExternalTokenRequest(value *ValidateExternalTokenRequest) *proto.ValidateExternalTokenRequest {
	if value == nil {
		return nil
	}
	out := &proto.ValidateExternalTokenRequest{
		Token: value.Token,
	}
	return out
}

func FromWireValidateExternalTokenRequest(value *proto.ValidateExternalTokenRequest) *ValidateExternalTokenRequest {
	if value == nil {
		return nil
	}
	out := &ValidateExternalTokenRequest{
		Token: value.Token,
	}
	return out
}
