// Code generated by sdkgen. DO NOT EDIT.

package client

import (
	"context"

	proto "github.com/valon-technologies/gestalt/server/rpc/protov1/v1"
	"google.golang.org/protobuf/types/known/emptypb"
)

// CacheProvider is the handler interface implemented by providers serving
// the gestalt.provider.v1.Cache service. Methods receive the full native request;
// wire conversion and error mapping live in the generated adapter (see
// [NewCacheProviderServer]). Embed [UnimplementedCacheProvider] to default
// unimplemented methods.
//
// Cache models the shared Gestalt cache-provider protocol.
type CacheProvider interface {
	// Get handles the Get RPC.
	Get(ctx context.Context, request *CacheGetRequest) (*CacheGetResponse, error)
	// GetMany handles the GetMany RPC.
	GetMany(ctx context.Context, request *CacheGetManyRequest) (*CacheGetManyResponse, error)
	// Set handles the Set RPC.
	Set(ctx context.Context, request *CacheSetRequest) error
	// SetMany handles the SetMany RPC.
	SetMany(ctx context.Context, request *CacheSetManyRequest) error
	// Delete handles the Delete RPC.
	Delete(ctx context.Context, request *CacheDeleteRequest) (*CacheDeleteResponse, error)
	// DeleteMany handles the DeleteMany RPC.
	DeleteMany(ctx context.Context, request *CacheDeleteManyRequest) (*CacheDeleteManyResponse, error)
	// Touch handles the Touch RPC.
	Touch(ctx context.Context, request *CacheTouchRequest) (*CacheTouchResponse, error)
}

// UnimplementedCacheProvider fails every CacheProvider method with a
// GestaltErrorCodeUnimplemented error; embed it to default the methods a
// provider does not implement.
type UnimplementedCacheProvider struct{}

// Get returns Unimplemented; embed UnimplementedCacheProvider to default
// unimplemented handler methods.
func (UnimplementedCacheProvider) Get(context.Context, *CacheGetRequest) (*CacheGetResponse, error) {
	return nil, &GestaltError{Code: GestaltErrorCodeUnimplemented, Message: "cache get is not implemented"}
}

// GetMany returns Unimplemented; embed UnimplementedCacheProvider to default
// unimplemented handler methods.
func (UnimplementedCacheProvider) GetMany(context.Context, *CacheGetManyRequest) (*CacheGetManyResponse, error) {
	return nil, &GestaltError{Code: GestaltErrorCodeUnimplemented, Message: "cache get many is not implemented"}
}

// Set returns Unimplemented; embed UnimplementedCacheProvider to default
// unimplemented handler methods.
func (UnimplementedCacheProvider) Set(context.Context, *CacheSetRequest) error {
	return &GestaltError{Code: GestaltErrorCodeUnimplemented, Message: "cache set is not implemented"}
}

// SetMany returns Unimplemented; embed UnimplementedCacheProvider to default
// unimplemented handler methods.
func (UnimplementedCacheProvider) SetMany(context.Context, *CacheSetManyRequest) error {
	return &GestaltError{Code: GestaltErrorCodeUnimplemented, Message: "cache set many is not implemented"}
}

// Delete returns Unimplemented; embed UnimplementedCacheProvider to default
// unimplemented handler methods.
func (UnimplementedCacheProvider) Delete(context.Context, *CacheDeleteRequest) (*CacheDeleteResponse, error) {
	return nil, &GestaltError{Code: GestaltErrorCodeUnimplemented, Message: "cache delete is not implemented"}
}

// DeleteMany returns Unimplemented; embed UnimplementedCacheProvider to default
// unimplemented handler methods.
func (UnimplementedCacheProvider) DeleteMany(context.Context, *CacheDeleteManyRequest) (*CacheDeleteManyResponse, error) {
	return nil, &GestaltError{Code: GestaltErrorCodeUnimplemented, Message: "cache delete many is not implemented"}
}

// Touch returns Unimplemented; embed UnimplementedCacheProvider to default
// unimplemented handler methods.
func (UnimplementedCacheProvider) Touch(context.Context, *CacheTouchRequest) (*CacheTouchResponse, error) {
	return nil, &GestaltError{Code: GestaltErrorCodeUnimplemented, Message: "cache touch is not implemented"}
}

// NewCacheProviderServer adapts provider to the wire-level
// [proto.CacheServer]: requests convert from the wire, responses convert to
// the wire, and handler errors map to gRPC statuses.
func NewCacheProviderServer(provider CacheProvider) proto.CacheServer {
	return &cacheProviderServer{provider: provider}
}

type cacheProviderServer struct {
	proto.UnimplementedCacheServer
	provider CacheProvider
}

func (s *cacheProviderServer) Get(ctx context.Context, request *proto.CacheGetRequest) (*proto.CacheGetResponse, error) {
	response, err := s.provider.Get(ctx, fromWireCacheGetRequest(request))
	if err != nil {
		return nil, statusError("cache get", err)
	}
	return toWireCacheGetResponse(response), nil
}

func (s *cacheProviderServer) GetMany(ctx context.Context, request *proto.CacheGetManyRequest) (*proto.CacheGetManyResponse, error) {
	response, err := s.provider.GetMany(ctx, fromWireCacheGetManyRequest(request))
	if err != nil {
		return nil, statusError("cache get many", err)
	}
	return toWireCacheGetManyResponse(response), nil
}

func (s *cacheProviderServer) Set(ctx context.Context, request *proto.CacheSetRequest) (*emptypb.Empty, error) {
	if err := s.provider.Set(ctx, fromWireCacheSetRequest(request)); err != nil {
		return nil, statusError("cache set", err)
	}
	return &emptypb.Empty{}, nil
}

func (s *cacheProviderServer) SetMany(ctx context.Context, request *proto.CacheSetManyRequest) (*emptypb.Empty, error) {
	if err := s.provider.SetMany(ctx, fromWireCacheSetManyRequest(request)); err != nil {
		return nil, statusError("cache set many", err)
	}
	return &emptypb.Empty{}, nil
}

func (s *cacheProviderServer) Delete(ctx context.Context, request *proto.CacheDeleteRequest) (*proto.CacheDeleteResponse, error) {
	response, err := s.provider.Delete(ctx, fromWireCacheDeleteRequest(request))
	if err != nil {
		return nil, statusError("cache delete", err)
	}
	return toWireCacheDeleteResponse(response), nil
}

func (s *cacheProviderServer) DeleteMany(ctx context.Context, request *proto.CacheDeleteManyRequest) (*proto.CacheDeleteManyResponse, error) {
	response, err := s.provider.DeleteMany(ctx, fromWireCacheDeleteManyRequest(request))
	if err != nil {
		return nil, statusError("cache delete many", err)
	}
	return toWireCacheDeleteManyResponse(response), nil
}

func (s *cacheProviderServer) Touch(ctx context.Context, request *proto.CacheTouchRequest) (*proto.CacheTouchResponse, error) {
	response, err := s.provider.Touch(ctx, fromWireCacheTouchRequest(request))
	if err != nil {
		return nil, statusError("cache touch", err)
	}
	return toWireCacheTouchResponse(response), nil
}
