// Code generated by sdkgen. DO NOT EDIT.

package client

import (
	"context"
	"time"

	"github.com/valon-technologies/gestalt/sdk/go/internal/host"
	proto "github.com/valon-technologies/gestalt/server/rpc/protov1/v1"
	"google.golang.org/grpc"
)

// CreateExternalCredentialRequest is the native message type for gestalt.provider.v1.CreateExternalCredentialRequest.
type CreateExternalCredentialRequest struct {
	Credential *ExternalCredential
}

// GetCredential returns the credential field; it is safe to call on a nil receiver.
func (x *CreateExternalCredentialRequest) GetCredential() *ExternalCredential {
	if x == nil {
		return nil
	}
	return x.Credential
}

// DeleteExternalCredentialRequest is the native message type for gestalt.provider.v1.DeleteExternalCredentialRequest.
type DeleteExternalCredentialRequest struct {
	ID string
}

// GetID returns the id field; it is safe to call on a nil receiver.
func (x *DeleteExternalCredentialRequest) GetID() string {
	if x == nil {
		return ""
	}
	return x.ID
}

// ExchangeExternalCredentialRequest is the native message type for gestalt.provider.v1.ExchangeExternalCredentialRequest.
type ExchangeExternalCredentialRequest struct {
	Provider            string
	Connection          string
	ConnectionID        string
	CredentialSubjectID string
	ActorSubjectID      string
	Instance            string
	Auth                *ExternalCredentialAuthConfig
	CredentialJSON      string
	ConnectionParams    map[string]string
}

// GetProvider returns the provider field; it is safe to call on a nil receiver.
func (x *ExchangeExternalCredentialRequest) GetProvider() string {
	if x == nil {
		return ""
	}
	return x.Provider
}

// GetConnection returns the connection field; it is safe to call on a nil receiver.
func (x *ExchangeExternalCredentialRequest) GetConnection() string {
	if x == nil {
		return ""
	}
	return x.Connection
}

// GetConnectionID returns the connectionId field; it is safe to call on a nil receiver.
func (x *ExchangeExternalCredentialRequest) GetConnectionID() string {
	if x == nil {
		return ""
	}
	return x.ConnectionID
}

// GetCredentialSubjectID returns the credentialSubjectId field; it is safe to call on a nil receiver.
func (x *ExchangeExternalCredentialRequest) GetCredentialSubjectID() string {
	if x == nil {
		return ""
	}
	return x.CredentialSubjectID
}

// GetActorSubjectID returns the actorSubjectId field; it is safe to call on a nil receiver.
func (x *ExchangeExternalCredentialRequest) GetActorSubjectID() string {
	if x == nil {
		return ""
	}
	return x.ActorSubjectID
}

// GetInstance returns the instance field; it is safe to call on a nil receiver.
func (x *ExchangeExternalCredentialRequest) GetInstance() string {
	if x == nil {
		return ""
	}
	return x.Instance
}

// GetAuth returns the auth field; it is safe to call on a nil receiver.
func (x *ExchangeExternalCredentialRequest) GetAuth() *ExternalCredentialAuthConfig {
	if x == nil {
		return nil
	}
	return x.Auth
}

// GetCredentialJSON returns the credentialJson field; it is safe to call on a nil receiver.
func (x *ExchangeExternalCredentialRequest) GetCredentialJSON() string {
	if x == nil {
		return ""
	}
	return x.CredentialJSON
}

// GetConnectionParams returns the connectionParams field; it is safe to call on a nil receiver.
func (x *ExchangeExternalCredentialRequest) GetConnectionParams() map[string]string {
	if x == nil {
		return nil
	}
	return x.ConnectionParams
}

// ExchangeExternalCredentialResponse is the native message type for gestalt.provider.v1.ExchangeExternalCredentialResponse.
type ExchangeExternalCredentialResponse struct {
	TokenResponse *ExternalCredentialTokenResponse
}

// GetTokenResponse returns the tokenResponse field; it is safe to call on a nil receiver.
func (x *ExchangeExternalCredentialResponse) GetTokenResponse() *ExternalCredentialTokenResponse {
	if x == nil {
		return nil
	}
	return x.TokenResponse
}

// ExternalCredentialCredential selects one variant of the credential oneof of ExternalCredential.
// A nil value means unset.
type ExternalCredentialCredential interface {
	isExternalCredentialCredential()
}

// ExternalCredentialCredentialGrant is the grant variant.
type ExternalCredentialCredentialGrant struct {
	Value *ExternalCredentialGrant
}

func (*ExternalCredentialCredentialGrant) isExternalCredentialCredential() {}

// ExternalCredentialCredentialClient is the client variant.
type ExternalCredentialCredentialClient struct {
	Value *ExternalCredentialClientInfo
}

func (*ExternalCredentialCredentialClient) isExternalCredentialCredential() {}

// ExternalCredentialCredentialOpaque is the opaque variant.
type ExternalCredentialCredentialOpaque struct {
	Value *ExternalCredentialOpaque
}

func (*ExternalCredentialCredentialOpaque) isExternalCredentialCredential() {}

// ExternalCredential is the native message type for gestalt.provider.v1.ExternalCredential.
type ExternalCredential struct {
	ID           string
	Subject      string
	Audience     string
	Qualifier    string
	MetadataJSON string
	CreatedAt    *time.Time
	UpdatedAt    *time.Time
	Credential   ExternalCredentialCredential
}

// GetID returns the id field; it is safe to call on a nil receiver.
func (x *ExternalCredential) GetID() string {
	if x == nil {
		return ""
	}
	return x.ID
}

// GetSubject returns the subject field; it is safe to call on a nil receiver.
func (x *ExternalCredential) GetSubject() string {
	if x == nil {
		return ""
	}
	return x.Subject
}

// GetAudience returns the audience field; it is safe to call on a nil receiver.
func (x *ExternalCredential) GetAudience() string {
	if x == nil {
		return ""
	}
	return x.Audience
}

// GetQualifier returns the qualifier field; it is safe to call on a nil receiver.
func (x *ExternalCredential) GetQualifier() string {
	if x == nil {
		return ""
	}
	return x.Qualifier
}

// GetMetadataJSON returns the metadataJson field; it is safe to call on a nil receiver.
func (x *ExternalCredential) GetMetadataJSON() string {
	if x == nil {
		return ""
	}
	return x.MetadataJSON
}

// GetCreatedAt returns the createdAt field; it is safe to call on a nil receiver.
func (x *ExternalCredential) GetCreatedAt() *time.Time {
	if x == nil {
		return nil
	}
	return x.CreatedAt
}

// GetUpdatedAt returns the updatedAt field; it is safe to call on a nil receiver.
func (x *ExternalCredential) GetUpdatedAt() *time.Time {
	if x == nil {
		return nil
	}
	return x.UpdatedAt
}

// GetCredential returns the credential oneof; it is safe to call on a nil receiver.
func (x *ExternalCredential) GetCredential() ExternalCredentialCredential {
	if x == nil {
		return nil
	}
	return x.Credential
}

// ExternalCredentialAuthConfig is the native message type for gestalt.provider.v1.ExternalCredentialAuthConfig.
type ExternalCredentialAuthConfig struct {
	Type                 string
	Token                string
	TokenPrefix          string
	GrantType            string
	TokenURL             string
	ClientID             string
	ClientSecret         string
	ClientAuth           string
	TokenExchange        string
	Scopes               []string
	ScopeParam           string
	ScopeSeparator       string
	TokenParams          map[string]string
	RefreshParams        map[string]string
	AcceptHeader         string
	AccessTokenPath      string
	TokenExchangeDrivers []*ExternalCredentialTokenExchangeDriver
	RefreshToken         string
}

// GetType returns the type field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetType() string {
	if x == nil {
		return ""
	}
	return x.Type
}

// GetToken returns the token field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetToken() string {
	if x == nil {
		return ""
	}
	return x.Token
}

// GetTokenPrefix returns the tokenPrefix field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetTokenPrefix() string {
	if x == nil {
		return ""
	}
	return x.TokenPrefix
}

// GetGrantType returns the grantType field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetGrantType() string {
	if x == nil {
		return ""
	}
	return x.GrantType
}

// GetTokenURL returns the tokenUrl field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetTokenURL() string {
	if x == nil {
		return ""
	}
	return x.TokenURL
}

// GetClientID returns the clientId field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetClientID() string {
	if x == nil {
		return ""
	}
	return x.ClientID
}

// GetClientSecret returns the clientSecret field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetClientSecret() string {
	if x == nil {
		return ""
	}
	return x.ClientSecret
}

// GetClientAuth returns the clientAuth field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetClientAuth() string {
	if x == nil {
		return ""
	}
	return x.ClientAuth
}

// GetTokenExchange returns the tokenExchange field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetTokenExchange() string {
	if x == nil {
		return ""
	}
	return x.TokenExchange
}

// GetScopes returns the scopes field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetScopes() []string {
	if x == nil {
		return nil
	}
	return x.Scopes
}

// GetScopeParam returns the scopeParam field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetScopeParam() string {
	if x == nil {
		return ""
	}
	return x.ScopeParam
}

// GetScopeSeparator returns the scopeSeparator field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetScopeSeparator() string {
	if x == nil {
		return ""
	}
	return x.ScopeSeparator
}

// GetTokenParams returns the tokenParams field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetTokenParams() map[string]string {
	if x == nil {
		return nil
	}
	return x.TokenParams
}

// GetRefreshParams returns the refreshParams field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetRefreshParams() map[string]string {
	if x == nil {
		return nil
	}
	return x.RefreshParams
}

// GetAcceptHeader returns the acceptHeader field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetAcceptHeader() string {
	if x == nil {
		return ""
	}
	return x.AcceptHeader
}

// GetAccessTokenPath returns the accessTokenPath field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetAccessTokenPath() string {
	if x == nil {
		return ""
	}
	return x.AccessTokenPath
}

// GetTokenExchangeDrivers returns the tokenExchangeDrivers field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetTokenExchangeDrivers() []*ExternalCredentialTokenExchangeDriver {
	if x == nil {
		return nil
	}
	return x.TokenExchangeDrivers
}

// GetRefreshToken returns the refreshToken field; it is safe to call on a nil receiver.
func (x *ExternalCredentialAuthConfig) GetRefreshToken() string {
	if x == nil {
		return ""
	}
	return x.RefreshToken
}

// ExternalCredentialClientInfo is the native message type for gestalt.provider.v1.ExternalCredentialClientInfo.
type ExternalCredentialClientInfo struct {
	ClientID              string
	ClientSecret          string
	ClientSecretExpiresAt *time.Time
}

// GetClientID returns the clientId field; it is safe to call on a nil receiver.
func (x *ExternalCredentialClientInfo) GetClientID() string {
	if x == nil {
		return ""
	}
	return x.ClientID
}

// GetClientSecret returns the clientSecret field; it is safe to call on a nil receiver.
func (x *ExternalCredentialClientInfo) GetClientSecret() string {
	if x == nil {
		return ""
	}
	return x.ClientSecret
}

// GetClientSecretExpiresAt returns the clientSecretExpiresAt field; it is safe to call on a nil receiver.
func (x *ExternalCredentialClientInfo) GetClientSecretExpiresAt() *time.Time {
	if x == nil {
		return nil
	}
	return x.ClientSecretExpiresAt
}

// ExternalCredentialGrant is the native message type for gestalt.provider.v1.ExternalCredentialGrant.
type ExternalCredentialGrant struct {
	AccessToken       string
	RefreshToken      string
	Scope             string
	ExpiresAt         *time.Time
	LastRefreshedAt   *time.Time
	RefreshErrorCount int32
}

// GetAccessToken returns the accessToken field; it is safe to call on a nil receiver.
func (x *ExternalCredentialGrant) GetAccessToken() string {
	if x == nil {
		return ""
	}
	return x.AccessToken
}

// GetRefreshToken returns the refreshToken field; it is safe to call on a nil receiver.
func (x *ExternalCredentialGrant) GetRefreshToken() string {
	if x == nil {
		return ""
	}
	return x.RefreshToken
}

// GetScope returns the scope field; it is safe to call on a nil receiver.
func (x *ExternalCredentialGrant) GetScope() string {
	if x == nil {
		return ""
	}
	return x.Scope
}

// GetExpiresAt returns the expiresAt field; it is safe to call on a nil receiver.
func (x *ExternalCredentialGrant) GetExpiresAt() *time.Time {
	if x == nil {
		return nil
	}
	return x.ExpiresAt
}

// GetLastRefreshedAt returns the lastRefreshedAt field; it is safe to call on a nil receiver.
func (x *ExternalCredentialGrant) GetLastRefreshedAt() *time.Time {
	if x == nil {
		return nil
	}
	return x.LastRefreshedAt
}

// GetRefreshErrorCount returns the refreshErrorCount field; it is safe to call on a nil receiver.
func (x *ExternalCredentialGrant) GetRefreshErrorCount() int32 {
	if x == nil {
		return 0
	}
	return x.RefreshErrorCount
}

// ExternalCredentialOpaque is the native message type for gestalt.provider.v1.ExternalCredentialOpaque.
type ExternalCredentialOpaque struct {
	Fields map[string]string
}

// GetFields returns the fields field; it is safe to call on a nil receiver.
func (x *ExternalCredentialOpaque) GetFields() map[string]string {
	if x == nil {
		return nil
	}
	return x.Fields
}

// ExternalCredentialTokenExchangeDriver is the native message type for gestalt.provider.v1.ExternalCredentialTokenExchangeDriver.
type ExternalCredentialTokenExchangeDriver struct {
	Type            string
	TargetPrincipal string
	Scopes          []string
	LifetimeSeconds int32
	Endpoint        string
	Params          map[string]string
}

// GetType returns the type field; it is safe to call on a nil receiver.
func (x *ExternalCredentialTokenExchangeDriver) GetType() string {
	if x == nil {
		return ""
	}
	return x.Type
}

// GetTargetPrincipal returns the targetPrincipal field; it is safe to call on a nil receiver.
func (x *ExternalCredentialTokenExchangeDriver) GetTargetPrincipal() string {
	if x == nil {
		return ""
	}
	return x.TargetPrincipal
}

// GetScopes returns the scopes field; it is safe to call on a nil receiver.
func (x *ExternalCredentialTokenExchangeDriver) GetScopes() []string {
	if x == nil {
		return nil
	}
	return x.Scopes
}

// GetLifetimeSeconds returns the lifetimeSeconds field; it is safe to call on a nil receiver.
func (x *ExternalCredentialTokenExchangeDriver) GetLifetimeSeconds() int32 {
	if x == nil {
		return 0
	}
	return x.LifetimeSeconds
}

// GetEndpoint returns the endpoint field; it is safe to call on a nil receiver.
func (x *ExternalCredentialTokenExchangeDriver) GetEndpoint() string {
	if x == nil {
		return ""
	}
	return x.Endpoint
}

// GetParams returns the params field; it is safe to call on a nil receiver.
func (x *ExternalCredentialTokenExchangeDriver) GetParams() map[string]string {
	if x == nil {
		return nil
	}
	return x.Params
}

// ExternalCredentialTokenResponse is the native message type for gestalt.provider.v1.ExternalCredentialTokenResponse.
type ExternalCredentialTokenResponse struct {
	AccessToken   string
	RefreshToken  string
	ExpiresIn     int32
	TokenType     string
	ExtraJSON     string
	RefreshSource string
}

// GetAccessToken returns the accessToken field; it is safe to call on a nil receiver.
func (x *ExternalCredentialTokenResponse) GetAccessToken() string {
	if x == nil {
		return ""
	}
	return x.AccessToken
}

// GetRefreshToken returns the refreshToken field; it is safe to call on a nil receiver.
func (x *ExternalCredentialTokenResponse) GetRefreshToken() string {
	if x == nil {
		return ""
	}
	return x.RefreshToken
}

// GetExpiresIn returns the expiresIn field; it is safe to call on a nil receiver.
func (x *ExternalCredentialTokenResponse) GetExpiresIn() int32 {
	if x == nil {
		return 0
	}
	return x.ExpiresIn
}

// GetTokenType returns the tokenType field; it is safe to call on a nil receiver.
func (x *ExternalCredentialTokenResponse) GetTokenType() string {
	if x == nil {
		return ""
	}
	return x.TokenType
}

// GetExtraJSON returns the extraJson field; it is safe to call on a nil receiver.
func (x *ExternalCredentialTokenResponse) GetExtraJSON() string {
	if x == nil {
		return ""
	}
	return x.ExtraJSON
}

// GetRefreshSource returns the refreshSource field; it is safe to call on a nil receiver.
func (x *ExternalCredentialTokenResponse) GetRefreshSource() string {
	if x == nil {
		return ""
	}
	return x.RefreshSource
}

// GetExternalCredentialRequest is the native message type for gestalt.provider.v1.GetExternalCredentialRequest.
type GetExternalCredentialRequest struct {
	Subject   string
	Audience  string
	Qualifier string
}

// GetSubject returns the subject field; it is safe to call on a nil receiver.
func (x *GetExternalCredentialRequest) GetSubject() string {
	if x == nil {
		return ""
	}
	return x.Subject
}

// GetAudience returns the audience field; it is safe to call on a nil receiver.
func (x *GetExternalCredentialRequest) GetAudience() string {
	if x == nil {
		return ""
	}
	return x.Audience
}

// GetQualifier returns the qualifier field; it is safe to call on a nil receiver.
func (x *GetExternalCredentialRequest) GetQualifier() string {
	if x == nil {
		return ""
	}
	return x.Qualifier
}

// ListExternalCredentialsRequest is the native message type for gestalt.provider.v1.ListExternalCredentialsRequest.
type ListExternalCredentialsRequest struct {
	Subject  string
	Audience string
}

// GetSubject returns the subject field; it is safe to call on a nil receiver.
func (x *ListExternalCredentialsRequest) GetSubject() string {
	if x == nil {
		return ""
	}
	return x.Subject
}

// GetAudience returns the audience field; it is safe to call on a nil receiver.
func (x *ListExternalCredentialsRequest) GetAudience() string {
	if x == nil {
		return ""
	}
	return x.Audience
}

// ListExternalCredentialsResponse is the native message type for gestalt.provider.v1.ListExternalCredentialsResponse.
type ListExternalCredentialsResponse struct {
	Credentials []*ExternalCredential
}

// GetCredentials returns the credentials field; it is safe to call on a nil receiver.
func (x *ListExternalCredentialsResponse) GetCredentials() []*ExternalCredential {
	if x == nil {
		return nil
	}
	return x.Credentials
}

// ResolveExternalCredentialRequest is the native message type for gestalt.provider.v1.ResolveExternalCredentialRequest.
type ResolveExternalCredentialRequest struct {
	Provider            string
	Connection          string
	ConnectionID        string
	Mode                string
	CredentialSubjectID string
	ActorSubjectID      string
	Instance            string
	Auth                *ExternalCredentialAuthConfig
	ConnectionParams    map[string]string
}

// GetProvider returns the provider field; it is safe to call on a nil receiver.
func (x *ResolveExternalCredentialRequest) GetProvider() string {
	if x == nil {
		return ""
	}
	return x.Provider
}

// GetConnection returns the connection field; it is safe to call on a nil receiver.
func (x *ResolveExternalCredentialRequest) GetConnection() string {
	if x == nil {
		return ""
	}
	return x.Connection
}

// GetConnectionID returns the connectionId field; it is safe to call on a nil receiver.
func (x *ResolveExternalCredentialRequest) GetConnectionID() string {
	if x == nil {
		return ""
	}
	return x.ConnectionID
}

// GetMode returns the mode field; it is safe to call on a nil receiver.
func (x *ResolveExternalCredentialRequest) GetMode() string {
	if x == nil {
		return ""
	}
	return x.Mode
}

// GetCredentialSubjectID returns the credentialSubjectId field; it is safe to call on a nil receiver.
func (x *ResolveExternalCredentialRequest) GetCredentialSubjectID() string {
	if x == nil {
		return ""
	}
	return x.CredentialSubjectID
}

// GetActorSubjectID returns the actorSubjectId field; it is safe to call on a nil receiver.
func (x *ResolveExternalCredentialRequest) GetActorSubjectID() string {
	if x == nil {
		return ""
	}
	return x.ActorSubjectID
}

// GetInstance returns the instance field; it is safe to call on a nil receiver.
func (x *ResolveExternalCredentialRequest) GetInstance() string {
	if x == nil {
		return ""
	}
	return x.Instance
}

// GetAuth returns the auth field; it is safe to call on a nil receiver.
func (x *ResolveExternalCredentialRequest) GetAuth() *ExternalCredentialAuthConfig {
	if x == nil {
		return nil
	}
	return x.Auth
}

// GetConnectionParams returns the connectionParams field; it is safe to call on a nil receiver.
func (x *ResolveExternalCredentialRequest) GetConnectionParams() map[string]string {
	if x == nil {
		return nil
	}
	return x.ConnectionParams
}

// ResolveExternalCredentialResponse is the native message type for gestalt.provider.v1.ResolveExternalCredentialResponse.
type ResolveExternalCredentialResponse struct {
	Token        string
	ExpiresAt    *time.Time
	MetadataJSON string
	Params       map[string]string
	Credential   *ExternalCredential
}

// GetToken returns the token field; it is safe to call on a nil receiver.
func (x *ResolveExternalCredentialResponse) GetToken() string {
	if x == nil {
		return ""
	}
	return x.Token
}

// GetExpiresAt returns the expiresAt field; it is safe to call on a nil receiver.
func (x *ResolveExternalCredentialResponse) GetExpiresAt() *time.Time {
	if x == nil {
		return nil
	}
	return x.ExpiresAt
}

// GetMetadataJSON returns the metadataJson field; it is safe to call on a nil receiver.
func (x *ResolveExternalCredentialResponse) GetMetadataJSON() string {
	if x == nil {
		return ""
	}
	return x.MetadataJSON
}

// GetParams returns the params field; it is safe to call on a nil receiver.
func (x *ResolveExternalCredentialResponse) GetParams() map[string]string {
	if x == nil {
		return nil
	}
	return x.Params
}

// GetCredential returns the credential field; it is safe to call on a nil receiver.
func (x *ResolveExternalCredentialResponse) GetCredential() *ExternalCredential {
	if x == nil {
		return nil
	}
	return x.Credential
}

// UpsertExternalCredentialRequest is the native message type for gestalt.provider.v1.UpsertExternalCredentialRequest.
type UpsertExternalCredentialRequest struct {
	Credential *ExternalCredential
}

// GetCredential returns the credential field; it is safe to call on a nil receiver.
func (x *UpsertExternalCredentialRequest) GetCredential() *ExternalCredential {
	if x == nil {
		return nil
	}
	return x.Credential
}

// ValidateExternalCredentialConfigRequest is the native message type for gestalt.provider.v1.ValidateExternalCredentialConfigRequest.
type ValidateExternalCredentialConfigRequest struct {
	Provider         string
	Connection       string
	ConnectionID     string
	Mode             string
	Auth             *ExternalCredentialAuthConfig
	ConnectionParams map[string]string
}

// GetProvider returns the provider field; it is safe to call on a nil receiver.
func (x *ValidateExternalCredentialConfigRequest) GetProvider() string {
	if x == nil {
		return ""
	}
	return x.Provider
}

// GetConnection returns the connection field; it is safe to call on a nil receiver.
func (x *ValidateExternalCredentialConfigRequest) GetConnection() string {
	if x == nil {
		return ""
	}
	return x.Connection
}

// GetConnectionID returns the connectionId field; it is safe to call on a nil receiver.
func (x *ValidateExternalCredentialConfigRequest) GetConnectionID() string {
	if x == nil {
		return ""
	}
	return x.ConnectionID
}

// GetMode returns the mode field; it is safe to call on a nil receiver.
func (x *ValidateExternalCredentialConfigRequest) GetMode() string {
	if x == nil {
		return ""
	}
	return x.Mode
}

// GetAuth returns the auth field; it is safe to call on a nil receiver.
func (x *ValidateExternalCredentialConfigRequest) GetAuth() *ExternalCredentialAuthConfig {
	if x == nil {
		return nil
	}
	return x.Auth
}

// GetConnectionParams returns the connectionParams field; it is safe to call on a nil receiver.
func (x *ValidateExternalCredentialConfigRequest) GetConnectionParams() map[string]string {
	if x == nil {
		return nil
	}
	return x.ConnectionParams
}

// ExternalCredentials is the generated client for gestalt.provider.v1.ExternalCredentials.
// Every transport error is converted to *GestaltError.
type ExternalCredentials struct {
	client proto.ExternalCredentialsClient
}

// NewExternalCredentials creates a ExternalCredentials client over an injected gRPC connection.
func NewExternalCredentials(conn grpc.ClientConnInterface) *ExternalCredentials {
	return &ExternalCredentials{client: proto.NewExternalCredentialsClient(conn)}
}

var connectExternalCredentialsConns host.ConnPool

// ConnectExternalCredentials dials the "external_credentials" host service advertised through the
// GESTALT_HOST_SERVICE_SOCKET environment and returns a connected client.
// name selects a named binding; the empty string selects the default
// binding. Connections are pooled per binding and shared across clients for
// the life of the process. The first dial blocks until the connection is
// ready or ctx is done.
func ConnectExternalCredentials(ctx context.Context, name string) (*ExternalCredentials, error) {
	target, token, err := host.Target("external_credentials")
	if err != nil {
		return nil, toGestaltError(err)
	}
	conn, err := connectExternalCredentialsConns.Conn(ctx, "external_credentials", target, token, name)
	if err != nil {
		return nil, toGestaltError(err)
	}
	return NewExternalCredentials(conn), nil
}

// CreateCredential is the ergonomic form of [ExternalCredentials.CreateCredentialRaw].
func (c *ExternalCredentials) CreateCredential(ctx context.Context, credential *ExternalCredential) (*ExternalCredential, error) {
	request := &CreateExternalCredentialRequest{Credential: credential}
	response, err := c.client.CreateCredential(ctx, toWireCreateExternalCredentialRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireExternalCredential(response), nil
}

// CreateCredentialRaw is the faithful form of [ExternalCredentials.CreateCredential].
func (c *ExternalCredentials) CreateCredentialRaw(ctx context.Context, request *CreateExternalCredentialRequest) (*ExternalCredential, error) {
	response, err := c.client.CreateCredential(ctx, toWireCreateExternalCredentialRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireExternalCredential(response), nil
}

// UpsertCredential is the ergonomic form of [ExternalCredentials.UpsertCredentialRaw].
func (c *ExternalCredentials) UpsertCredential(ctx context.Context, credential *ExternalCredential) (*ExternalCredential, error) {
	request := &UpsertExternalCredentialRequest{Credential: credential}
	response, err := c.client.UpsertCredential(ctx, toWireUpsertExternalCredentialRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireExternalCredential(response), nil
}

// UpsertCredentialRaw is the faithful form of [ExternalCredentials.UpsertCredential].
func (c *ExternalCredentials) UpsertCredentialRaw(ctx context.Context, request *UpsertExternalCredentialRequest) (*ExternalCredential, error) {
	response, err := c.client.UpsertCredential(ctx, toWireUpsertExternalCredentialRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireExternalCredential(response), nil
}

// GetCredential is the ergonomic form of [ExternalCredentials.GetCredentialRaw].
func (c *ExternalCredentials) GetCredential(ctx context.Context, subject string, audience string, qualifier string) (*ExternalCredential, error) {
	request := &GetExternalCredentialRequest{Subject: subject, Audience: audience, Qualifier: qualifier}
	response, err := c.client.GetCredential(ctx, toWireGetExternalCredentialRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireExternalCredential(response), nil
}

// GetCredentialRaw is the faithful form of [ExternalCredentials.GetCredential].
func (c *ExternalCredentials) GetCredentialRaw(ctx context.Context, request *GetExternalCredentialRequest) (*ExternalCredential, error) {
	response, err := c.client.GetCredential(ctx, toWireGetExternalCredentialRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireExternalCredential(response), nil
}

// ExternalCredentialsListCredentialsOptions carries the optional parameters of [ExternalCredentials.ListCredentials].
// A nil options value is equivalent to the zero value.
type ExternalCredentialsListCredentialsOptions struct {
	Audience string
}

// ListCredentials is the ergonomic form of [ExternalCredentials.ListCredentialsRaw].
// The response collapses to its credentials field.
func (c *ExternalCredentials) ListCredentials(ctx context.Context, subject string, opts *ExternalCredentialsListCredentialsOptions) ([]*ExternalCredential, error) {
	if opts == nil {
		opts = &ExternalCredentialsListCredentialsOptions{}
	}
	request := &ListExternalCredentialsRequest{Subject: subject, Audience: opts.Audience}
	response, err := c.client.ListCredentials(ctx, toWireListExternalCredentialsRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireListExternalCredentialsResponse(response).Credentials, nil
}

// ListCredentialsRaw is the faithful form of [ExternalCredentials.ListCredentials].
func (c *ExternalCredentials) ListCredentialsRaw(ctx context.Context, request *ListExternalCredentialsRequest) (*ListExternalCredentialsResponse, error) {
	response, err := c.client.ListCredentials(ctx, toWireListExternalCredentialsRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireListExternalCredentialsResponse(response), nil
}

// DeleteCredential is the ergonomic form of [ExternalCredentials.DeleteCredentialRaw].
func (c *ExternalCredentials) DeleteCredential(ctx context.Context, id string) error {
	request := &DeleteExternalCredentialRequest{ID: id}
	if _, err := c.client.DeleteCredential(ctx, toWireDeleteExternalCredentialRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// DeleteCredentialRaw is the faithful form of [ExternalCredentials.DeleteCredential].
func (c *ExternalCredentials) DeleteCredentialRaw(ctx context.Context, request *DeleteExternalCredentialRequest) error {
	if _, err := c.client.DeleteCredential(ctx, toWireDeleteExternalCredentialRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// ValidateCredentialConfig is the ergonomic form of [ExternalCredentials.ValidateCredentialConfigRaw].
func (c *ExternalCredentials) ValidateCredentialConfig(ctx context.Context, provider string, connection string, connectionId string, mode string, auth *ExternalCredentialAuthConfig) error {
	request := &ValidateExternalCredentialConfigRequest{Provider: provider, Connection: connection, ConnectionID: connectionId, Mode: mode, Auth: auth}
	if _, err := c.client.ValidateCredentialConfig(ctx, toWireValidateExternalCredentialConfigRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// ValidateCredentialConfigRaw is the faithful form of [ExternalCredentials.ValidateCredentialConfig].
func (c *ExternalCredentials) ValidateCredentialConfigRaw(ctx context.Context, request *ValidateExternalCredentialConfigRequest) error {
	if _, err := c.client.ValidateCredentialConfig(ctx, toWireValidateExternalCredentialConfigRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// ResolveCredential is the ergonomic form of [ExternalCredentials.ResolveCredentialRaw].
func (c *ExternalCredentials) ResolveCredential(ctx context.Context, provider string, connection string, connectionId string, mode string, credentialSubjectId string, actorSubjectId string, instance string, auth *ExternalCredentialAuthConfig) (*ResolveExternalCredentialResponse, error) {
	request := &ResolveExternalCredentialRequest{Provider: provider, Connection: connection, ConnectionID: connectionId, Mode: mode, CredentialSubjectID: credentialSubjectId, ActorSubjectID: actorSubjectId, Instance: instance, Auth: auth}
	response, err := c.client.ResolveCredential(ctx, toWireResolveExternalCredentialRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireResolveExternalCredentialResponse(response), nil
}

// ResolveCredentialRaw is the faithful form of [ExternalCredentials.ResolveCredential].
func (c *ExternalCredentials) ResolveCredentialRaw(ctx context.Context, request *ResolveExternalCredentialRequest) (*ResolveExternalCredentialResponse, error) {
	response, err := c.client.ResolveCredential(ctx, toWireResolveExternalCredentialRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireResolveExternalCredentialResponse(response), nil
}

// ExchangeCredential is the ergonomic form of [ExternalCredentials.ExchangeCredentialRaw].
// The response collapses to its tokenResponse field.
func (c *ExternalCredentials) ExchangeCredential(ctx context.Context, provider string, connection string, connectionId string, credentialSubjectId string, actorSubjectId string, instance string, credentialJson string, auth *ExternalCredentialAuthConfig) (*ExternalCredentialTokenResponse, error) {
	request := &ExchangeExternalCredentialRequest{Provider: provider, Connection: connection, ConnectionID: connectionId, CredentialSubjectID: credentialSubjectId, ActorSubjectID: actorSubjectId, Instance: instance, CredentialJSON: credentialJson, Auth: auth}
	response, err := c.client.ExchangeCredential(ctx, toWireExchangeExternalCredentialRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireExchangeExternalCredentialResponse(response).TokenResponse, nil
}

// ExchangeCredentialRaw is the faithful form of [ExternalCredentials.ExchangeCredential].
func (c *ExternalCredentials) ExchangeCredentialRaw(ctx context.Context, request *ExchangeExternalCredentialRequest) (*ExchangeExternalCredentialResponse, error) {
	response, err := c.client.ExchangeCredential(ctx, toWireExchangeExternalCredentialRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireExchangeExternalCredentialResponse(response), nil
}
