// Code generated by sdkgen. DO NOT EDIT.

package client

import (
	"context"
	"time"

	"github.com/valon-technologies/gestalt/sdk/go/internal/host"
	proto "github.com/valon-technologies/gestalt/server/rpc/protov1/v1"
	"google.golang.org/grpc"
)

// CursorDirection is the gestalt.provider.v1.CursorDirection enum. It is open:
// numeric values outside the named constants are preserved.
//
// CursorDirection controls IndexedDB cursor traversal order.
type CursorDirection int32

const (
	// CursorDirectionCursorNext is the CURSOR_NEXT value of CursorDirection.
	CursorDirectionCursorNext CursorDirection = 0
	// CursorDirectionCursorNextUnique is the CURSOR_NEXT_UNIQUE value of CursorDirection.
	CursorDirectionCursorNextUnique CursorDirection = 1
	// CursorDirectionCursorPrev is the CURSOR_PREV value of CursorDirection.
	CursorDirectionCursorPrev CursorDirection = 2
	// CursorDirectionCursorPrevUnique is the CURSOR_PREV_UNIQUE value of CursorDirection.
	CursorDirectionCursorPrevUnique CursorDirection = 3
)

// TransactionDurabilityHint is the gestalt.provider.v1.TransactionDurabilityHint enum. It is open:
// numeric values outside the named constants are preserved.
//
// TransactionDurabilityHint mirrors the W3C IndexedDB durability option as a
// provider hint. It is not a portable durability guarantee.
type TransactionDurabilityHint int32

const (
	// TransactionDurabilityHintTransactionDurabilityDefault is the TRANSACTION_DURABILITY_DEFAULT value of TransactionDurabilityHint.
	TransactionDurabilityHintTransactionDurabilityDefault TransactionDurabilityHint = 0
	// TransactionDurabilityHintTransactionDurabilityStrict is the TRANSACTION_DURABILITY_STRICT value of TransactionDurabilityHint.
	TransactionDurabilityHintTransactionDurabilityStrict TransactionDurabilityHint = 1
	// TransactionDurabilityHintTransactionDurabilityRelaxed is the TRANSACTION_DURABILITY_RELAXED value of TransactionDurabilityHint.
	TransactionDurabilityHintTransactionDurabilityRelaxed TransactionDurabilityHint = 2
)

// TransactionMode is the gestalt.provider.v1.TransactionMode enum. It is open:
// numeric values outside the named constants are preserved.
//
// TransactionMode controls whether a transaction may mutate scoped stores.
type TransactionMode int32

const (
	// TransactionModeTransactionReadonly is the TRANSACTION_READONLY value of TransactionMode.
	TransactionModeTransactionReadonly TransactionMode = 0
	// TransactionModeTransactionReadwrite is the TRANSACTION_READWRITE value of TransactionMode.
	TransactionModeTransactionReadwrite TransactionMode = 1
)

// BeginTransactionRequest is the native message type for gestalt.provider.v1.BeginTransactionRequest.
//
// BeginTransactionRequest starts an IndexedDB transaction stream.
type BeginTransactionRequest struct {
	Stores         []string
	Mode           TransactionMode
	DurabilityHint TransactionDurabilityHint
}

// ColumnDef is the native message type for gestalt.provider.v1.ColumnDef.
//
// ColumnDef is reserved for providers that preserve SQL-style column metadata.
type ColumnDef struct {
	Name       string
	Type       int32
	PrimaryKey bool
	NotNull    bool
	Unique     bool
}

// CountResponse is the native message type for gestalt.provider.v1.CountResponse.
//
// CountResponse reports how many rows matched a query.
type CountResponse struct {
	Count int64
}

// CreateObjectStoreRequest is the native message type for gestalt.provider.v1.CreateObjectStoreRequest.
//
// CreateObjectStoreRequest creates a new object store.
type CreateObjectStoreRequest struct {
	Name   string
	Schema *ObjectStoreSchema
}

// CursorClientMessageMsg selects one variant of the msg oneof of CursorClientMessage.
// A nil value means unset.
type CursorClientMessageMsg interface {
	isCursorClientMessageMsg()
}

// CursorClientMessageMsgOpen is the open variant.
type CursorClientMessageMsgOpen struct {
	Value *OpenCursorRequest
}

func (*CursorClientMessageMsgOpen) isCursorClientMessageMsg() {}

// CursorClientMessageMsgCommand is the command variant.
type CursorClientMessageMsgCommand struct {
	Value *CursorCommand
}

func (*CursorClientMessageMsgCommand) isCursorClientMessageMsg() {}

// CursorClientMessage is the native message type for gestalt.provider.v1.CursorClientMessage.
//
// CursorClientMessage is one frame in the bidirectional cursor stream.
type CursorClientMessage struct {
	Msg CursorClientMessageMsg
}

// CursorCommandCommand selects one variant of the command oneof of CursorCommand.
// A nil value means unset.
type CursorCommandCommand interface {
	isCursorCommandCommand()
}

// CursorCommandCommandNext is the next variant.
type CursorCommandCommandNext struct {
	Value bool
}

func (*CursorCommandCommandNext) isCursorCommandCommand() {}

// CursorCommandCommandContinueToKey is the continueToKey variant.
type CursorCommandCommandContinueToKey struct {
	Value *CursorKeyTarget
}

func (*CursorCommandCommandContinueToKey) isCursorCommandCommand() {}

// CursorCommandCommandAdvance is the advance variant.
type CursorCommandCommandAdvance struct {
	Value int32
}

func (*CursorCommandCommandAdvance) isCursorCommandCommand() {}

// CursorCommandCommandUpdate is the update variant.
type CursorCommandCommandUpdate struct {
	Value *Record
}

func (*CursorCommandCommandUpdate) isCursorCommandCommand() {}

// CursorCommandCommandDelete is the delete variant.
type CursorCommandCommandDelete struct {
	Value bool
}

func (*CursorCommandCommandDelete) isCursorCommandCommand() {}

// CursorCommandCommandClose is the close variant.
type CursorCommandCommandClose struct {
	Value bool
}

func (*CursorCommandCommandClose) isCursorCommandCommand() {}

// CursorCommand is the native message type for gestalt.provider.v1.CursorCommand.
//
// CursorCommand advances, mutates, or closes an open cursor.
type CursorCommand struct {
	Command CursorCommandCommand
}

// CursorEntry is the native message type for gestalt.provider.v1.CursorEntry.
//
// CursorEntry is one streamed cursor row.
type CursorEntry struct {
	// Key components per index KeyPath field. Each component is a KeyValue
	// that can be a scalar or a nested array, preserving the full W3C IndexedDB
	// key structure including array-valued keys.
	Key        []*KeyValue
	PrimaryKey string
	Record     *Record
}

// CursorKeyTarget is the native message type for gestalt.provider.v1.CursorKeyTarget.
//
// CursorKeyTarget addresses a specific cursor position.
type CursorKeyTarget struct {
	Key []*KeyValue
}

// CursorResponseResult selects one variant of the result oneof of CursorResponse.
// A nil value means unset.
type CursorResponseResult interface {
	isCursorResponseResult()
}

// CursorResponseResultEntry is the entry variant.
type CursorResponseResultEntry struct {
	Value *CursorEntry
}

func (*CursorResponseResultEntry) isCursorResponseResult() {}

// CursorResponseResultDone is the done variant.
type CursorResponseResultDone struct {
	Value bool
}

func (*CursorResponseResultDone) isCursorResponseResult() {}

// CursorResponse is the native message type for gestalt.provider.v1.CursorResponse.
//
// CursorResponse is one streamed cursor frame.
type CursorResponse struct {
	Result CursorResponseResult
}

// DeleteObjectStoreRequest is the native message type for gestalt.provider.v1.DeleteObjectStoreRequest.
//
// DeleteObjectStoreRequest removes an object store.
type DeleteObjectStoreRequest struct {
	Name string
}

// DeleteResponse is the native message type for gestalt.provider.v1.DeleteResponse.
//
// DeleteResponse reports how many rows were deleted.
type DeleteResponse struct {
	Deleted int64
}

// IndexQueryRequest is the native message type for gestalt.provider.v1.IndexQueryRequest.
//
// IndexQueryRequest addresses a secondary index plus optional key values and
// range constraints.
type IndexQueryRequest struct {
	Store  string
	Index  string
	Values []*TypedValue
	Range  *KeyRange
}

// IndexSchema is the native message type for gestalt.provider.v1.IndexSchema.
//
// IndexSchema describes one secondary index on an object store.
type IndexSchema struct {
	Name    string
	KeyPath []string
	Unique  bool
}

// KeyRange is the native message type for gestalt.provider.v1.KeyRange.
//
// KeyRange constrains a query or cursor by lower and upper bounds.
type KeyRange struct {
	Lower     *TypedValue
	Upper     *TypedValue
	LowerOpen bool
	UpperOpen bool
}

// KeyResponse is the native message type for gestalt.provider.v1.KeyResponse.
//
// KeyResponse wraps one primary key.
type KeyResponse struct {
	Key string
}

// KeyValueKind selects one variant of the kind oneof of KeyValue.
// A nil value means unset.
type KeyValueKind interface {
	isKeyValueKind()
}

// KeyValueKindScalar is the scalar variant.
type KeyValueKindScalar struct {
	Value *TypedValue
}

func (*KeyValueKindScalar) isKeyValueKind() {}

// KeyValueKindArray is the array variant.
type KeyValueKindArray struct {
	Value *KeyValueArray
}

func (*KeyValueKindArray) isKeyValueKind() {}

// KeyValue is the native message type for gestalt.provider.v1.KeyValue.
//
// KeyValue represents a single IndexedDB key, which can be a scalar
// (string, number, date, binary) or a nested array of keys per the W3C spec.
type KeyValue struct {
	Kind KeyValueKind
}

// KeyValueArray is the native message type for gestalt.provider.v1.KeyValueArray.
type KeyValueArray struct {
	Elements []*KeyValue
}

// KeysResponse is the native message type for gestalt.provider.v1.KeysResponse.
//
// KeysResponse wraps repeated primary keys.
type KeysResponse struct {
	Keys []string
}

// ObjectStoreNameRequest is the native message type for gestalt.provider.v1.ObjectStoreNameRequest.
//
// ObjectStoreNameRequest addresses an object store without a specific row key.
type ObjectStoreNameRequest struct {
	Store string
}

// ObjectStoreRangeRequest is the native message type for gestalt.provider.v1.ObjectStoreRangeRequest.
//
// ObjectStoreRangeRequest addresses an object store plus an optional key range.
type ObjectStoreRangeRequest struct {
	Store string
	Range *KeyRange
}

// ObjectStoreRequest is the native message type for gestalt.provider.v1.ObjectStoreRequest.
//
// ObjectStoreRequest addresses one object store row by primary key.
type ObjectStoreRequest struct {
	Store string
	Id    string
}

// ObjectStoreSchema is the native message type for gestalt.provider.v1.ObjectStoreSchema.
//
// ObjectStoreSchema describes the indexes and columns attached to an object
// store.
type ObjectStoreSchema struct {
	Indexes []*IndexSchema
	Columns []*ColumnDef
}

// OpenCursorRequest is the native message type for gestalt.provider.v1.OpenCursorRequest.
//
// OpenCursorRequest starts a streaming cursor over an object store or index.
type OpenCursorRequest struct {
	Store     string
	Range     *KeyRange
	Direction CursorDirection
	// keys_only suppresses row payloads and returns only keys.
	KeysOnly bool
	// index selects a secondary index when non-empty.
	Index string
	// values selects a compound index key prefix when index is set.
	Values []*TypedValue
}

// Record is the native message type for gestalt.provider.v1.Record.
//
// Record is one JSON-like row in an object store.
type Record struct {
	Fields map[string]*TypedValue
}

// RecordRequest is the native message type for gestalt.provider.v1.RecordRequest.
//
// RecordRequest addresses one object store and carries one row payload.
type RecordRequest struct {
	Store  string
	Record *Record
}

// RecordResponse is the native message type for gestalt.provider.v1.RecordResponse.
//
// RecordResponse wraps one row payload.
type RecordResponse struct {
	Record *Record
}

// RecordsResponse is the native message type for gestalt.provider.v1.RecordsResponse.
//
// RecordsResponse wraps repeated row payloads.
type RecordsResponse struct {
	Records []*Record
}

// TransactionAbortRequest is the native message type for gestalt.provider.v1.TransactionAbortRequest.
type TransactionAbortRequest struct {
	Reason string
}

// TransactionAbortResponse is the native message type for gestalt.provider.v1.TransactionAbortResponse.
//
// TransactionAbortResponse acknowledges abort or reports an abort failure.
type TransactionAbortResponse struct {
	Error *RpcStatus
}

// TransactionBeginResponse is the native message type for gestalt.provider.v1.TransactionBeginResponse.
type TransactionBeginResponse struct{}

// TransactionClientMessageMsg selects one variant of the msg oneof of TransactionClientMessage.
// A nil value means unset.
type TransactionClientMessageMsg interface {
	isTransactionClientMessageMsg()
}

// TransactionClientMessageMsgBegin is the begin variant.
type TransactionClientMessageMsgBegin struct {
	Value *BeginTransactionRequest
}

func (*TransactionClientMessageMsgBegin) isTransactionClientMessageMsg() {}

// TransactionClientMessageMsgOperation is the operation variant.
type TransactionClientMessageMsgOperation struct {
	Value *TransactionOperation
}

func (*TransactionClientMessageMsgOperation) isTransactionClientMessageMsg() {}

// TransactionClientMessageMsgCommit is the commit variant.
type TransactionClientMessageMsgCommit struct {
	Value *TransactionCommitRequest
}

func (*TransactionClientMessageMsgCommit) isTransactionClientMessageMsg() {}

// TransactionClientMessageMsgAbort is the abort variant.
type TransactionClientMessageMsgAbort struct {
	Value *TransactionAbortRequest
}

func (*TransactionClientMessageMsgAbort) isTransactionClientMessageMsg() {}

// TransactionClientMessage is the native message type for gestalt.provider.v1.TransactionClientMessage.
//
// TransactionClientMessage is one client frame in the transaction stream. The
// first frame must be BeginTransactionRequest.
type TransactionClientMessage struct {
	Msg TransactionClientMessageMsg
}

// TransactionCommitRequest is the native message type for gestalt.provider.v1.TransactionCommitRequest.
type TransactionCommitRequest struct{}

// TransactionCommitResponse is the native message type for gestalt.provider.v1.TransactionCommitResponse.
//
// TransactionCommitResponse carries a non-OK status when commit failed after
// the provider accepted the commit frame and rolled the transaction back.
type TransactionCommitResponse struct {
	Error *RpcStatus
}

// TransactionOperationOperation selects one variant of the operation oneof of TransactionOperation.
// A nil value means unset.
type TransactionOperationOperation interface {
	isTransactionOperationOperation()
}

// TransactionOperationOperationGet is the get variant.
type TransactionOperationOperationGet struct {
	Value *ObjectStoreRequest
}

func (*TransactionOperationOperationGet) isTransactionOperationOperation() {}

// TransactionOperationOperationGetKey is the getKey variant.
type TransactionOperationOperationGetKey struct {
	Value *ObjectStoreRequest
}

func (*TransactionOperationOperationGetKey) isTransactionOperationOperation() {}

// TransactionOperationOperationAdd is the add variant.
type TransactionOperationOperationAdd struct {
	Value *RecordRequest
}

func (*TransactionOperationOperationAdd) isTransactionOperationOperation() {}

// TransactionOperationOperationPut is the put variant.
type TransactionOperationOperationPut struct {
	Value *RecordRequest
}

func (*TransactionOperationOperationPut) isTransactionOperationOperation() {}

// TransactionOperationOperationDelete is the delete variant.
type TransactionOperationOperationDelete struct {
	Value *ObjectStoreRequest
}

func (*TransactionOperationOperationDelete) isTransactionOperationOperation() {}

// TransactionOperationOperationClear is the clear variant.
type TransactionOperationOperationClear struct {
	Value *ObjectStoreNameRequest
}

func (*TransactionOperationOperationClear) isTransactionOperationOperation() {}

// TransactionOperationOperationGetAll is the getAll variant.
type TransactionOperationOperationGetAll struct {
	Value *ObjectStoreRangeRequest
}

func (*TransactionOperationOperationGetAll) isTransactionOperationOperation() {}

// TransactionOperationOperationGetAllKeys is the getAllKeys variant.
type TransactionOperationOperationGetAllKeys struct {
	Value *ObjectStoreRangeRequest
}

func (*TransactionOperationOperationGetAllKeys) isTransactionOperationOperation() {}

// TransactionOperationOperationCount is the count variant.
type TransactionOperationOperationCount struct {
	Value *ObjectStoreRangeRequest
}

func (*TransactionOperationOperationCount) isTransactionOperationOperation() {}

// TransactionOperationOperationDeleteRange is the deleteRange variant.
type TransactionOperationOperationDeleteRange struct {
	Value *ObjectStoreRangeRequest
}

func (*TransactionOperationOperationDeleteRange) isTransactionOperationOperation() {}

// TransactionOperationOperationIndexGet is the indexGet variant.
type TransactionOperationOperationIndexGet struct {
	Value *IndexQueryRequest
}

func (*TransactionOperationOperationIndexGet) isTransactionOperationOperation() {}

// TransactionOperationOperationIndexGetKey is the indexGetKey variant.
type TransactionOperationOperationIndexGetKey struct {
	Value *IndexQueryRequest
}

func (*TransactionOperationOperationIndexGetKey) isTransactionOperationOperation() {}

// TransactionOperationOperationIndexGetAll is the indexGetAll variant.
type TransactionOperationOperationIndexGetAll struct {
	Value *IndexQueryRequest
}

func (*TransactionOperationOperationIndexGetAll) isTransactionOperationOperation() {}

// TransactionOperationOperationIndexGetAllKeys is the indexGetAllKeys variant.
type TransactionOperationOperationIndexGetAllKeys struct {
	Value *IndexQueryRequest
}

func (*TransactionOperationOperationIndexGetAllKeys) isTransactionOperationOperation() {}

// TransactionOperationOperationIndexCount is the indexCount variant.
type TransactionOperationOperationIndexCount struct {
	Value *IndexQueryRequest
}

func (*TransactionOperationOperationIndexCount) isTransactionOperationOperation() {}

// TransactionOperationOperationIndexDelete is the indexDelete variant.
type TransactionOperationOperationIndexDelete struct {
	Value *IndexQueryRequest
}

func (*TransactionOperationOperationIndexDelete) isTransactionOperationOperation() {}

// TransactionOperation is the native message type for gestalt.provider.v1.TransactionOperation.
//
// TransactionOperation is one ordered transaction-scoped object store or index
// operation. Cursor operations are intentionally excluded from the initial
// transaction contract.
type TransactionOperation struct {
	RequestId uint64
	Operation TransactionOperationOperation
}

// TransactionOperationResponseResult selects one variant of the result oneof of TransactionOperationResponse.
// A nil value means unset.
type TransactionOperationResponseResult interface {
	isTransactionOperationResponseResult()
}

// TransactionOperationResponseResultEmpty is the empty variant. It carries no payload.
type TransactionOperationResponseResultEmpty struct{}

func (*TransactionOperationResponseResultEmpty) isTransactionOperationResponseResult() {}

// TransactionOperationResponseResultRecord is the record variant.
type TransactionOperationResponseResultRecord struct {
	Value *RecordResponse
}

func (*TransactionOperationResponseResultRecord) isTransactionOperationResponseResult() {}

// TransactionOperationResponseResultRecords is the records variant.
type TransactionOperationResponseResultRecords struct {
	Value *RecordsResponse
}

func (*TransactionOperationResponseResultRecords) isTransactionOperationResponseResult() {}

// TransactionOperationResponseResultKey is the key variant.
type TransactionOperationResponseResultKey struct {
	Value *KeyResponse
}

func (*TransactionOperationResponseResultKey) isTransactionOperationResponseResult() {}

// TransactionOperationResponseResultKeys is the keys variant.
type TransactionOperationResponseResultKeys struct {
	Value *KeysResponse
}

func (*TransactionOperationResponseResultKeys) isTransactionOperationResponseResult() {}

// TransactionOperationResponseResultCount is the count variant.
type TransactionOperationResponseResultCount struct {
	Value *CountResponse
}

func (*TransactionOperationResponseResultCount) isTransactionOperationResponseResult() {}

// TransactionOperationResponseResultDelete is the delete variant.
type TransactionOperationResponseResultDelete struct {
	Value *DeleteResponse
}

func (*TransactionOperationResponseResultDelete) isTransactionOperationResponseResult() {}

// TransactionOperationResponse is the native message type for gestalt.provider.v1.TransactionOperationResponse.
//
// TransactionOperationResponse is the ordered response to one operation.
// Non-OK error marks the transaction failed and causes rollback in phase 1.
type TransactionOperationResponse struct {
	RequestId uint64
	Error     *RpcStatus
	Result    TransactionOperationResponseResult
}

// TransactionServerMessageMsg selects one variant of the msg oneof of TransactionServerMessage.
// A nil value means unset.
type TransactionServerMessageMsg interface {
	isTransactionServerMessageMsg()
}

// TransactionServerMessageMsgBegin is the begin variant.
type TransactionServerMessageMsgBegin struct {
	Value *TransactionBeginResponse
}

func (*TransactionServerMessageMsgBegin) isTransactionServerMessageMsg() {}

// TransactionServerMessageMsgOperation is the operation variant.
type TransactionServerMessageMsgOperation struct {
	Value *TransactionOperationResponse
}

func (*TransactionServerMessageMsgOperation) isTransactionServerMessageMsg() {}

// TransactionServerMessageMsgCommit is the commit variant.
type TransactionServerMessageMsgCommit struct {
	Value *TransactionCommitResponse
}

func (*TransactionServerMessageMsgCommit) isTransactionServerMessageMsg() {}

// TransactionServerMessageMsgAbort is the abort variant.
type TransactionServerMessageMsgAbort struct {
	Value *TransactionAbortResponse
}

func (*TransactionServerMessageMsgAbort) isTransactionServerMessageMsg() {}

// TransactionServerMessage is the native message type for gestalt.provider.v1.TransactionServerMessage.
type TransactionServerMessage struct {
	Msg TransactionServerMessageMsg
}

// TypedValueKind selects one variant of the kind oneof of TypedValue.
// A nil value means unset.
type TypedValueKind interface {
	isTypedValueKind()
}

// TypedValueKindNullValue is the nullValue variant. It carries no payload.
type TypedValueKindNullValue struct{}

func (*TypedValueKindNullValue) isTypedValueKind() {}

// TypedValueKindStringValue is the stringValue variant.
type TypedValueKindStringValue struct {
	Value string
}

func (*TypedValueKindStringValue) isTypedValueKind() {}

// TypedValueKindIntValue is the intValue variant.
type TypedValueKindIntValue struct {
	Value int64
}

func (*TypedValueKindIntValue) isTypedValueKind() {}

// TypedValueKindFloatValue is the floatValue variant.
type TypedValueKindFloatValue struct {
	Value float64
}

func (*TypedValueKindFloatValue) isTypedValueKind() {}

// TypedValueKindBoolValue is the boolValue variant.
type TypedValueKindBoolValue struct {
	Value bool
}

func (*TypedValueKindBoolValue) isTypedValueKind() {}

// TypedValueKindTimeValue is the timeValue variant.
type TypedValueKindTimeValue struct {
	Value time.Time
}

func (*TypedValueKindTimeValue) isTypedValueKind() {}

// TypedValueKindBytesValue is the bytesValue variant.
type TypedValueKindBytesValue struct {
	Value []byte
}

func (*TypedValueKindBytesValue) isTypedValueKind() {}

// TypedValueKindJsonValue is the jsonValue variant.
type TypedValueKindJsonValue struct {
	Value any
}

func (*TypedValueKindJsonValue) isTypedValueKind() {}

// TypedValue is the native message type for gestalt.provider.v1.TypedValue.
//
// TypedValue stores one scalar or structured value in an IndexedDB record.
type TypedValue struct {
	Kind TypedValueKind
}

// IndexedDB is the generated client for gestalt.provider.v1.IndexedDB.
// Every transport error is converted to *GestaltError.
//
// IndexedDB models the shared Gestalt IndexedDB-provider protocol.
type IndexedDB struct {
	client proto.IndexedDBClient
}

// NewIndexedDB creates a IndexedDB client over an injected gRPC connection.
func NewIndexedDB(conn grpc.ClientConnInterface) *IndexedDB {
	return &IndexedDB{client: proto.NewIndexedDBClient(conn)}
}

var connectIndexedDBConns host.ConnPool

// ConnectIndexedDB dials the "indexeddb" host service advertised through the
// GESTALT_HOST_SERVICE_SOCKET environment and returns a connected client.
// name selects a named binding; the empty string selects the default
// binding. Connections are pooled per binding and shared across clients for
// the life of the process. The first dial blocks until the connection is
// ready or ctx is done.
func ConnectIndexedDB(ctx context.Context, name string) (*IndexedDB, error) {
	target, token, err := host.Target("indexeddb")
	if err != nil {
		return nil, toGestaltError(err)
	}
	conn, err := connectIndexedDBConns.Conn(ctx, "indexeddb", target, token, name)
	if err != nil {
		return nil, toGestaltError(err)
	}
	return NewIndexedDB(conn), nil
}

// CreateObjectStore is the ergonomic form of [IndexedDB.CreateObjectStoreRaw].
//
// Lifecycle
func (c *IndexedDB) CreateObjectStore(ctx context.Context, name string, schema *ObjectStoreSchema) error {
	request := &CreateObjectStoreRequest{Name: name, Schema: schema}
	if _, err := c.client.CreateObjectStore(ctx, toWireCreateObjectStoreRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// CreateObjectStoreRaw is the faithful form of [IndexedDB.CreateObjectStore].
//
// Lifecycle
func (c *IndexedDB) CreateObjectStoreRaw(ctx context.Context, request *CreateObjectStoreRequest) error {
	if _, err := c.client.CreateObjectStore(ctx, toWireCreateObjectStoreRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// DeleteObjectStore is the ergonomic form of [IndexedDB.DeleteObjectStoreRaw].
func (c *IndexedDB) DeleteObjectStore(ctx context.Context, name string) error {
	request := &DeleteObjectStoreRequest{Name: name}
	if _, err := c.client.DeleteObjectStore(ctx, toWireDeleteObjectStoreRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// DeleteObjectStoreRaw is the faithful form of [IndexedDB.DeleteObjectStore].
func (c *IndexedDB) DeleteObjectStoreRaw(ctx context.Context, request *DeleteObjectStoreRequest) error {
	if _, err := c.client.DeleteObjectStore(ctx, toWireDeleteObjectStoreRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// Get is the ergonomic form of [IndexedDB.GetRaw].
//
// Primary key CRUD
func (c *IndexedDB) Get(ctx context.Context, store string, id string) (*RecordResponse, error) {
	request := &ObjectStoreRequest{Store: store, Id: id}
	response, err := c.client.Get(ctx, toWireObjectStoreRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireRecordResponse(response), nil
}

// GetRaw is the faithful form of [IndexedDB.Get].
//
// Primary key CRUD
func (c *IndexedDB) GetRaw(ctx context.Context, request *ObjectStoreRequest) (*RecordResponse, error) {
	response, err := c.client.Get(ctx, toWireObjectStoreRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireRecordResponse(response), nil
}

// GetKey is the ergonomic form of [IndexedDB.GetKeyRaw].
func (c *IndexedDB) GetKey(ctx context.Context, store string, id string) (*KeyResponse, error) {
	request := &ObjectStoreRequest{Store: store, Id: id}
	response, err := c.client.GetKey(ctx, toWireObjectStoreRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireKeyResponse(response), nil
}

// GetKeyRaw is the faithful form of [IndexedDB.GetKey].
func (c *IndexedDB) GetKeyRaw(ctx context.Context, request *ObjectStoreRequest) (*KeyResponse, error) {
	response, err := c.client.GetKey(ctx, toWireObjectStoreRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireKeyResponse(response), nil
}

// Add is the ergonomic form of [IndexedDB.AddRaw].
func (c *IndexedDB) Add(ctx context.Context, store string, record *Record) error {
	request := &RecordRequest{Store: store, Record: record}
	if _, err := c.client.Add(ctx, toWireRecordRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// AddRaw is the faithful form of [IndexedDB.Add].
func (c *IndexedDB) AddRaw(ctx context.Context, request *RecordRequest) error {
	if _, err := c.client.Add(ctx, toWireRecordRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// Put is the ergonomic form of [IndexedDB.PutRaw].
func (c *IndexedDB) Put(ctx context.Context, store string, record *Record) error {
	request := &RecordRequest{Store: store, Record: record}
	if _, err := c.client.Put(ctx, toWireRecordRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// PutRaw is the faithful form of [IndexedDB.Put].
func (c *IndexedDB) PutRaw(ctx context.Context, request *RecordRequest) error {
	if _, err := c.client.Put(ctx, toWireRecordRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// Delete is the ergonomic form of [IndexedDB.DeleteRaw].
func (c *IndexedDB) Delete(ctx context.Context, store string, id string) error {
	request := &ObjectStoreRequest{Store: store, Id: id}
	if _, err := c.client.Delete(ctx, toWireObjectStoreRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// DeleteRaw is the faithful form of [IndexedDB.Delete].
func (c *IndexedDB) DeleteRaw(ctx context.Context, request *ObjectStoreRequest) error {
	if _, err := c.client.Delete(ctx, toWireObjectStoreRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// Clear is the ergonomic form of [IndexedDB.ClearRaw].
//
// Bulk operations (with optional key range)
func (c *IndexedDB) Clear(ctx context.Context, store string) error {
	request := &ObjectStoreNameRequest{Store: store}
	if _, err := c.client.Clear(ctx, toWireObjectStoreNameRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// ClearRaw is the faithful form of [IndexedDB.Clear].
//
// Bulk operations (with optional key range)
func (c *IndexedDB) ClearRaw(ctx context.Context, request *ObjectStoreNameRequest) error {
	if _, err := c.client.Clear(ctx, toWireObjectStoreNameRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// GetAll is the ergonomic form of [IndexedDB.GetAllRaw].
func (c *IndexedDB) GetAll(ctx context.Context, store string, range_ *KeyRange) (*RecordsResponse, error) {
	request := &ObjectStoreRangeRequest{Store: store, Range: range_}
	response, err := c.client.GetAll(ctx, toWireObjectStoreRangeRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireRecordsResponse(response), nil
}

// GetAllRaw is the faithful form of [IndexedDB.GetAll].
func (c *IndexedDB) GetAllRaw(ctx context.Context, request *ObjectStoreRangeRequest) (*RecordsResponse, error) {
	response, err := c.client.GetAll(ctx, toWireObjectStoreRangeRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireRecordsResponse(response), nil
}

// GetAllKeys is the ergonomic form of [IndexedDB.GetAllKeysRaw].
func (c *IndexedDB) GetAllKeys(ctx context.Context, store string, range_ *KeyRange) (*KeysResponse, error) {
	request := &ObjectStoreRangeRequest{Store: store, Range: range_}
	response, err := c.client.GetAllKeys(ctx, toWireObjectStoreRangeRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireKeysResponse(response), nil
}

// GetAllKeysRaw is the faithful form of [IndexedDB.GetAllKeys].
func (c *IndexedDB) GetAllKeysRaw(ctx context.Context, request *ObjectStoreRangeRequest) (*KeysResponse, error) {
	response, err := c.client.GetAllKeys(ctx, toWireObjectStoreRangeRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireKeysResponse(response), nil
}

// Count is the ergonomic form of [IndexedDB.CountRaw].
func (c *IndexedDB) Count(ctx context.Context, store string, range_ *KeyRange) (*CountResponse, error) {
	request := &ObjectStoreRangeRequest{Store: store, Range: range_}
	response, err := c.client.Count(ctx, toWireObjectStoreRangeRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireCountResponse(response), nil
}

// CountRaw is the faithful form of [IndexedDB.Count].
func (c *IndexedDB) CountRaw(ctx context.Context, request *ObjectStoreRangeRequest) (*CountResponse, error) {
	response, err := c.client.Count(ctx, toWireObjectStoreRangeRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireCountResponse(response), nil
}

// DeleteRange is the ergonomic form of [IndexedDB.DeleteRangeRaw].
func (c *IndexedDB) DeleteRange(ctx context.Context, store string, range_ *KeyRange) (*DeleteResponse, error) {
	request := &ObjectStoreRangeRequest{Store: store, Range: range_}
	response, err := c.client.DeleteRange(ctx, toWireObjectStoreRangeRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireDeleteResponse(response), nil
}

// DeleteRangeRaw is the faithful form of [IndexedDB.DeleteRange].
func (c *IndexedDB) DeleteRangeRaw(ctx context.Context, request *ObjectStoreRangeRequest) (*DeleteResponse, error) {
	response, err := c.client.DeleteRange(ctx, toWireObjectStoreRangeRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireDeleteResponse(response), nil
}

// IndexGet is the ergonomic form of [IndexedDB.IndexGetRaw].
//
// Index queries
func (c *IndexedDB) IndexGet(ctx context.Context, store string, index string, values []*TypedValue, range_ *KeyRange) (*RecordResponse, error) {
	request := &IndexQueryRequest{Store: store, Index: index, Values: values, Range: range_}
	response, err := c.client.IndexGet(ctx, toWireIndexQueryRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireRecordResponse(response), nil
}

// IndexGetRaw is the faithful form of [IndexedDB.IndexGet].
//
// Index queries
func (c *IndexedDB) IndexGetRaw(ctx context.Context, request *IndexQueryRequest) (*RecordResponse, error) {
	response, err := c.client.IndexGet(ctx, toWireIndexQueryRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireRecordResponse(response), nil
}

// IndexGetKey is the ergonomic form of [IndexedDB.IndexGetKeyRaw].
func (c *IndexedDB) IndexGetKey(ctx context.Context, store string, index string, values []*TypedValue, range_ *KeyRange) (*KeyResponse, error) {
	request := &IndexQueryRequest{Store: store, Index: index, Values: values, Range: range_}
	response, err := c.client.IndexGetKey(ctx, toWireIndexQueryRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireKeyResponse(response), nil
}

// IndexGetKeyRaw is the faithful form of [IndexedDB.IndexGetKey].
func (c *IndexedDB) IndexGetKeyRaw(ctx context.Context, request *IndexQueryRequest) (*KeyResponse, error) {
	response, err := c.client.IndexGetKey(ctx, toWireIndexQueryRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireKeyResponse(response), nil
}

// IndexGetAll is the ergonomic form of [IndexedDB.IndexGetAllRaw].
func (c *IndexedDB) IndexGetAll(ctx context.Context, store string, index string, values []*TypedValue, range_ *KeyRange) (*RecordsResponse, error) {
	request := &IndexQueryRequest{Store: store, Index: index, Values: values, Range: range_}
	response, err := c.client.IndexGetAll(ctx, toWireIndexQueryRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireRecordsResponse(response), nil
}

// IndexGetAllRaw is the faithful form of [IndexedDB.IndexGetAll].
func (c *IndexedDB) IndexGetAllRaw(ctx context.Context, request *IndexQueryRequest) (*RecordsResponse, error) {
	response, err := c.client.IndexGetAll(ctx, toWireIndexQueryRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireRecordsResponse(response), nil
}

// IndexGetAllKeys is the ergonomic form of [IndexedDB.IndexGetAllKeysRaw].
func (c *IndexedDB) IndexGetAllKeys(ctx context.Context, store string, index string, values []*TypedValue, range_ *KeyRange) (*KeysResponse, error) {
	request := &IndexQueryRequest{Store: store, Index: index, Values: values, Range: range_}
	response, err := c.client.IndexGetAllKeys(ctx, toWireIndexQueryRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireKeysResponse(response), nil
}

// IndexGetAllKeysRaw is the faithful form of [IndexedDB.IndexGetAllKeys].
func (c *IndexedDB) IndexGetAllKeysRaw(ctx context.Context, request *IndexQueryRequest) (*KeysResponse, error) {
	response, err := c.client.IndexGetAllKeys(ctx, toWireIndexQueryRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireKeysResponse(response), nil
}

// IndexCount is the ergonomic form of [IndexedDB.IndexCountRaw].
func (c *IndexedDB) IndexCount(ctx context.Context, store string, index string, values []*TypedValue, range_ *KeyRange) (*CountResponse, error) {
	request := &IndexQueryRequest{Store: store, Index: index, Values: values, Range: range_}
	response, err := c.client.IndexCount(ctx, toWireIndexQueryRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireCountResponse(response), nil
}

// IndexCountRaw is the faithful form of [IndexedDB.IndexCount].
func (c *IndexedDB) IndexCountRaw(ctx context.Context, request *IndexQueryRequest) (*CountResponse, error) {
	response, err := c.client.IndexCount(ctx, toWireIndexQueryRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireCountResponse(response), nil
}

// IndexDelete is the ergonomic form of [IndexedDB.IndexDeleteRaw].
func (c *IndexedDB) IndexDelete(ctx context.Context, store string, index string, values []*TypedValue, range_ *KeyRange) (*DeleteResponse, error) {
	request := &IndexQueryRequest{Store: store, Index: index, Values: values, Range: range_}
	response, err := c.client.IndexDelete(ctx, toWireIndexQueryRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireDeleteResponse(response), nil
}

// IndexDeleteRaw is the faithful form of [IndexedDB.IndexDelete].
func (c *IndexedDB) IndexDeleteRaw(ctx context.Context, request *IndexQueryRequest) (*DeleteResponse, error) {
	response, err := c.client.IndexDelete(ctx, toWireIndexQueryRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireDeleteResponse(response), nil
}

// OpenCursor calls the OpenCursor RPC of IndexedDB.
//
// Cursor iteration (bidirectional stream)
func (c *IndexedDB) OpenCursor(ctx context.Context) (*IndexedDBOpenCursorStream, error) {
	stream, err := c.client.OpenCursor(ctx)
	if err != nil {
		return nil, toGestaltError(err)
	}
	return &IndexedDBOpenCursorStream{stream: stream}, nil
}

// Transaction calls the Transaction RPC of IndexedDB.
//
// Transaction stream. The first client message must be
// BeginTransactionRequest. Stream close before commit aborts the transaction.
func (c *IndexedDB) Transaction(ctx context.Context) (*IndexedDBTransactionStream, error) {
	stream, err := c.client.Transaction(ctx)
	if err != nil {
		return nil, toGestaltError(err)
	}
	return &IndexedDBTransactionStream{stream: stream}, nil
}

// Cursor iteration (bidirectional stream)
//
// IndexedDBOpenCursorStream is the bidirectional stream opened by
// IndexedDB.OpenCursor.
type IndexedDBOpenCursorStream struct {
	stream proto.IndexedDB_OpenCursorClient
}

// Send sends one frame. io.EOF reports a broken stream; the cause
// surfaces on the terminating call.
func (s *IndexedDBOpenCursorStream) Send(request *CursorClientMessage) error {
	return streamError(s.stream.Send(toWireCursorClientMessage(request)))
}

// Recv receives the next frame. io.EOF reports the normal end of the
// stream; every other error is a *GestaltError.
func (s *IndexedDBOpenCursorStream) Recv() (*CursorResponse, error) {
	frame, err := s.stream.Recv()
	if err != nil {
		return nil, streamError(err)
	}
	return fromWireCursorResponse(frame), nil
}

// CloseSend closes the send side of the stream.
func (s *IndexedDBOpenCursorStream) CloseSend() error {
	return streamError(s.stream.CloseSend())
}

// Transaction stream. The first client message must be
// BeginTransactionRequest. Stream close before commit aborts the transaction.
//
// IndexedDBTransactionStream is the bidirectional stream opened by
// IndexedDB.Transaction.
type IndexedDBTransactionStream struct {
	stream proto.IndexedDB_TransactionClient
}

// Send sends one frame. io.EOF reports a broken stream; the cause
// surfaces on the terminating call.
func (s *IndexedDBTransactionStream) Send(request *TransactionClientMessage) error {
	return streamError(s.stream.Send(toWireTransactionClientMessage(request)))
}

// Recv receives the next frame. io.EOF reports the normal end of the
// stream; every other error is a *GestaltError.
func (s *IndexedDBTransactionStream) Recv() (*TransactionServerMessage, error) {
	frame, err := s.stream.Recv()
	if err != nil {
		return nil, streamError(err)
	}
	return fromWireTransactionServerMessage(frame), nil
}

// CloseSend closes the send side of the stream.
func (s *IndexedDBTransactionStream) CloseSend() error {
	return streamError(s.stream.CloseSend())
}
