// Code generated by sdkgen. DO NOT EDIT.

package client

import (
	"context"
	"errors"
	"io"
	"time"

	"github.com/valon-technologies/gestalt/sdk/go/internal/host"
	proto "github.com/valon-technologies/gestalt/server/rpc/protov1/v1"
	"google.golang.org/grpc"
)

// PresignMethod is the gestalt.provider.v1.PresignMethod enum. It is open:
// numeric values outside the named constants are preserved.
//
// PresignMethod identifies the HTTP verb encoded into a presigned URL.
type PresignMethod int32

const (
	// PresignMethodUnspecified is the PRESIGN_METHOD_UNSPECIFIED value of PresignMethod.
	PresignMethodUnspecified PresignMethod = 0
	// PresignMethodGet is the PRESIGN_METHOD_GET value of PresignMethod.
	PresignMethodGet PresignMethod = 1
	// PresignMethodPut is the PRESIGN_METHOD_PUT value of PresignMethod.
	PresignMethodPut PresignMethod = 2
	// PresignMethodDelete is the PRESIGN_METHOD_DELETE value of PresignMethod.
	PresignMethodDelete PresignMethod = 3
	// PresignMethodHead is the PRESIGN_METHOD_HEAD value of PresignMethod.
	PresignMethodHead PresignMethod = 4
)

// ByteRange is the native message type for gestalt.provider.v1.ByteRange.
//
// ByteRange requests a half-open slice of an object's bytes.
type ByteRange struct {
	Start *int64
	End   *int64
}

// GetStart returns the start field; it is safe to call on a nil receiver.
func (x *ByteRange) GetStart() *int64 {
	if x == nil {
		return nil
	}
	return x.Start
}

// GetEnd returns the end field; it is safe to call on a nil receiver.
func (x *ByteRange) GetEnd() *int64 {
	if x == nil {
		return nil
	}
	return x.End
}

// CopyObjectRequest is the native message type for gestalt.provider.v1.CopyObjectRequest.
//
// CopyObjectRequest copies one object to another location.
type CopyObjectRequest struct {
	Source      *S3ObjectRef
	Destination *S3ObjectRef
	IfMatch     string
	IfNoneMatch string
}

// GetSource returns the source field; it is safe to call on a nil receiver.
func (x *CopyObjectRequest) GetSource() *S3ObjectRef {
	if x == nil {
		return nil
	}
	return x.Source
}

// GetDestination returns the destination field; it is safe to call on a nil receiver.
func (x *CopyObjectRequest) GetDestination() *S3ObjectRef {
	if x == nil {
		return nil
	}
	return x.Destination
}

// GetIfMatch returns the ifMatch field; it is safe to call on a nil receiver.
func (x *CopyObjectRequest) GetIfMatch() string {
	if x == nil {
		return ""
	}
	return x.IfMatch
}

// GetIfNoneMatch returns the ifNoneMatch field; it is safe to call on a nil receiver.
func (x *CopyObjectRequest) GetIfNoneMatch() string {
	if x == nil {
		return ""
	}
	return x.IfNoneMatch
}

// CopyObjectResponse is the native message type for gestalt.provider.v1.CopyObjectResponse.
//
// CopyObjectResponse returns metadata for the copied object.
type CopyObjectResponse struct {
	Meta *S3ObjectMeta
}

// GetMeta returns the meta field; it is safe to call on a nil receiver.
func (x *CopyObjectResponse) GetMeta() *S3ObjectMeta {
	if x == nil {
		return nil
	}
	return x.Meta
}

// CreateObjectAccessURLRequest is the native message type for gestalt.provider.v1.CreateObjectAccessURLRequest.
//
// CreateObjectAccessURLRequest asks the host to mint an HTTP object-access URL
// for a plugin-scoped S3 binding. The host authorizes and scopes the URL, then
// streams object bytes through the backing S3 provider.
type CreateObjectAccessURLRequest struct {
	Ref                *S3ObjectRef
	Method             PresignMethod
	ExpiresSeconds     int64
	ContentType        string
	ContentDisposition string
	Headers            map[string]string
}

// GetRef returns the ref field; it is safe to call on a nil receiver.
func (x *CreateObjectAccessURLRequest) GetRef() *S3ObjectRef {
	if x == nil {
		return nil
	}
	return x.Ref
}

// GetMethod returns the method field; it is safe to call on a nil receiver.
func (x *CreateObjectAccessURLRequest) GetMethod() PresignMethod {
	if x == nil {
		return 0
	}
	return x.Method
}

// GetExpiresSeconds returns the expiresSeconds field; it is safe to call on a nil receiver.
func (x *CreateObjectAccessURLRequest) GetExpiresSeconds() int64 {
	if x == nil {
		return 0
	}
	return x.ExpiresSeconds
}

// GetContentType returns the contentType field; it is safe to call on a nil receiver.
func (x *CreateObjectAccessURLRequest) GetContentType() string {
	if x == nil {
		return ""
	}
	return x.ContentType
}

// GetContentDisposition returns the contentDisposition field; it is safe to call on a nil receiver.
func (x *CreateObjectAccessURLRequest) GetContentDisposition() string {
	if x == nil {
		return ""
	}
	return x.ContentDisposition
}

// GetHeaders returns the headers field; it is safe to call on a nil receiver.
func (x *CreateObjectAccessURLRequest) GetHeaders() map[string]string {
	if x == nil {
		return nil
	}
	return x.Headers
}

// CreateObjectAccessURLResponse is the native message type for gestalt.provider.v1.CreateObjectAccessURLResponse.
//
// CreateObjectAccessURLResponse returns a hosted object-access URL plus any
// headers the caller must include when using it.
type CreateObjectAccessURLResponse struct {
	URL       string
	Method    PresignMethod
	ExpiresAt *time.Time
	Headers   map[string]string
}

// GetURL returns the url field; it is safe to call on a nil receiver.
func (x *CreateObjectAccessURLResponse) GetURL() string {
	if x == nil {
		return ""
	}
	return x.URL
}

// GetMethod returns the method field; it is safe to call on a nil receiver.
func (x *CreateObjectAccessURLResponse) GetMethod() PresignMethod {
	if x == nil {
		return 0
	}
	return x.Method
}

// GetExpiresAt returns the expiresAt field; it is safe to call on a nil receiver.
func (x *CreateObjectAccessURLResponse) GetExpiresAt() *time.Time {
	if x == nil {
		return nil
	}
	return x.ExpiresAt
}

// GetHeaders returns the headers field; it is safe to call on a nil receiver.
func (x *CreateObjectAccessURLResponse) GetHeaders() map[string]string {
	if x == nil {
		return nil
	}
	return x.Headers
}

// DeleteObjectRequest is the native message type for gestalt.provider.v1.DeleteObjectRequest.
//
// DeleteObjectRequest removes one object.
type DeleteObjectRequest struct {
	Ref *S3ObjectRef
}

// GetRef returns the ref field; it is safe to call on a nil receiver.
func (x *DeleteObjectRequest) GetRef() *S3ObjectRef {
	if x == nil {
		return nil
	}
	return x.Ref
}

// HeadObjectRequest is the native message type for gestalt.provider.v1.HeadObjectRequest.
//
// HeadObjectRequest fetches metadata for one object.
type HeadObjectRequest struct {
	Ref *S3ObjectRef
}

// GetRef returns the ref field; it is safe to call on a nil receiver.
func (x *HeadObjectRequest) GetRef() *S3ObjectRef {
	if x == nil {
		return nil
	}
	return x.Ref
}

// HeadObjectResponse is the native message type for gestalt.provider.v1.HeadObjectResponse.
//
// HeadObjectResponse returns object metadata.
type HeadObjectResponse struct {
	Meta *S3ObjectMeta
}

// GetMeta returns the meta field; it is safe to call on a nil receiver.
func (x *HeadObjectResponse) GetMeta() *S3ObjectMeta {
	if x == nil {
		return nil
	}
	return x.Meta
}

// ListObjectsRequest is the native message type for gestalt.provider.v1.ListObjectsRequest.
//
// ListObjectsRequest lists objects in the provider's configured bucket.
type ListObjectsRequest struct {
	Prefix            string
	Delimiter         string
	ContinuationToken string
	StartAfter        string
	MaxKeys           int32
}

// GetPrefix returns the prefix field; it is safe to call on a nil receiver.
func (x *ListObjectsRequest) GetPrefix() string {
	if x == nil {
		return ""
	}
	return x.Prefix
}

// GetDelimiter returns the delimiter field; it is safe to call on a nil receiver.
func (x *ListObjectsRequest) GetDelimiter() string {
	if x == nil {
		return ""
	}
	return x.Delimiter
}

// GetContinuationToken returns the continuationToken field; it is safe to call on a nil receiver.
func (x *ListObjectsRequest) GetContinuationToken() string {
	if x == nil {
		return ""
	}
	return x.ContinuationToken
}

// GetStartAfter returns the startAfter field; it is safe to call on a nil receiver.
func (x *ListObjectsRequest) GetStartAfter() string {
	if x == nil {
		return ""
	}
	return x.StartAfter
}

// GetMaxKeys returns the maxKeys field; it is safe to call on a nil receiver.
func (x *ListObjectsRequest) GetMaxKeys() int32 {
	if x == nil {
		return 0
	}
	return x.MaxKeys
}

// ListObjectsResponse is the native message type for gestalt.provider.v1.ListObjectsResponse.
//
// ListObjectsResponse is one page of list-objects results.
type ListObjectsResponse struct {
	Objects               []*S3ObjectMeta
	CommonPrefixes        []string
	NextContinuationToken string
	HasMore               bool
}

// GetObjects returns the objects field; it is safe to call on a nil receiver.
func (x *ListObjectsResponse) GetObjects() []*S3ObjectMeta {
	if x == nil {
		return nil
	}
	return x.Objects
}

// GetCommonPrefixes returns the commonPrefixes field; it is safe to call on a nil receiver.
func (x *ListObjectsResponse) GetCommonPrefixes() []string {
	if x == nil {
		return nil
	}
	return x.CommonPrefixes
}

// GetNextContinuationToken returns the nextContinuationToken field; it is safe to call on a nil receiver.
func (x *ListObjectsResponse) GetNextContinuationToken() string {
	if x == nil {
		return ""
	}
	return x.NextContinuationToken
}

// GetHasMore returns the hasMore field; it is safe to call on a nil receiver.
func (x *ListObjectsResponse) GetHasMore() bool {
	if x == nil {
		return false
	}
	return x.HasMore
}

// PresignObjectRequest is the native message type for gestalt.provider.v1.PresignObjectRequest.
//
// PresignObjectRequest asks the provider to mint a presigned URL.
type PresignObjectRequest struct {
	Ref                *S3ObjectRef
	Method             PresignMethod
	ExpiresSeconds     int64
	ContentType        string
	ContentDisposition string
	Headers            map[string]string
}

// GetRef returns the ref field; it is safe to call on a nil receiver.
func (x *PresignObjectRequest) GetRef() *S3ObjectRef {
	if x == nil {
		return nil
	}
	return x.Ref
}

// GetMethod returns the method field; it is safe to call on a nil receiver.
func (x *PresignObjectRequest) GetMethod() PresignMethod {
	if x == nil {
		return 0
	}
	return x.Method
}

// GetExpiresSeconds returns the expiresSeconds field; it is safe to call on a nil receiver.
func (x *PresignObjectRequest) GetExpiresSeconds() int64 {
	if x == nil {
		return 0
	}
	return x.ExpiresSeconds
}

// GetContentType returns the contentType field; it is safe to call on a nil receiver.
func (x *PresignObjectRequest) GetContentType() string {
	if x == nil {
		return ""
	}
	return x.ContentType
}

// GetContentDisposition returns the contentDisposition field; it is safe to call on a nil receiver.
func (x *PresignObjectRequest) GetContentDisposition() string {
	if x == nil {
		return ""
	}
	return x.ContentDisposition
}

// GetHeaders returns the headers field; it is safe to call on a nil receiver.
func (x *PresignObjectRequest) GetHeaders() map[string]string {
	if x == nil {
		return nil
	}
	return x.Headers
}

// PresignObjectResponse is the native message type for gestalt.provider.v1.PresignObjectResponse.
//
// PresignObjectResponse returns a presigned URL plus any required headers.
type PresignObjectResponse struct {
	URL       string
	Method    PresignMethod
	ExpiresAt *time.Time
	Headers   map[string]string
}

// GetURL returns the url field; it is safe to call on a nil receiver.
func (x *PresignObjectResponse) GetURL() string {
	if x == nil {
		return ""
	}
	return x.URL
}

// GetMethod returns the method field; it is safe to call on a nil receiver.
func (x *PresignObjectResponse) GetMethod() PresignMethod {
	if x == nil {
		return 0
	}
	return x.Method
}

// GetExpiresAt returns the expiresAt field; it is safe to call on a nil receiver.
func (x *PresignObjectResponse) GetExpiresAt() *time.Time {
	if x == nil {
		return nil
	}
	return x.ExpiresAt
}

// GetHeaders returns the headers field; it is safe to call on a nil receiver.
func (x *PresignObjectResponse) GetHeaders() map[string]string {
	if x == nil {
		return nil
	}
	return x.Headers
}

// ReadObjectChunkResult selects one variant of the result oneof of ReadObjectChunk.
// A nil value means unset.
type ReadObjectChunkResult interface {
	isReadObjectChunkResult()
}

// ReadObjectChunkResultMeta is the meta variant.
type ReadObjectChunkResultMeta struct {
	Value *S3ObjectMeta
}

func (*ReadObjectChunkResultMeta) isReadObjectChunkResult() {}

// ReadObjectChunkResultData is the data variant.
type ReadObjectChunkResultData struct {
	Value []byte
}

func (*ReadObjectChunkResultData) isReadObjectChunkResult() {}

// ReadObjectChunk is the native message type for gestalt.provider.v1.ReadObjectChunk.
//
// ReadObjectChunk is one frame in a streaming object read.
type ReadObjectChunk struct {
	Result ReadObjectChunkResult
}

// GetResult returns the result oneof; it is safe to call on a nil receiver.
func (x *ReadObjectChunk) GetResult() ReadObjectChunkResult {
	if x == nil {
		return nil
	}
	return x.Result
}

// ReadObjectRequest is the native message type for gestalt.provider.v1.ReadObjectRequest.
//
// ReadObjectRequest opens a streaming object read.
type ReadObjectRequest struct {
	Ref               *S3ObjectRef
	Range             *ByteRange
	IfMatch           string
	IfNoneMatch       string
	IfModifiedSince   *time.Time
	IfUnmodifiedSince *time.Time
}

// GetRef returns the ref field; it is safe to call on a nil receiver.
func (x *ReadObjectRequest) GetRef() *S3ObjectRef {
	if x == nil {
		return nil
	}
	return x.Ref
}

// GetRange returns the range field; it is safe to call on a nil receiver.
func (x *ReadObjectRequest) GetRange() *ByteRange {
	if x == nil {
		return nil
	}
	return x.Range
}

// GetIfMatch returns the ifMatch field; it is safe to call on a nil receiver.
func (x *ReadObjectRequest) GetIfMatch() string {
	if x == nil {
		return ""
	}
	return x.IfMatch
}

// GetIfNoneMatch returns the ifNoneMatch field; it is safe to call on a nil receiver.
func (x *ReadObjectRequest) GetIfNoneMatch() string {
	if x == nil {
		return ""
	}
	return x.IfNoneMatch
}

// GetIfModifiedSince returns the ifModifiedSince field; it is safe to call on a nil receiver.
func (x *ReadObjectRequest) GetIfModifiedSince() *time.Time {
	if x == nil {
		return nil
	}
	return x.IfModifiedSince
}

// GetIfUnmodifiedSince returns the ifUnmodifiedSince field; it is safe to call on a nil receiver.
func (x *ReadObjectRequest) GetIfUnmodifiedSince() *time.Time {
	if x == nil {
		return nil
	}
	return x.IfUnmodifiedSince
}

// S3ObjectMeta is the native message type for gestalt.provider.v1.S3ObjectMeta.
//
// S3ObjectMeta describes one object returned by the provider.
type S3ObjectMeta struct {
	Ref          *S3ObjectRef
	Etag         string
	Size         int64
	ContentType  string
	LastModified *time.Time
	Metadata     map[string]string
	StorageClass string
}

// GetRef returns the ref field; it is safe to call on a nil receiver.
func (x *S3ObjectMeta) GetRef() *S3ObjectRef {
	if x == nil {
		return nil
	}
	return x.Ref
}

// GetEtag returns the etag field; it is safe to call on a nil receiver.
func (x *S3ObjectMeta) GetEtag() string {
	if x == nil {
		return ""
	}
	return x.Etag
}

// GetSize returns the size field; it is safe to call on a nil receiver.
func (x *S3ObjectMeta) GetSize() int64 {
	if x == nil {
		return 0
	}
	return x.Size
}

// GetContentType returns the contentType field; it is safe to call on a nil receiver.
func (x *S3ObjectMeta) GetContentType() string {
	if x == nil {
		return ""
	}
	return x.ContentType
}

// GetLastModified returns the lastModified field; it is safe to call on a nil receiver.
func (x *S3ObjectMeta) GetLastModified() *time.Time {
	if x == nil {
		return nil
	}
	return x.LastModified
}

// GetMetadata returns the metadata field; it is safe to call on a nil receiver.
func (x *S3ObjectMeta) GetMetadata() map[string]string {
	if x == nil {
		return nil
	}
	return x.Metadata
}

// GetStorageClass returns the storageClass field; it is safe to call on a nil receiver.
func (x *S3ObjectMeta) GetStorageClass() string {
	if x == nil {
		return ""
	}
	return x.StorageClass
}

// S3ObjectRef is the native message type for gestalt.provider.v1.S3ObjectRef.
//
// S3ObjectRef identifies one object or object version.
type S3ObjectRef struct {
	Key       string
	VersionID string
}

// GetKey returns the key field; it is safe to call on a nil receiver.
func (x *S3ObjectRef) GetKey() string {
	if x == nil {
		return ""
	}
	return x.Key
}

// GetVersionID returns the versionId field; it is safe to call on a nil receiver.
func (x *S3ObjectRef) GetVersionID() string {
	if x == nil {
		return ""
	}
	return x.VersionID
}

// WriteObjectOpen is the native message type for gestalt.provider.v1.WriteObjectOpen.
//
// WriteObjectOpen carries the metadata frame that must be sent first in a
// write-object stream.
type WriteObjectOpen struct {
	Ref                *S3ObjectRef
	ContentType        string
	CacheControl       string
	ContentDisposition string
	ContentEncoding    string
	ContentLanguage    string
	Metadata           map[string]string
	IfMatch            string
	IfNoneMatch        string
}

// GetRef returns the ref field; it is safe to call on a nil receiver.
func (x *WriteObjectOpen) GetRef() *S3ObjectRef {
	if x == nil {
		return nil
	}
	return x.Ref
}

// GetContentType returns the contentType field; it is safe to call on a nil receiver.
func (x *WriteObjectOpen) GetContentType() string {
	if x == nil {
		return ""
	}
	return x.ContentType
}

// GetCacheControl returns the cacheControl field; it is safe to call on a nil receiver.
func (x *WriteObjectOpen) GetCacheControl() string {
	if x == nil {
		return ""
	}
	return x.CacheControl
}

// GetContentDisposition returns the contentDisposition field; it is safe to call on a nil receiver.
func (x *WriteObjectOpen) GetContentDisposition() string {
	if x == nil {
		return ""
	}
	return x.ContentDisposition
}

// GetContentEncoding returns the contentEncoding field; it is safe to call on a nil receiver.
func (x *WriteObjectOpen) GetContentEncoding() string {
	if x == nil {
		return ""
	}
	return x.ContentEncoding
}

// GetContentLanguage returns the contentLanguage field; it is safe to call on a nil receiver.
func (x *WriteObjectOpen) GetContentLanguage() string {
	if x == nil {
		return ""
	}
	return x.ContentLanguage
}

// GetMetadata returns the metadata field; it is safe to call on a nil receiver.
func (x *WriteObjectOpen) GetMetadata() map[string]string {
	if x == nil {
		return nil
	}
	return x.Metadata
}

// GetIfMatch returns the ifMatch field; it is safe to call on a nil receiver.
func (x *WriteObjectOpen) GetIfMatch() string {
	if x == nil {
		return ""
	}
	return x.IfMatch
}

// GetIfNoneMatch returns the ifNoneMatch field; it is safe to call on a nil receiver.
func (x *WriteObjectOpen) GetIfNoneMatch() string {
	if x == nil {
		return ""
	}
	return x.IfNoneMatch
}

// WriteObjectRequestMsg selects one variant of the msg oneof of WriteObjectRequest.
// A nil value means unset.
type WriteObjectRequestMsg interface {
	isWriteObjectRequestMsg()
}

// WriteObjectRequestMsgOpen is the open variant.
type WriteObjectRequestMsgOpen struct {
	Value *WriteObjectOpen
}

func (*WriteObjectRequestMsgOpen) isWriteObjectRequestMsg() {}

// WriteObjectRequestMsgData is the data variant.
type WriteObjectRequestMsgData struct {
	Value []byte
}

func (*WriteObjectRequestMsgData) isWriteObjectRequestMsg() {}

// WriteObjectRequest is the native message type for gestalt.provider.v1.WriteObjectRequest.
//
// WriteObjectRequest is one frame in a write-object stream.
type WriteObjectRequest struct {
	Msg WriteObjectRequestMsg
}

// GetMsg returns the msg oneof; it is safe to call on a nil receiver.
func (x *WriteObjectRequest) GetMsg() WriteObjectRequestMsg {
	if x == nil {
		return nil
	}
	return x.Msg
}

// WriteObjectResponse is the native message type for gestalt.provider.v1.WriteObjectResponse.
//
// WriteObjectResponse returns metadata for the committed object.
type WriteObjectResponse struct {
	Meta *S3ObjectMeta
}

// GetMeta returns the meta field; it is safe to call on a nil receiver.
func (x *WriteObjectResponse) GetMeta() *S3ObjectMeta {
	if x == nil {
		return nil
	}
	return x.Meta
}

// S3 is the generated client for gestalt.provider.v1.S3.
// Every transport error is converted to *GestaltError.
//
// S3 models the shared Gestalt S3-provider protocol.
type S3 struct {
	client proto.S3Client
}

// NewS3 creates a S3 client over an injected gRPC connection.
func NewS3(conn grpc.ClientConnInterface) *S3 {
	return &S3{client: proto.NewS3Client(conn)}
}

var connectS3Conns host.ConnPool

// ConnectS3 dials the "s3" host service advertised through the
// GESTALT_HOST_SERVICE_SOCKET environment and returns a connected client.
// name selects a named binding; the empty string selects the default
// binding. Connections are pooled per binding and shared across clients for
// the life of the process. The first dial blocks until the connection is
// ready or ctx is done.
func ConnectS3(ctx context.Context, name string) (*S3, error) {
	target, token, err := host.Target("s3")
	if err != nil {
		return nil, toGestaltError(err)
	}
	conn, err := connectS3Conns.Conn(ctx, "s3", target, token, name)
	if err != nil {
		return nil, toGestaltError(err)
	}
	return NewS3(conn), nil
}

// HeadObject is the ergonomic form of [S3.HeadObjectRaw].
func (c *S3) HeadObject(ctx context.Context, ref *S3ObjectRef) (*HeadObjectResponse, error) {
	request := &HeadObjectRequest{Ref: ref}
	response, err := c.client.HeadObject(ctx, toWireHeadObjectRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireHeadObjectResponse(response), nil
}

// HeadObjectRaw is the faithful form of [S3.HeadObject].
func (c *S3) HeadObjectRaw(ctx context.Context, request *HeadObjectRequest) (*HeadObjectResponse, error) {
	response, err := c.client.HeadObject(ctx, toWireHeadObjectRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireHeadObjectResponse(response), nil
}

// ReadObject is the ergonomic form of [S3.ReadObjectRaw]: it consumes the
// leading meta header frame and returns it beside the data payload
// stream.
//
// The first response frame carries object metadata. All subsequent frames
// carry byte chunks. Zero-byte objects therefore emit exactly one frame.
func (c *S3) ReadObject(ctx context.Context, request *ReadObjectRequest) (*S3ObjectMeta, *S3ReadObjectDataStream, error) {
	frames, err := c.ReadObjectRaw(ctx, request)
	if err != nil {
		return nil, nil, err
	}
	frame, err := frames.Recv()
	if err != nil && !errors.Is(err, io.EOF) {
		return nil, nil, err
	}
	if err != nil {
		return nil, nil, &GestaltError{Code: GestaltErrorCodeInternal, Message: "stream did not begin with the expected header frame"}
	}
	header, ok := frame.Result.(*ReadObjectChunkResultMeta)
	if !ok {
		return nil, nil, &GestaltError{Code: GestaltErrorCodeInternal, Message: "stream did not begin with the expected header frame"}
	}
	return header.Value, &S3ReadObjectDataStream{frames: frames}, nil
}

// ReadObjectRaw is the faithful form of [S3.ReadObject].
//
// The first response frame carries object metadata. All subsequent frames
// carry byte chunks. Zero-byte objects therefore emit exactly one frame.
func (c *S3) ReadObjectRaw(ctx context.Context, request *ReadObjectRequest) (*S3ReadObjectStream, error) {
	stream, err := c.client.ReadObject(ctx, toWireReadObjectRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return &S3ReadObjectStream{stream: stream}, nil
}

// WriteObject is the ergonomic form of [S3.WriteObjectRaw]: it sends the open
// header frame and returns the data payload stream.
//
// The first request frame must carry WriteObjectOpen metadata. All
// subsequent frames carry raw bytes. The response is emitted only after the
// object has been durably committed by the provider.
func (c *S3) WriteObject(ctx context.Context, open *WriteObjectOpen) (*S3WriteObjectDataStream, error) {
	frames, err := c.WriteObjectRaw(ctx)
	if err != nil {
		return nil, err
	}
	if err := frames.Send(&WriteObjectRequest{Msg: &WriteObjectRequestMsgOpen{Value: open}}); err != nil {
		// A failed header send reports a broken stream; surface the cause.
		if _, recvErr := frames.CloseAndRecv(); recvErr != nil {
			return nil, recvErr
		}
		return nil, toGestaltError(err)
	}
	return &S3WriteObjectDataStream{frames: frames}, nil
}

// WriteObjectRaw is the faithful form of [S3.WriteObject].
//
// The first request frame must carry WriteObjectOpen metadata. All
// subsequent frames carry raw bytes. The response is emitted only after the
// object has been durably committed by the provider.
func (c *S3) WriteObjectRaw(ctx context.Context) (*S3WriteObjectStream, error) {
	stream, err := c.client.WriteObject(ctx)
	if err != nil {
		return nil, toGestaltError(err)
	}
	return &S3WriteObjectStream{stream: stream}, nil
}

// DeleteObject is the ergonomic form of [S3.DeleteObjectRaw].
func (c *S3) DeleteObject(ctx context.Context, ref *S3ObjectRef) error {
	request := &DeleteObjectRequest{Ref: ref}
	if _, err := c.client.DeleteObject(ctx, toWireDeleteObjectRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// DeleteObjectRaw is the faithful form of [S3.DeleteObject].
func (c *S3) DeleteObjectRaw(ctx context.Context, request *DeleteObjectRequest) error {
	if _, err := c.client.DeleteObject(ctx, toWireDeleteObjectRequest(request)); err != nil {
		return toGestaltError(err)
	}
	return nil
}

// ListObjects is the ergonomic form of [S3.ListObjectsRaw].
func (c *S3) ListObjects(ctx context.Context, prefix string, delimiter string, continuationToken string, startAfter string, maxKeys int32) (*ListObjectsResponse, error) {
	request := &ListObjectsRequest{Prefix: prefix, Delimiter: delimiter, ContinuationToken: continuationToken, StartAfter: startAfter, MaxKeys: maxKeys}
	response, err := c.client.ListObjects(ctx, toWireListObjectsRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireListObjectsResponse(response), nil
}

// ListObjectsRaw is the faithful form of [S3.ListObjects].
func (c *S3) ListObjectsRaw(ctx context.Context, request *ListObjectsRequest) (*ListObjectsResponse, error) {
	response, err := c.client.ListObjects(ctx, toWireListObjectsRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireListObjectsResponse(response), nil
}

// CopyObject is the ergonomic form of [S3.CopyObjectRaw].
func (c *S3) CopyObject(ctx context.Context, ifMatch string, ifNoneMatch string, source *S3ObjectRef, destination *S3ObjectRef) (*CopyObjectResponse, error) {
	request := &CopyObjectRequest{IfMatch: ifMatch, IfNoneMatch: ifNoneMatch, Source: source, Destination: destination}
	response, err := c.client.CopyObject(ctx, toWireCopyObjectRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireCopyObjectResponse(response), nil
}

// CopyObjectRaw is the faithful form of [S3.CopyObject].
func (c *S3) CopyObjectRaw(ctx context.Context, request *CopyObjectRequest) (*CopyObjectResponse, error) {
	response, err := c.client.CopyObject(ctx, toWireCopyObjectRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireCopyObjectResponse(response), nil
}

// S3PresignObjectOptions carries the optional parameters of [S3.PresignObject].
// A nil options value is equivalent to the zero value.
type S3PresignObjectOptions struct {
	ContentType        string
	ContentDisposition string
}

// PresignObject is the ergonomic form of [S3.PresignObjectRaw].
func (c *S3) PresignObject(ctx context.Context, method PresignMethod, expiresSeconds int64, ref *S3ObjectRef, opts *S3PresignObjectOptions) (*PresignObjectResponse, error) {
	if opts == nil {
		opts = &S3PresignObjectOptions{}
	}
	request := &PresignObjectRequest{Method: method, ExpiresSeconds: expiresSeconds, Ref: ref, ContentType: opts.ContentType, ContentDisposition: opts.ContentDisposition}
	response, err := c.client.PresignObject(ctx, toWirePresignObjectRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWirePresignObjectResponse(response), nil
}

// PresignObjectRaw is the faithful form of [S3.PresignObject].
func (c *S3) PresignObjectRaw(ctx context.Context, request *PresignObjectRequest) (*PresignObjectResponse, error) {
	response, err := c.client.PresignObject(ctx, toWirePresignObjectRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWirePresignObjectResponse(response), nil
}

// The first response frame carries object metadata. All subsequent frames
// carry byte chunks. Zero-byte objects therefore emit exactly one frame.
//
// S3ReadObjectStream is the server stream of ReadObjectChunk frames
// returned by S3.ReadObjectRaw.
type S3ReadObjectStream struct {
	stream proto.S3_ReadObjectClient
}

// Recv receives the next frame. io.EOF reports the normal end of the
// stream; every other error is a *GestaltError.
func (s *S3ReadObjectStream) Recv() (*ReadObjectChunk, error) {
	frame, err := s.stream.Recv()
	if err != nil {
		return nil, streamError(err)
	}
	return fromWireReadObjectChunk(frame), nil
}

// S3ReadObjectDataStream is the stream of data payloads returned by
// S3.ReadObject after the header frame.
type S3ReadObjectDataStream struct {
	frames *S3ReadObjectStream
}

// Recv receives the next data payload. io.EOF reports the normal end of
// the stream; any other frame variant or transport failure is a
// *GestaltError.
func (s *S3ReadObjectDataStream) Recv() ([]byte, error) {
	frame, err := s.frames.Recv()
	if err != nil {
		return nil, err
	}
	chunk, ok := frame.Result.(*ReadObjectChunkResultData)
	if !ok {
		return nil, &GestaltError{Code: GestaltErrorCodeInternal, Message: "unexpected frame in payload stream"}
	}
	return chunk.Value, nil
}

// ReadAll buffers the remaining data payload into one byte slice, like
// io.ReadAll over the stream.
func (s *S3ReadObjectDataStream) ReadAll() ([]byte, error) {
	var out []byte
	for {
		chunk, err := s.Recv()
		if errors.Is(err, io.EOF) {
			return out, nil
		}
		if err != nil {
			return nil, err
		}
		out = append(out, chunk...)
	}
}

// The first request frame must carry WriteObjectOpen metadata. All
// subsequent frames carry raw bytes. The response is emitted only after the
// object has been durably committed by the provider.
//
// S3WriteObjectStream is the client stream of WriteObjectRequest frames
// accepted by S3.WriteObjectRaw.
type S3WriteObjectStream struct {
	stream proto.S3_WriteObjectClient
}

// Send sends one frame. io.EOF reports a broken stream; the cause
// surfaces on the terminating call.
func (s *S3WriteObjectStream) Send(request *WriteObjectRequest) error {
	return streamError(s.stream.Send(toWireWriteObjectRequest(request)))
}

// CloseAndRecv closes the send side and receives the response.
func (s *S3WriteObjectStream) CloseAndRecv() (*WriteObjectResponse, error) {
	response, err := s.stream.CloseAndRecv()
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireWriteObjectResponse(response), nil
}

// S3WriteObjectDataStream is the stream of data payloads accepted by
// S3.WriteObject after the header frame.
type S3WriteObjectDataStream struct {
	frames *S3WriteObjectStream
}

// Send sends one data payload. io.EOF reports a broken stream; the cause
// surfaces on CloseAndRecv.
func (s *S3WriteObjectDataStream) Send(data []byte) error {
	return s.frames.Send(&WriteObjectRequest{Msg: &WriteObjectRequestMsgData{Value: data}})
}

// CloseAndRecv closes the send side and receives the response.
func (s *S3WriteObjectDataStream) CloseAndRecv() (*WriteObjectResponse, error) {
	return s.frames.CloseAndRecv()
}

// S3ObjectAccess is the generated client for gestalt.provider.v1.S3ObjectAccess.
// Every transport error is converted to *GestaltError.
//
// S3ObjectAccess models host-mediated object access for plugin-scoped S3
// bindings. It is registered by gestaltd for apps and is not implemented by
// S3 providers.
type S3ObjectAccess struct {
	client proto.S3ObjectAccessClient
}

// NewS3ObjectAccess creates a S3ObjectAccess client over an injected gRPC connection.
func NewS3ObjectAccess(conn grpc.ClientConnInterface) *S3ObjectAccess {
	return &S3ObjectAccess{client: proto.NewS3ObjectAccessClient(conn)}
}

// S3ObjectAccessCreateObjectAccessURLOptions carries the optional parameters of [S3ObjectAccess.CreateObjectAccessURL].
// A nil options value is equivalent to the zero value.
type S3ObjectAccessCreateObjectAccessURLOptions struct {
	ContentType        string
	ContentDisposition string
}

// CreateObjectAccessURL is the ergonomic form of [S3ObjectAccess.CreateObjectAccessURLRaw].
func (c *S3ObjectAccess) CreateObjectAccessURL(ctx context.Context, method PresignMethod, expiresSeconds int64, ref *S3ObjectRef, opts *S3ObjectAccessCreateObjectAccessURLOptions) (*CreateObjectAccessURLResponse, error) {
	if opts == nil {
		opts = &S3ObjectAccessCreateObjectAccessURLOptions{}
	}
	request := &CreateObjectAccessURLRequest{Method: method, ExpiresSeconds: expiresSeconds, Ref: ref, ContentType: opts.ContentType, ContentDisposition: opts.ContentDisposition}
	response, err := c.client.CreateObjectAccessURL(ctx, toWireCreateObjectAccessURLRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireCreateObjectAccessURLResponse(response), nil
}

// CreateObjectAccessURLRaw is the faithful form of [S3ObjectAccess.CreateObjectAccessURL].
func (c *S3ObjectAccess) CreateObjectAccessURLRaw(ctx context.Context, request *CreateObjectAccessURLRequest) (*CreateObjectAccessURLResponse, error) {
	response, err := c.client.CreateObjectAccessURL(ctx, toWireCreateObjectAccessURLRequest(request))
	if err != nil {
		return nil, toGestaltError(err)
	}
	return fromWireCreateObjectAccessURLResponse(response), nil
}
