{{- $hasSecrets := false -}}
{{- if .Values.secrets.encryptionKey }}{{ $hasSecrets = true }}{{ end -}}
{{- if .Values.secrets.google.clientId }}{{ $hasSecrets = true }}{{ end -}}
{{- if .Values.secrets.google.clientSecret }}{{ $hasSecrets = true }}{{ end -}}
{{- if .Values.secrets.google.sessionSecret }}{{ $hasSecrets = true }}{{ end -}}
{{- if .Values.secrets.google.redirectUrl }}{{ $hasSecrets = true }}{{ end -}}
{{- if $hasSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "toolshed.fullname" . }}-secrets
  labels:
    {{- include "toolshed.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.encryptionKey }}
  ENCRYPTION_KEY: {{ .Values.secrets.encryptionKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.google.clientId }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.google.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.google.clientSecret }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.google.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.google.sessionSecret }}
  SESSION_SECRET: {{ .Values.secrets.google.sessionSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.google.redirectUrl }}
  GOOGLE_REDIRECT_URL: {{ .Values.secrets.google.redirectUrl | b64enc | quote }}
  {{- end }}
{{- end }}
