config:
  server:
    base_url: "https://toolshed.example.com"
    encryption_key: "ci-test-encryption-key"
  auth:
    config:
      client_id: "ci-test-client-id"
      client_secret: "ci-test-client-secret"

image:
  tag: "ci-test"

web:
  image:
    tag: "ci-test"
