name: Publish Toolshed Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish-api:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/valon-technologies/gestalt:latest
            ghcr.io/valon-technologies/gestalt:${{ github.sha }}

  publish-web:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: web
          file: web/Dockerfile
          push: true
          tags: |
            ghcr.io/valon-technologies/gestalt-web:latest
            ghcr.io/valon-technologies/gestalt-web:${{ github.sha }}
