// Code generated by sdkgen. DO NOT EDIT.

import { create } from "@bufbuild/protobuf";

import * as wire from "../gen/v1/test_pb.ts";
import type { HelloWorldRequest, HelloWorldResponse } from "../../test.ts";
import type { Init } from "../../rpc_support.ts";

export function toWireHelloWorldRequest(
  value: Init<HelloWorldRequest>,
): wire.HelloWorldRequest {
  return create(wire.HelloWorldRequestSchema, {});
}

export function fromWireHelloWorldRequest(
  value: wire.HelloWorldRequest,
): HelloWorldRequest {
  return {};
}

export function toWireHelloWorldResponse(
  value: Init<HelloWorldResponse>,
): wire.HelloWorldResponse {
  return create(wire.HelloWorldResponseSchema, {
    message: value.message ?? "",
  });
}

export function fromWireHelloWorldResponse(
  value: wire.HelloWorldResponse,
): HelloWorldResponse {
  return {
    message: value.message,
  };
}
